import { IngredientUnit, RecipeDifficulty } from '../../common/enums';
import type { SeedRecipe } from './recipes.seed';

/**
 * Platos que aparecen en animes conocidos. Son platos japoneses tradicionales
 * (o comidas caseras) con receta propia: no se copia texto ni fotos de libros
 * de cocina ni se usan personajes en el título. Cada una trae su versión en
 * inglés (`en`); ingredientNotes sigue el orden de `ingredients`.
 */
const G = IngredientUnit.GRAMS;
const KG = IngredientUnit.KILOGRAMS;
const ML = IngredientUnit.MILLILITERS;
const L = IngredientUnit.LITERS;
const UN = IngredientUnit.UNIT;

export const animeRecipes: SeedRecipe[] = [
  {
    title: 'Ramen de miso con chashu',
    description:
      'El ramen que se come en el puesto favorito de Naruto: caldo de miso, fideos, cerdo braseado (chashu), huevo marinado y cebolla de verdeo.',
    servings: 4,
    prepTimeMinutes: 180,
    difficulty: RecipeDifficulty.HARD,
    dietTags: ['anime'],
    estimatedCostTotal: 14000,
    nutrition: {
      calories: 780,
      proteinG: 42,
      fatG: 30,
      carbsG: 82,
      fiberG: 4,
      sugarG: 9,
      sodiumMg: 2400,
    },
    instructions: [
      'Chashu: atar la panceta enrollada con hilo de cocina. Dorarla en una olla con un poco de aceite por todos lados.',
      'Agregar 250 ml de agua, la salsa de soja, el mirin, el azúcar, la mitad del jengibre y 2 dientes de ajo. Tapar y cocinar a fuego bajo 2 horas, girándola cada 30 minutos.',
      'Huevos: hervirlos 6 minutos y medio, pasarlos a agua con hielo, pelarlos y dejarlos en un poco del líquido del chashu al menos 1 hora.',
      'Caldo: en otra olla saltear el resto del ajo y del jengibre con el aceite de sésamo. Agregar el caldo y llevar a hervor suave.',
      'Disolver la pasta de miso en un cucharón de caldo caliente y volver a la olla. No dejar que hierva fuerte después de agregar el miso.',
      'Cocinar los fideos según el paquete, escurrir y repartir en 4 bowls.',
      'Servir el caldo sobre los fideos. Cortar el chashu en rodajas y los huevos por la mitad, y acomodarlos arriba con la cebolla de verdeo, el nori y el sésamo.',
    ],
    tips: [
      'El chashu queda mejor si se cocina el día anterior y se corta frío.',
      'Si no conseguís fideos de ramen, sirven unos fideos finos al huevo.',
    ],
    ingredients: [
      {
        ingredientName: 'Panceta',
        quantity: 600,
        unit: G,
        notes: 'en una pieza, para el chashu',
      },
      { ingredientName: 'Salsa de soja', quantity: 120, unit: ML },
      { ingredientName: 'Mirin', quantity: 60, unit: ML },
      { ingredientName: 'Azúcar', quantity: 30, unit: G },
      {
        ingredientName: 'Jengibre',
        quantity: 20,
        unit: G,
        notes: 'en rodajas, dividido',
      },
      {
        ingredientName: 'Ajo',
        quantity: 4,
        unit: UN,
        notes: 'dientes, dividido',
      },
      { ingredientName: 'Huevo', quantity: 4, unit: UN },
      { ingredientName: 'Aceite de sésamo', quantity: 15, unit: ML },
      {
        ingredientName: 'Caldo',
        quantity: 1.6,
        unit: L,
        notes: 'de pollo o de cerdo',
      },
      { ingredientName: 'Pasta de miso', quantity: 100, unit: G },
      {
        ingredientName: 'Fideos',
        quantity: 500,
        unit: G,
        notes: 'de ramen o finos al huevo',
      },
      {
        ingredientName: 'Cebolla de verdeo',
        quantity: 3,
        unit: UN,
        notes: 'en rodajas finas',
      },
      {
        ingredientName: 'Alga nori',
        quantity: 4,
        unit: UN,
        notes: 'hojas cortadas en rectángulos',
      },
      { ingredientName: 'Semillas de sésamo', quantity: 10, unit: G },
    ],
    en: {
      title: 'Miso ramen with chashu',
      description:
        "The ramen from Naruto's favorite noodle stand: miso broth, noodles, braised pork (chashu), marinated egg and scallions.",
      instructions: [
        'Chashu: roll the pork belly and tie it with kitchen twine. Brown it on all sides in a pot with a little oil.',
        'Add 250 ml of water, the soy sauce, mirin, sugar, half the ginger and 2 garlic cloves. Cover and simmer on low for 2 hours, turning it every 30 minutes.',
        'Eggs: boil them for 6 and a half minutes, move them to ice water, peel them and soak them in some of the chashu liquid for at least 1 hour.',
        'Broth: in another pot sauté the rest of the garlic and ginger in the sesame oil. Add the stock and bring to a gentle boil.',
        'Dissolve the miso paste in a ladle of hot broth and stir it back into the pot. Do not let it boil hard after adding the miso.',
        'Cook the noodles according to the package, drain and divide them among 4 bowls.',
        'Pour the broth over the noodles. Slice the chashu and halve the eggs, and arrange them on top with the scallions, nori and sesame seeds.',
      ],
      tips: [
        'Chashu is even better cooked the day before and sliced cold.',
        "If you can't find ramen noodles, thin egg noodles work well.",
      ],
      ingredientNotes: [
        'in one piece, for the chashu',
        null,
        null,
        null,
        'sliced, divided',
        'cloves, divided',
        null,
        null,
        'chicken or pork',
        null,
        'ramen or thin egg noodles',
        'thinly sliced',
        'sheets cut into rectangles',
        null,
      ],
    },
  },
  {
    title: 'Onigiri de salmón y de atún',
    description:
      'Las bolitas de arroz que aparecen en Naruto y Fruits Basket: arroz blanco, relleno de salmón o atún con mayonesa y una tira de alga nori.',
    servings: 4,
    prepTimeMinutes: 45,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['anime'],
    estimatedCostTotal: 6500,
    nutrition: {
      calories: 420,
      proteinG: 18,
      fatG: 9,
      carbsG: 66,
      fiberG: 1,
      sugarG: 2,
      sodiumMg: 650,
    },
    instructions: [
      'Lavar el arroz hasta que el agua salga casi transparente. Cocinarlo con 600 ml de agua, tapado, 15 minutos a fuego bajo y dejarlo reposar tapado 10 minutos.',
      'Relleno de salmón: cocinar el salmón a la plancha con una pizca de sal, desmenuzarlo y mezclarlo con la mitad de la salsa de soja.',
      'Relleno de atún: escurrir el atún y mezclarlo con la mayonesa y el resto de la salsa de soja.',
      'Mojarse las manos con agua y frotarlas con un poco de sal. Tomar un puñado de arroz tibio y aplanarlo en la palma.',
      'Poner una cucharadita de relleno en el centro, cerrar con más arroz y darle forma de triángulo apretando suave.',
      'Envolver la base de cada onigiri con una tira de alga nori justo antes de comer, para que quede crocante.',
    ],
    tips: [
      'Usá arroz de grano corto o arroz para sushi: es el que mejor se pega.',
    ],
    ingredients: [
      {
        ingredientName: 'Arroz',
        quantity: 500,
        unit: G,
        notes: 'de grano corto o para sushi',
      },
      { ingredientName: 'Salmón', quantity: 150, unit: G },
      { ingredientName: 'Atún', quantity: 170, unit: G, notes: '1 lata' },
      { ingredientName: 'Mayonesa', quantity: 30, unit: G },
      {
        ingredientName: 'Salsa de soja',
        quantity: 20,
        unit: ML,
        notes: 'dividida',
      },
      { ingredientName: 'Sal', quantity: 5, unit: G },
      {
        ingredientName: 'Alga nori',
        quantity: 3,
        unit: UN,
        notes: 'hojas cortadas en tiras',
      },
    ],
    en: {
      title: 'Salmon and tuna onigiri',
      description:
        'The rice balls seen in Naruto and Fruits Basket: white rice filled with salmon or tuna mayo and wrapped with a strip of nori.',
      instructions: [
        'Rinse the rice until the water runs almost clear. Cook it with 600 ml of water, covered, for 15 minutes on low heat and let it rest covered for 10 minutes.',
        'Salmon filling: grill the salmon with a pinch of salt, flake it and mix it with half the soy sauce.',
        'Tuna filling: drain the tuna and mix it with the mayonnaise and the rest of the soy sauce.',
        'Wet your hands and rub them with a little salt. Take a handful of warm rice and flatten it in your palm.',
        'Put a teaspoon of filling in the center, close it with more rice and gently press it into a triangle.',
        'Wrap the bottom of each onigiri with a strip of nori just before eating so it stays crisp.',
      ],
      tips: ['Use short-grain or sushi rice: it sticks together best.'],
      ingredientNotes: [
        'short-grain or sushi rice',
        null,
        '1 can',
        null,
        'divided',
        null,
        'sheets cut into strips',
      ],
    },
  },
  {
    title: 'Katsudon',
    description:
      'El bowl de arroz con milanesa de cerdo, cebolla y huevo que es el plato favorito del protagonista de Yuri!!! on Ice (y de muchos personajes de anime antes de una competencia).',
    servings: 2,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['anime'],
    estimatedCostTotal: 7500,
    nutrition: {
      calories: 890,
      proteinG: 45,
      fatG: 32,
      carbsG: 98,
      fiberG: 3,
      sugarG: 10,
      sodiumMg: 1500,
    },
    instructions: [
      'Cocinar el arroz y mantenerlo caliente.',
      'Aplanar los bifes de cerdo, salpimentarlos y pasarlos por harina, por 1 huevo batido y por pan rallado.',
      'Freírlos en aceite caliente 3 a 4 minutos por lado hasta que estén dorados. Escurrirlos y cortarlos en tiras.',
      'En una sartén chica poner el caldo, la salsa de soja, el mirin y el azúcar. Agregar la cebolla en pluma y cocinar 5 minutos.',
      'Acomodar una milanesa cortada sobre la cebolla, verter por encima 1 huevo batido y tapar 1 minuto, hasta que el huevo quede apenas cuajado.',
      'Deslizarlo sobre un bowl de arroz y repetir con la otra porción. Terminar con cebolla de verdeo.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 300, unit: G },
      {
        ingredientName: 'Cerdo (magro)',
        quantity: 300,
        unit: G,
        notes: '2 bifes de lomo o bondiola',
      },
      { ingredientName: 'Harina', quantity: 30, unit: G },
      {
        ingredientName: 'Huevo',
        quantity: 3,
        unit: UN,
        notes: '1 para rebozar y 2 para cubrir',
      },
      {
        ingredientName: 'Pan rallado',
        quantity: 80,
        unit: G,
        notes: 'mejor si es panko',
      },
      {
        ingredientName: 'Aceite',
        quantity: 300,
        unit: ML,
        notes: 'para freír',
      },
      { ingredientName: 'Caldo', quantity: 200, unit: ML },
      { ingredientName: 'Salsa de soja', quantity: 40, unit: ML },
      { ingredientName: 'Mirin', quantity: 30, unit: ML },
      { ingredientName: 'Azúcar', quantity: 10, unit: G },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN, notes: 'en pluma' },
      { ingredientName: 'Cebolla de verdeo', quantity: 1, unit: UN },
    ],
    en: {
      title: 'Katsudon',
      description:
        "The rice bowl with breaded pork cutlet, onion and egg: the protagonist's favorite dish in Yuri!!! on Ice (and a classic pre-competition meal in anime).",
      instructions: [
        'Cook the rice and keep it warm.',
        'Pound the pork steaks flat, season them and coat them in flour, 1 beaten egg and breadcrumbs.',
        'Fry them in hot oil for 3 to 4 minutes per side until golden. Drain and cut into strips.',
        'In a small pan add the stock, soy sauce, mirin and sugar. Add the sliced onion and cook for 5 minutes.',
        'Lay one sliced cutlet over the onion, pour 1 beaten egg over it and cover for 1 minute, until the egg is just set.',
        'Slide it onto a bowl of rice and repeat with the other portion. Top with scallions.',
      ],
      ingredientNotes: [
        null,
        '2 loin or shoulder steaks',
        null,
        '1 for breading and 2 for topping',
        'panko is best',
        'for frying',
        null,
        null,
        null,
        null,
        'sliced',
        null,
      ],
    },
  },
  {
    title: 'Mitarashi dango',
    description:
      'Brochetas de bolitas de arroz asadas con salsa dulce de soja, el dulce que se ve en Demon Slayer y en Naruto.',
    servings: 4,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['anime', 'vegetariano'],
    estimatedCostTotal: 3500,
    nutrition: {
      calories: 260,
      proteinG: 4,
      fatG: 1,
      carbsG: 58,
      fiberG: 1,
      sugarG: 16,
      sodiumMg: 600,
    },
    instructions: [
      'Mezclar la harina de arroz con el azúcar e ir agregando agua tibia de a poco hasta lograr una masa suave que no se pegue, como plastilina.',
      'Formar 16 bolitas del mismo tamaño.',
      'Hervirlas en agua hasta que floten y 2 minutos más. Pasarlas a agua fría y escurrir.',
      'Ensartar 4 bolitas por brocheta y dorarlas en una sartén o a la parrilla hasta que tengan marcas.',
      'Salsa: en una ollita mezclar la salsa de soja, el azúcar restante, el agua y el almidón de maíz. Cocinar revolviendo hasta que espese y brille.',
      'Bañar las brochetas con la salsa tibia y servir.',
    ],
    tips: [
      'La harina de arroz común sirve, pero con harina de arroz glutinoso (mochiko) quedan más elásticas.',
    ],
    ingredients: [
      {
        ingredientName: 'Harina de arroz',
        quantity: 200,
        unit: G,
        notes: 'mejor si es glutinoso (mochiko)',
      },
      {
        ingredientName: 'Azúcar',
        quantity: 60,
        unit: G,
        notes: '20 g para la masa y 40 g para la salsa',
      },
      {
        ingredientName: 'Agua',
        quantity: 280,
        unit: ML,
        notes: '180 ml tibia para la masa y 100 ml para la salsa',
      },
      { ingredientName: 'Salsa de soja', quantity: 30, unit: ML },
      { ingredientName: 'Almidón de maíz', quantity: 10, unit: G },
    ],
    en: {
      title: 'Mitarashi dango',
      description:
        'Skewers of grilled rice dumplings glazed with a sweet soy sauce, the treat seen in Demon Slayer and Naruto.',
      instructions: [
        'Mix the rice flour with the sugar and gradually add warm water until you get a soft dough that does not stick, like modeling clay.',
        'Shape 16 balls of the same size.',
        'Boil them until they float, plus 2 more minutes. Move them to cold water and drain.',
        'Thread 4 balls onto each skewer and brown them in a pan or on the grill until they have marks.',
        'Sauce: in a small pot mix the soy sauce, the remaining sugar, water and cornstarch. Cook while stirring until thick and glossy.',
        'Coat the skewers with the warm sauce and serve.',
      ],
      tips: [
        'Regular rice flour works, but glutinous rice flour (mochiko) makes them chewier.',
      ],
      ingredientNotes: [
        'glutinous (mochiko) is best',
        '20 g for the dough and 40 g for the sauce',
        '180 ml warm for the dough and 100 ml for the sauce',
        null,
        null,
      ],
    },
  },
  {
    title: 'Sakura mochi',
    description:
      'Mochi rosado relleno de pasta de porotos dulces, el dulce de primavera japonés que aparece en Demon Slayer.',
    servings: 8,
    prepTimeMinutes: 90,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['anime', 'vegetariano', 'vegano'],
    estimatedCostTotal: 5000,
    nutrition: {
      calories: 190,
      proteinG: 4,
      fatG: 0.5,
      carbsG: 42,
      fiberG: 3,
      sugarG: 20,
      sodiumMg: 40,
    },
    instructions: [
      'Pasta de porotos: remojar los porotos aduki toda la noche. Hervirlos en agua nueva 1 hora o hasta que se deshagan.',
      'Escurrirlos, pisarlos y volverlos al fuego con 100 g de azúcar y la sal, revolviendo hasta que la pasta se despegue de la olla. Dejar enfriar y formar 8 bolitas.',
      'Masa: mezclar la harina de arroz con el resto del azúcar, el agua y 1 gota de colorante rojo hasta que quede rosa claro.',
      'Cocinar la masa en el microondas 1 minuto, revolver con una cuchara mojada y repetir 2 o 3 veces hasta que quede elástica y translúcida.',
      'Con las manos mojadas dividirla en 8, aplanar cada parte, poner una bolita de pasta en el centro y cerrar.',
      'Servir el mismo día; en Japón se envuelven en una hoja de cerezo en salmuera.',
    ],
    ingredients: [
      {
        ingredientName: 'Porotos aduki',
        quantity: 200,
        unit: G,
        notes: 'o porotos rojos chicos',
      },
      {
        ingredientName: 'Azúcar',
        quantity: 150,
        unit: G,
        notes: '100 g para la pasta y 50 g para la masa',
      },
      { ingredientName: 'Sal', quantity: 1, unit: G },
      {
        ingredientName: 'Harina de arroz',
        quantity: 150,
        unit: G,
        notes: 'glutinoso (mochiko)',
      },
      { ingredientName: 'Agua', quantity: 200, unit: ML },
      {
        ingredientName: 'Colorante alimentario',
        quantity: 1,
        unit: UN,
        notes: '1 gota de rojo',
      },
    ],
    en: {
      title: 'Sakura mochi',
      description:
        'Pink mochi filled with sweet red bean paste, the Japanese spring treat seen in Demon Slayer.',
      instructions: [
        'Bean paste: soak the azuki beans overnight. Boil them in fresh water for 1 hour or until they fall apart.',
        'Drain, mash and return them to the heat with 100 g of sugar and the salt, stirring until the paste pulls away from the pot. Let it cool and shape 8 balls.',
        'Dough: mix the rice flour with the rest of the sugar, the water and 1 drop of red coloring until light pink.',
        'Microwave the dough for 1 minute, stir with a wet spoon and repeat 2 or 3 times until stretchy and translucent.',
        'With wet hands divide it into 8, flatten each piece, put a ball of paste in the center and close it.',
        'Serve the same day; in Japan they are wrapped in a pickled cherry leaf.',
      ],
      ingredientNotes: [
        'or small red beans',
        '100 g for the paste and 50 g for the dough',
        null,
        'glutinous (mochiko)',
        null,
        '1 drop of red',
      ],
    },
  },
  {
    title: 'Ramen con jamón y huevo',
    description:
      'El ramen instantáneo mejorado de Ponyo (Studio Ghibli): fideos en caldo con jamón, huevo y cebolla de verdeo, listo en 10 minutos.',
    servings: 2,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['anime', 'economico'],
    estimatedCostTotal: 3000,
    nutrition: {
      calories: 520,
      proteinG: 25,
      fatG: 18,
      carbsG: 62,
      fiberG: 2,
      sugarG: 3,
      sodiumMg: 1900,
    },
    instructions: [
      'Hervir el caldo con la salsa de soja.',
      'Agregar los fideos y cocinar según el paquete (unos 3 minutos).',
      'Mientras tanto, hervir los huevos 6 minutos, enfriarlos y pelarlos.',
      'Servir los fideos con el caldo en dos bowls.',
      'Acomodar arriba 2 fetas de jamón, medio huevo y la cebolla de verdeo picada. Tapar el bowl 1 minuto antes de comer, como en la película.',
    ],
    ingredients: [
      { ingredientName: 'Caldo', quantity: 800, unit: ML },
      { ingredientName: 'Salsa de soja', quantity: 15, unit: ML },
      {
        ingredientName: 'Fideos',
        quantity: 200,
        unit: G,
        notes: 'de ramen o instantáneos',
      },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Jamón', quantity: 80, unit: G, notes: '4 fetas' },
      { ingredientName: 'Cebolla de verdeo', quantity: 1, unit: UN },
    ],
    en: {
      title: 'Ramen with ham and egg',
      description:
        "Ponyo's upgraded instant ramen (Studio Ghibli): noodles in broth with ham, egg and scallions, ready in 10 minutes.",
      instructions: [
        'Bring the stock to a boil with the soy sauce.',
        'Add the noodles and cook according to the package (about 3 minutes).',
        'Meanwhile, boil the eggs for 6 minutes, cool and peel them.',
        'Serve the noodles and broth in two bowls.',
        'Top with 2 slices of ham, half an egg and chopped scallions. Cover the bowl for 1 minute before eating, just like in the movie.',
      ],
      ingredientNotes: [
        null,
        null,
        'ramen or instant noodles',
        null,
        '4 slices',
        null,
      ],
    },
  },
  {
    title: 'Huevos con panceta a la sartén',
    description:
      'El desayuno que se cocina sobre el fuego en El increíble castillo vagabundo (Studio Ghibli): panceta crocante, huevos fritos y pan tostado.',
    servings: 2,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['anime', 'proteico', 'economico'],
    estimatedCostTotal: 3500,
    nutrition: {
      calories: 560,
      proteinG: 28,
      fatG: 38,
      carbsG: 26,
      fiberG: 1,
      sugarG: 2,
      sodiumMg: 1100,
    },
    instructions: [
      'Poner las fetas de panceta en una sartén fría y llevar a fuego medio. Cocinarlas hasta que estén crocantes, dándolas vuelta.',
      'Correr la panceta a un costado y cascar los huevos en la grasa caliente.',
      'Tapar 2 minutos para que la clara se cocine y la yema quede líquida. Salpimentar.',
      'Tostar el pan en la misma sartén o en la tostadora.',
      'Servir todo en el plato, con los huevos sobre el pan si te gusta mojar la yema.',
    ],
    ingredients: [
      {
        ingredientName: 'Panceta',
        quantity: 120,
        unit: G,
        notes: 'en fetas gruesas',
      },
      { ingredientName: 'Huevo', quantity: 4, unit: UN },
      {
        ingredientName: 'Pan',
        quantity: 2,
        unit: UN,
        notes: 'rodajas gruesas',
      },
      { ingredientName: 'Sal', quantity: 1, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
    ],
    en: {
      title: 'Pan-fried bacon and eggs',
      description:
        "The breakfast cooked over the fire in Howl's Moving Castle (Studio Ghibli): crispy bacon, fried eggs and toast.",
      instructions: [
        'Place the bacon slices in a cold pan and bring to medium heat. Cook until crispy, turning them over.',
        'Push the bacon to one side and crack the eggs into the hot fat.',
        'Cover for 2 minutes so the whites cook and the yolks stay runny. Season with salt and pepper.',
        'Toast the bread in the same pan or in a toaster.',
        'Serve everything on the plate, with the eggs over the bread if you like dipping the yolk.',
      ],
      ingredientNotes: ['thick slices', null, 'thick slices', null, null],
    },
  },
  {
    title: 'Guiso de carne al estilo Ghibli',
    description:
      'Guiso casero de carne, papa, zanahoria y cebolla, como el que se come en El castillo en el cielo (Studio Ghibli).',
    servings: 4,
    prepTimeMinutes: 120,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['anime', 'proteico'],
    estimatedCostTotal: 12000,
    nutrition: {
      calories: 520,
      proteinG: 38,
      fatG: 20,
      carbsG: 40,
      fiberG: 6,
      sugarG: 8,
      sodiumMg: 900,
    },
    instructions: [
      'Cortar la carne en cubos grandes, salpimentarla y pasarla por la harina.',
      'Dorarla en tandas en una olla con aceite y reservar.',
      'En la misma olla rehogar la cebolla y el ajo. Agregar la salsa de tomate y el vino y raspar el fondo.',
      'Volver la carne a la olla, cubrir con el caldo, sumar el laurel y cocinar tapado a fuego bajo 1 hora.',
      'Agregar la papa y la zanahoria en trozos y cocinar 30 minutos más, hasta que estén tiernas y el caldo espese.',
      'Servir caliente con pan.',
    ],
    ingredients: [
      {
        ingredientName: 'Carne (bife)',
        quantity: 800,
        unit: G,
        notes: 'para guisar, en cubos',
      },
      { ingredientName: 'Harina', quantity: 20, unit: G },
      { ingredientName: 'Aceite', quantity: 30, unit: ML },
      { ingredientName: 'Cebolla', quantity: 2, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'dientes' },
      { ingredientName: 'Salsa de tomate', quantity: 150, unit: G },
      { ingredientName: 'Vino tinto', quantity: 150, unit: ML },
      { ingredientName: 'Caldo', quantity: 800, unit: ML },
      { ingredientName: 'Laurel', quantity: 2, unit: UN, notes: 'hojas' },
      { ingredientName: 'Papa', quantity: 3, unit: UN },
      { ingredientName: 'Zanahoria', quantity: 2, unit: UN },
      { ingredientName: 'Sal', quantity: 5, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 2, unit: G },
    ],
    en: {
      title: 'Ghibli-style beef stew',
      description:
        'A homemade stew of beef, potato, carrot and onion, like the one eaten in Castle in the Sky (Studio Ghibli).',
      instructions: [
        'Cut the beef into large cubes, season it and dust it with flour.',
        'Brown it in batches in a pot with oil and set aside.',
        'In the same pot cook the onion and garlic until soft. Add the tomato sauce and wine and scrape the bottom.',
        'Return the beef, cover with the stock, add the bay leaves and simmer covered on low heat for 1 hour.',
        'Add the potato and carrot in chunks and cook 30 more minutes, until tender and the stew thickens.',
        'Serve hot with bread.',
      ],
      ingredientNotes: [
        'stewing beef, cubed',
        null,
        null,
        null,
        'cloves',
        null,
        null,
        null,
        'leaves',
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Panqueques soufflé japoneses',
    description:
      'Panqueques altísimos y esponjosos, de los que aparecen en Your Name y en tantas escenas de cafetería del anime.',
    servings: 2,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['anime', 'vegetariano'],
    estimatedCostTotal: 2500,
    nutrition: {
      calories: 340,
      proteinG: 12,
      fatG: 12,
      carbsG: 45,
      fiberG: 1,
      sugarG: 22,
      sodiumMg: 250,
    },
    instructions: [
      'Separar las claras de las yemas. Mezclar las yemas con la leche, la vainilla, la harina y el polvo de hornear hasta que no queden grumos.',
      'Batir las claras con el azúcar hasta punto nieve firme.',
      'Incorporar las claras a la mezcla de yemas en 3 veces, con movimientos envolventes y sin batir.',
      'Calentar una sartén antiadherente a fuego mínimo con un poco de manteca. Poner 3 montoncitos altos de mezcla (usar aros si tenés).',
      'Agregar 1 cucharada de agua en la sartén, tapar y cocinar 5 minutos. Dar vuelta con cuidado, sumar otra cucharada de agua, tapar y cocinar 5 minutos más.',
      'Servir enseguida con manteca, miel o frutillas.',
    ],
    tips: [
      'El fuego bien bajo y la tapa son el secreto: el vapor los cocina por dentro sin quemarlos.',
    ],
    ingredients: [
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Leche', quantity: 30, unit: ML },
      { ingredientName: 'Esencia de vainilla', quantity: 2, unit: ML },
      { ingredientName: 'Harina', quantity: 40, unit: G },
      { ingredientName: 'Polvo de hornear', quantity: 2, unit: G },
      { ingredientName: 'Azúcar', quantity: 30, unit: G },
      {
        ingredientName: 'Manteca',
        quantity: 15,
        unit: G,
        notes: 'para la sartén y para servir',
      },
      { ingredientName: 'Miel', quantity: 30, unit: G, notes: 'para servir' },
      {
        ingredientName: 'Frutillas',
        quantity: 100,
        unit: G,
        notes: 'opcional',
      },
    ],
    en: {
      title: 'Japanese soufflé pancakes',
      description:
        'Super tall, fluffy pancakes like the ones in Your Name and in so many anime café scenes.',
      instructions: [
        'Separate the whites from the yolks. Mix the yolks with the milk, vanilla, flour and baking powder until smooth.',
        'Beat the whites with the sugar to stiff peaks.',
        'Fold the whites into the yolk mixture in 3 additions, gently and without beating.',
        'Heat a nonstick pan on the lowest heat with a little butter. Spoon in 3 tall mounds of batter (use rings if you have them).',
        'Add 1 tablespoon of water to the pan, cover and cook for 5 minutes. Flip carefully, add another tablespoon of water, cover and cook 5 more minutes.',
        'Serve right away with butter, honey or strawberries.',
      ],
      tips: [
        'Very low heat and a lid are the secret: the steam cooks the inside without burning them.',
      ],
      ingredientNotes: [
        null,
        null,
        null,
        null,
        null,
        null,
        'for the pan and for serving',
        'for serving',
        'optional',
      ],
    },
  },
  {
    title: 'Omelette soufflé con arroz',
    description:
      'Una omelette que se abre sobre el arroz y lo cubre como una manta, el truco que hace famoso a un plato de Food Wars!',
    servings: 2,
    prepTimeMinutes: 30,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['anime'],
    estimatedCostTotal: 5000,
    nutrition: {
      calories: 620,
      proteinG: 26,
      fatG: 24,
      carbsG: 74,
      fiberG: 2,
      sugarG: 9,
      sodiumMg: 1000,
    },
    instructions: [
      'Arroz: saltear la cebolla picada y el pollo en cubitos en la manteca. Agregar el arroz cocido y el kétchup y saltear hasta que esté rojizo. Salar y repartir en 2 platos, formando un óvalo.',
      'Batir 3 huevos con la leche y una pizca de sal.',
      'Calentar una sartén con manteca a fuego medio, volcar los huevos y revolver rápido con palillos mientras se mueve la sartén.',
      'Cuando la parte de abajo esté cuajada y la de arriba siga cremosa, enrollar la omelette hacia el borde de la sartén y darle forma de cigarro.',
      'Apoyarla sobre el arroz, hacerle un corte a lo largo con un cuchillo y abrirla para que caiga y cubra el arroz.',
      'Repetir con el resto y terminar con kétchup por encima.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 300, unit: G, notes: 'ya cocido' },
      {
        ingredientName: 'Pollo (pechuga)',
        quantity: 150,
        unit: G,
        notes: 'en cubitos',
      },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN, notes: 'chica' },
      {
        ingredientName: 'Kétchup',
        quantity: 80,
        unit: G,
        notes: 'y un poco más para servir',
      },
      {
        ingredientName: 'Huevo',
        quantity: 6,
        unit: UN,
        notes: '3 por omelette',
      },
      { ingredientName: 'Leche', quantity: 40, unit: ML },
      { ingredientName: 'Manteca', quantity: 30, unit: G },
      { ingredientName: 'Sal', quantity: 3, unit: G },
    ],
    en: {
      title: 'Soufflé omelette over rice',
      description:
        'An omelette that splits open over the rice and covers it like a blanket, the trick that makes a Food Wars! dish famous.',
      instructions: [
        'Rice: sauté the chopped onion and diced chicken in butter. Add the cooked rice and ketchup and stir-fry until reddish. Season and divide between 2 plates, shaping an oval.',
        'Beat 3 eggs with the milk and a pinch of salt.',
        'Heat a pan with butter on medium heat, pour in the eggs and stir quickly with chopsticks while shaking the pan.',
        'When the bottom is set and the top is still creamy, roll the omelette toward the edge of the pan into a cigar shape.',
        'Place it on the rice, slice it lengthwise with a knife and open it so it falls and covers the rice.',
        'Repeat with the rest and top with ketchup.',
      ],
      ingredientNotes: [
        'already cooked',
        'diced',
        'small',
        'plus extra for serving',
        '3 per omelette',
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Rollo de panceta relleno de papas',
    description:
      'Papas en puré envueltas en panceta y horneadas hasta quedar crocantes: un "asado" que parece de carne y es casi todo papa, inspirado en Food Wars!',
    servings: 4,
    prepTimeMinutes: 90,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['anime'],
    estimatedCostTotal: 9000,
    nutrition: {
      calories: 610,
      proteinG: 18,
      fatG: 38,
      carbsG: 50,
      fiberG: 5,
      sugarG: 6,
      sodiumMg: 1200,
    },
    instructions: [
      'Hervir las papas peladas hasta que estén tiernas y hacer un puré con la manteca, sal y pimienta.',
      'Rehogar la cebolla picada y los champiñones hasta que estén dorados y mezclarlos con el puré.',
      'Sobre papel film, colocar las fetas de panceta superpuestas formando un rectángulo.',
      'Poner el puré en el centro formando un cilindro y envolverlo con la panceta usando el film para ayudarte. Enfriar 30 minutos en la heladera.',
      'Quitar el film y hornear en una fuente a 200 °C durante 35 a 40 minutos, hasta que la panceta esté dorada y crocante.',
      'Pintar con la salsa de soja mezclada con la miel en los últimos 5 minutos. Cortar en rodajas y servir.',
    ],
    ingredients: [
      { ingredientName: 'Papa', quantity: 1, unit: KG },
      { ingredientName: 'Manteca', quantity: 40, unit: G },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Champiñones', quantity: 150, unit: G },
      {
        ingredientName: 'Panceta',
        quantity: 300,
        unit: G,
        notes: 'en fetas finas y largas',
      },
      { ingredientName: 'Salsa de soja', quantity: 20, unit: ML },
      { ingredientName: 'Miel', quantity: 20, unit: G },
      { ingredientName: 'Sal', quantity: 5, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 2, unit: G },
    ],
    en: {
      title: 'Potato-stuffed bacon roll',
      description:
        'Mashed potatoes wrapped in bacon and baked until crispy: a "roast" that looks like meat but is mostly potato, inspired by Food Wars!',
      instructions: [
        'Boil the peeled potatoes until tender and mash them with the butter, salt and pepper.',
        'Sauté the chopped onion and mushrooms until golden and mix them into the mash.',
        'On plastic wrap, lay the bacon slices overlapping to form a rectangle.',
        'Shape the mash into a log in the center and wrap it with the bacon, using the plastic wrap to help. Chill for 30 minutes.',
        'Remove the wrap and bake in a dish at 200 °C (400 °F) for 35 to 40 minutes, until the bacon is golden and crisp.',
        'Brush with the soy sauce mixed with honey during the last 5 minutes. Slice and serve.',
      ],
      ingredientNotes: [
        null,
        null,
        null,
        null,
        'long thin slices',
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Curry japonés con arroz',
    description:
      'El curry espeso y suave que comen los personajes de One Piece, Pokémon y casi todos los animes: carne, papa y zanahoria con roux casero.',
    servings: 4,
    prepTimeMinutes: 60,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['anime'],
    estimatedCostTotal: 8500,
    nutrition: {
      calories: 680,
      proteinG: 30,
      fatG: 22,
      carbsG: 90,
      fiberG: 6,
      sugarG: 10,
      sodiumMg: 1100,
    },
    instructions: [
      'Cocinar el arroz.',
      'Dorar el pollo en cubos en una olla con aceite. Agregar la cebolla y cocinar hasta que esté transparente.',
      'Sumar la papa y la zanahoria en cubos, cubrir con el caldo y cocinar 20 minutos.',
      'Roux: derretir la manteca en una sartén, agregar la harina y cocinar 3 minutos revolviendo. Sumar el curry en polvo, el kétchup, la salsa inglesa y la miel, y mezclar.',
      'Disolver el roux en un cucharón de caldo y volcarlo en la olla. Cocinar 10 minutos revolviendo hasta que espese.',
      'Servir el curry junto al arroz.',
    ],
    tips: [
      'La miel y el kétchup le dan el toque dulce típico del curry japonés.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 400, unit: G },
      {
        ingredientName: 'Pollo (muslos)',
        quantity: 500,
        unit: G,
        notes: 'o carne de vaca',
      },
      { ingredientName: 'Aceite', quantity: 15, unit: ML },
      { ingredientName: 'Cebolla', quantity: 2, unit: UN },
      { ingredientName: 'Papa', quantity: 2, unit: UN },
      { ingredientName: 'Zanahoria', quantity: 2, unit: UN },
      { ingredientName: 'Caldo', quantity: 800, unit: ML },
      { ingredientName: 'Manteca', quantity: 50, unit: G },
      { ingredientName: 'Harina', quantity: 50, unit: G },
      { ingredientName: 'Curry en polvo', quantity: 15, unit: G },
      { ingredientName: 'Kétchup', quantity: 30, unit: G },
      { ingredientName: 'Salsa inglesa', quantity: 15, unit: ML },
      { ingredientName: 'Miel', quantity: 15, unit: G },
    ],
    en: {
      title: 'Japanese curry with rice',
      description:
        'The thick, mild curry eaten in One Piece, Pokémon and almost every anime: meat, potato and carrot with a homemade roux.',
      instructions: [
        'Cook the rice.',
        'Brown the cubed chicken in a pot with oil. Add the onion and cook until translucent.',
        'Add the cubed potato and carrot, cover with the stock and cook for 20 minutes.',
        'Roux: melt the butter in a pan, add the flour and cook for 3 minutes while stirring. Add the curry powder, ketchup, Worcestershire sauce and honey, and mix.',
        'Dissolve the roux in a ladle of broth and pour it into the pot. Cook for 10 minutes, stirring, until thick.',
        'Serve the curry next to the rice.',
      ],
      tips: [
        'Honey and ketchup give it the typical sweet touch of Japanese curry.',
      ],
      ingredientNotes: [
        null,
        'or beef',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Omurice',
    description:
      'Arroz salteado con pollo y kétchup envuelto en una omelette fina, el plato casero que se ve en tantos animes de cafetería y de vida cotidiana.',
    servings: 2,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['anime'],
    estimatedCostTotal: 4500,
    nutrition: {
      calories: 590,
      proteinG: 25,
      fatG: 20,
      carbsG: 76,
      fiberG: 3,
      sugarG: 10,
      sodiumMg: 950,
    },
    instructions: [
      'Saltear la cebolla y el pollo picados en la mitad de la manteca hasta que el pollo esté cocido.',
      'Agregar las arvejas, el arroz cocido y el kétchup, y saltear hasta que todo tome color. Salar.',
      'Batir los huevos con la leche. En una sartén con el resto de la manteca, hacer una omelette fina con la mitad de la mezcla.',
      'Poner la mitad del arroz en el centro, doblar los bordes de la omelette hacia el arroz y darla vuelta sobre el plato para que la unión quede abajo.',
      'Repetir con la otra porción y decorar con kétchup (un dibujo o un nombre, como en el anime).',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 300, unit: G, notes: 'ya cocido' },
      { ingredientName: 'Pollo (pechuga)', quantity: 150, unit: G },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN, notes: 'chica' },
      { ingredientName: 'Arvejas', quantity: 60, unit: G },
      { ingredientName: 'Kétchup', quantity: 80, unit: G },
      { ingredientName: 'Huevo', quantity: 4, unit: UN },
      { ingredientName: 'Leche', quantity: 30, unit: ML },
      { ingredientName: 'Manteca', quantity: 30, unit: G },
      { ingredientName: 'Sal', quantity: 3, unit: G },
    ],
    en: {
      title: 'Omurice',
      description:
        'Chicken and ketchup fried rice wrapped in a thin omelette, the homestyle dish seen in so many café and slice-of-life anime.',
      instructions: [
        'Sauté the chopped onion and chicken in half the butter until the chicken is cooked.',
        'Add the peas, cooked rice and ketchup, and stir-fry until everything is colored. Season with salt.',
        'Beat the eggs with the milk. In a pan with the rest of the butter, make a thin omelette with half the mixture.',
        'Put half the rice in the center, fold the edges of the omelette over it and flip it onto the plate so the seam is underneath.',
        'Repeat with the other portion and decorate with ketchup (a drawing or a name, like in anime).',
      ],
      ingredientNotes: [
        'already cooked',
        null,
        'small',
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Takoyaki',
    description:
      'Bolitas de masa rellenas de pulpo, cocinadas en la placa especial y cubiertas con salsa y mayonesa: el clásico de los festivales en el anime.',
    servings: 4,
    prepTimeMinutes: 45,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['anime'],
    estimatedCostTotal: 9000,
    nutrition: {
      calories: 380,
      proteinG: 18,
      fatG: 15,
      carbsG: 42,
      fiberG: 2,
      sugarG: 7,
      sodiumMg: 900,
    },
    instructions: [
      'Mezclar la harina, los huevos, el caldo frío y la salsa de soja hasta lograr una masa bien líquida.',
      'Cortar el pulpo cocido en cubitos y picar la cebolla de verdeo.',
      'Calentar la placa de takoyaki y pintar cada hueco con aceite.',
      'Llenar los huecos con masa hasta el borde, poner un trozo de pulpo en cada uno y espolvorear cebolla de verdeo.',
      'Cuando los bordes estén cocidos, girar cada bolita 90° con un palillo, empujando la masa que sobra hacia adentro. Seguir girando hasta que queden redondas y doradas.',
      'Salsa: mezclar el kétchup con la salsa inglesa y la miel. Servir los takoyaki con la salsa y la mayonesa por encima.',
    ],
    tips: [
      'Sin placa de takoyaki se pueden hacer en una sartén para mini panqueques o como tortitas planas.',
    ],
    ingredients: [
      { ingredientName: 'Harina', quantity: 150, unit: G },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Caldo', quantity: 500, unit: ML, notes: 'frío' },
      { ingredientName: 'Salsa de soja', quantity: 10, unit: ML },
      { ingredientName: 'Pulpo', quantity: 200, unit: G, notes: 'cocido' },
      { ingredientName: 'Cebolla de verdeo', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 30, unit: ML },
      { ingredientName: 'Kétchup', quantity: 40, unit: G },
      { ingredientName: 'Salsa inglesa', quantity: 30, unit: ML },
      { ingredientName: 'Miel', quantity: 10, unit: G },
      { ingredientName: 'Mayonesa', quantity: 40, unit: G },
    ],
    en: {
      title: 'Takoyaki',
      description:
        'Batter balls filled with octopus, cooked in a special pan and topped with sauce and mayonnaise: the classic festival snack in anime.',
      instructions: [
        'Mix the flour, eggs, cold stock and soy sauce into a very runny batter.',
        'Dice the cooked octopus and chop the scallions.',
        'Heat the takoyaki pan and brush each hole with oil.',
        'Fill the holes to the brim with batter, drop a piece of octopus into each and sprinkle with scallions.',
        'When the edges are set, turn each ball 90° with a skewer, tucking the extra batter inside. Keep turning until round and golden.',
        'Sauce: mix the ketchup with the Worcestershire sauce and honey. Serve the takoyaki topped with the sauce and mayonnaise.',
      ],
      tips: [
        'Without a takoyaki pan you can use an aebleskiver pan or make them as small flat fritters.',
      ],
      ingredientNotes: [
        null,
        null,
        'cold',
        null,
        'cooked',
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Yakisoba',
    description:
      'Fideos salteados con cerdo, repollo y zanahoria en salsa agridulce, la comida de los puestos callejeros y los festivales escolares del anime.',
    servings: 3,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['anime', 'economico'],
    estimatedCostTotal: 6000,
    nutrition: {
      calories: 560,
      proteinG: 24,
      fatG: 18,
      carbsG: 74,
      fiberG: 4,
      sugarG: 11,
      sodiumMg: 1300,
    },
    instructions: [
      'Cocinar los fideos 1 minuto menos de lo que indica el paquete, escurrirlos y mezclarlos con un poco de aceite.',
      'Salsa: mezclar la salsa inglesa, el kétchup, la salsa de soja y el azúcar.',
      'Saltear el cerdo en tiras finas en un wok o sartén grande con aceite a fuego fuerte.',
      'Agregar la cebolla, la zanahoria en bastones y el repollo en tiras, y saltear 3 minutos.',
      'Sumar los fideos y la salsa, y saltear todo junto 2 minutos más.',
      'Servir con cebolla de verdeo y sésamo.',
    ],
    ingredients: [
      {
        ingredientName: 'Fideos',
        quantity: 300,
        unit: G,
        notes: 'tipo spaghetti fino o de ramen',
      },
      { ingredientName: 'Aceite', quantity: 30, unit: ML },
      { ingredientName: 'Salsa inglesa', quantity: 40, unit: ML },
      { ingredientName: 'Kétchup', quantity: 30, unit: G },
      { ingredientName: 'Salsa de soja', quantity: 20, unit: ML },
      { ingredientName: 'Azúcar', quantity: 10, unit: G },
      {
        ingredientName: 'Cerdo (magro)',
        quantity: 250,
        unit: G,
        notes: 'en tiras finas',
      },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Zanahoria', quantity: 1, unit: UN },
      { ingredientName: 'Repollo', quantity: 200, unit: G },
      { ingredientName: 'Cebolla de verdeo', quantity: 1, unit: UN },
      { ingredientName: 'Semillas de sésamo', quantity: 5, unit: G },
    ],
    en: {
      title: 'Yakisoba',
      description:
        'Stir-fried noodles with pork, cabbage and carrot in a sweet and tangy sauce, the street-stall and school-festival food of anime.',
      instructions: [
        'Cook the noodles 1 minute less than the package says, drain and toss them with a little oil.',
        'Sauce: mix the Worcestershire sauce, ketchup, soy sauce and sugar.',
        'Stir-fry the thinly sliced pork in a wok or large pan with oil over high heat.',
        'Add the onion, carrot sticks and shredded cabbage, and stir-fry for 3 minutes.',
        'Add the noodles and sauce and stir-fry everything together for 2 more minutes.',
        'Serve with scallions and sesame seeds.',
      ],
      ingredientNotes: [
        'thin spaghetti or ramen noodles',
        null,
        null,
        null,
        null,
        null,
        'thinly sliced',
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Taiyaki',
    description:
      'Bizcochitos con forma de pez rellenos de pasta de porotos dulces o dulce de leche, la merienda callejera más famosa del anime.',
    servings: 8,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['anime', 'vegetariano'],
    estimatedCostTotal: 4500,
    nutrition: {
      calories: 230,
      proteinG: 5,
      fatG: 6,
      carbsG: 38,
      fiberG: 1,
      sugarG: 18,
      sodiumMg: 120,
    },
    instructions: [
      'Mezclar la harina, el polvo de hornear y el azúcar. Aparte, batir el huevo con la leche y la manteca derretida.',
      'Unir ambas mezclas hasta que no queden grumos y dejar reposar 15 minutos.',
      'Calentar el molde de taiyaki a fuego bajo y pintarlo con manteca.',
      'Llenar una de las mitades con masa hasta la mitad, poner 1 cucharada de relleno y cubrir con más masa.',
      'Cerrar el molde y cocinar 3 minutos de cada lado, hasta que estén dorados.',
      'Desmoldar y comer tibios.',
    ],
    tips: [
      'Sin molde de pez, se pueden hacer en una waflera o como panqueques gruesos rellenos.',
    ],
    ingredients: [
      { ingredientName: 'Harina', quantity: 200, unit: G },
      { ingredientName: 'Polvo de hornear', quantity: 8, unit: G },
      { ingredientName: 'Azúcar', quantity: 40, unit: G },
      { ingredientName: 'Huevo', quantity: 1, unit: UN },
      { ingredientName: 'Leche', quantity: 200, unit: ML },
      {
        ingredientName: 'Manteca',
        quantity: 30,
        unit: G,
        notes: 'derretida, y un poco para el molde',
      },
      {
        ingredientName: 'Dulce de leche',
        quantity: 200,
        unit: G,
        notes: 'o pasta de porotos dulces',
      },
    ],
    en: {
      title: 'Taiyaki',
      description:
        'Fish-shaped cakes filled with sweet bean paste or dulce de leche, the most famous street snack in anime.',
      instructions: [
        'Mix the flour, baking powder and sugar. Separately, whisk the egg with the milk and melted butter.',
        'Combine both mixtures until smooth and let the batter rest for 15 minutes.',
        'Heat the taiyaki mold on low heat and brush it with butter.',
        'Fill one half halfway with batter, add 1 tablespoon of filling and cover with more batter.',
        'Close the mold and cook for 3 minutes per side, until golden.',
        'Unmold and eat warm.',
      ],
      tips: [
        'Without a fish mold, you can use a waffle iron or make thick filled pancakes.',
      ],
      ingredientNotes: [
        null,
        null,
        null,
        null,
        null,
        'melted, plus extra for the mold',
        'or sweet bean paste',
      ],
    },
  },
  {
    title: 'Melon pan',
    description:
      'Pan dulce esponjoso con una costra crocante de galletita marcada en rombos, la merienda escolar que aparece en un montón de animes.',
    servings: 8,
    prepTimeMinutes: 150,
    difficulty: RecipeDifficulty.HARD,
    dietTags: ['anime', 'vegetariano'],
    estimatedCostTotal: 4000,
    nutrition: {
      calories: 310,
      proteinG: 7,
      fatG: 10,
      carbsG: 48,
      fiberG: 1,
      sugarG: 16,
      sodiumMg: 200,
    },
    instructions: [
      'Masa de pan: mezclar 250 g de harina, 30 g de azúcar, la levadura y la sal. Agregar la leche tibia y 1 huevo, y amasar 10 minutos. Sumar 25 g de manteca y amasar hasta que quede lisa.',
      'Dejar levar tapada en un lugar tibio 1 hora, hasta que duplique su tamaño.',
      'Costra: batir 50 g de manteca blanda con el resto del azúcar, sumar el otro huevo y la vainilla, e incorporar el resto de la harina. Enfriar 30 minutos.',
      'Dividir la masa de pan en 8 bollos. Dividir la costra en 8, aplanar cada parte entre dos papeles y cubrir cada bollo.',
      'Pasar la parte de arriba por azúcar y marcar un enrejado con el lomo de un cuchillo. Dejar levar 30 minutos más.',
      'Hornear a 180 °C durante 13 a 15 minutos, hasta que estén apenas dorados.',
    ],
    ingredients: [
      {
        ingredientName: 'Harina',
        quantity: 400,
        unit: G,
        notes: '250 g para el pan y 150 g para la costra',
      },
      {
        ingredientName: 'Azúcar',
        quantity: 110,
        unit: G,
        notes:
          '30 g para el pan, 60 g para la costra y el resto para espolvorear',
      },
      { ingredientName: 'Levadura', quantity: 5, unit: G, notes: 'seca' },
      { ingredientName: 'Sal', quantity: 3, unit: G },
      { ingredientName: 'Leche', quantity: 140, unit: ML, notes: 'tibia' },
      {
        ingredientName: 'Huevo',
        quantity: 2,
        unit: UN,
        notes: '1 para el pan y 1 para la costra',
      },
      {
        ingredientName: 'Manteca',
        quantity: 75,
        unit: G,
        notes: '25 g para el pan y 50 g para la costra',
      },
      { ingredientName: 'Esencia de vainilla', quantity: 3, unit: ML },
    ],
    en: {
      title: 'Melon pan',
      description:
        'A fluffy sweet bun with a crunchy cookie crust scored in diamonds, the school snack that shows up in so many anime.',
      instructions: [
        'Bread dough: mix 250 g of flour, 30 g of sugar, the yeast and salt. Add the warm milk and 1 egg and knead for 10 minutes. Add 25 g of butter and knead until smooth.',
        'Let it rise covered in a warm place for 1 hour, until doubled.',
        'Crust: beat 50 g of soft butter with the remaining sugar, add the other egg and the vanilla, and mix in the rest of the flour. Chill for 30 minutes.',
        'Divide the bread dough into 8 buns. Divide the crust into 8, flatten each piece between two sheets of paper and cover each bun.',
        'Dip the tops in sugar and score a crosshatch with the back of a knife. Let rise 30 more minutes.',
        'Bake at 180 °C (350 °F) for 13 to 15 minutes, until lightly golden.',
      ],
      ingredientNotes: [
        '250 g for the bread and 150 g for the crust',
        '30 g for the bread, 60 g for the crust and the rest for dusting',
        'dry',
        null,
        'warm',
        '1 for the bread and 1 for the crust',
        '25 g for the bread and 50 g for the crust',
        null,
      ],
    },
  },
  {
    title: 'Okonomiyaki',
    description:
      'La "pizza" japonesa de repollo y panceta cocinada a la plancha, protagonista de muchas escenas de comida compartida en el anime.',
    servings: 2,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['anime'],
    estimatedCostTotal: 5000,
    nutrition: {
      calories: 590,
      proteinG: 22,
      fatG: 34,
      carbsG: 48,
      fiberG: 5,
      sugarG: 10,
      sodiumMg: 1100,
    },
    instructions: [
      'Mezclar la harina con el caldo y los huevos hasta lograr una masa lisa.',
      'Agregar el repollo cortado muy fino y la cebolla de verdeo, y mezclar bien.',
      'Calentar una sartén con aceite a fuego medio y volcar la mitad de la mezcla formando un círculo de 2 cm de alto.',
      'Cubrir con fetas de panceta y cocinar 5 minutos. Dar vuelta con ayuda de un plato y cocinar 5 minutos más con la panceta abajo.',
      'Volver a dar vuelta y cocinar 2 minutos. Repetir con el resto.',
      'Salsa: mezclar la salsa inglesa, el kétchup y la miel. Servir con la salsa, la mayonesa en hilos y el alga nori desmenuzada.',
    ],
    ingredients: [
      { ingredientName: 'Harina', quantity: 100, unit: G },
      { ingredientName: 'Caldo', quantity: 120, unit: ML },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      {
        ingredientName: 'Repollo',
        quantity: 300,
        unit: G,
        notes: 'cortado muy fino',
      },
      { ingredientName: 'Cebolla de verdeo', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 20, unit: ML },
      {
        ingredientName: 'Panceta',
        quantity: 120,
        unit: G,
        notes: 'en fetas finas',
      },
      { ingredientName: 'Salsa inglesa', quantity: 30, unit: ML },
      { ingredientName: 'Kétchup', quantity: 30, unit: G },
      { ingredientName: 'Miel', quantity: 10, unit: G },
      { ingredientName: 'Mayonesa', quantity: 30, unit: G },
      {
        ingredientName: 'Alga nori',
        quantity: 1,
        unit: UN,
        notes: 'hoja desmenuzada',
      },
    ],
    en: {
      title: 'Okonomiyaki',
      description:
        'Japan\'s cabbage and bacon griddle "pizza", the star of many shared-meal scenes in anime.',
      instructions: [
        'Mix the flour with the stock and eggs into a smooth batter.',
        'Add the very finely shredded cabbage and the scallions and mix well.',
        'Heat a pan with oil on medium heat and pour in half the mixture, shaping a 2 cm (3/4 in) high circle.',
        'Cover with bacon slices and cook for 5 minutes. Flip with the help of a plate and cook 5 more minutes with the bacon side down.',
        'Flip again and cook for 2 minutes. Repeat with the rest.',
        'Sauce: mix the Worcestershire sauce, ketchup and honey. Serve with the sauce, drizzled mayonnaise and crumbled nori.',
      ],
      ingredientNotes: [
        null,
        null,
        null,
        'very finely shredded',
        null,
        null,
        'thin slices',
        null,
        null,
        null,
        null,
        'sheet, crumbled',
      ],
    },
  },
];
