import { IngredientUnit, RecipeDifficulty } from '../../common/enums';
import type { SeedRecipe } from './recipes.seed';

/**
 * Recetas "Cerebro sano" (patrón de la dieta MIND: hojas verdes, otras
 * verduras, frutos rojos, frutos secos, legumbres, granos integrales, pescado,
 * pollo y aceite de oliva; poca carne roja, manteca, queso, dulces y frituras)
 * y "Texturas suaves" (blandas, húmedas y con poca sal, pensadas para quien
 * tiene dificultad para masticar o tragar, por ejemplo después de un ACV).
 *
 * Son recetas propias. No tratan ni curan ninguna enfermedad: cada una lo
 * aclara. Las que llevan muchas hojas verdes avisan sobre anticoagulantes
 * (vitamina K) y las de textura suave, que la textura la indica el fonoaudiólogo.
 */
const G = IngredientUnit.GRAMS;
const ML = IngredientUnit.MILLILITERS;
const UN = IngredientUnit.UNIT;

const AVISO =
  'Receta orientativa: no reemplaza la indicación de tu médico o nutricionista.';
const NOTICE =
  'This recipe is general guidance and does not replace advice from your doctor or dietitian.';
const VITAMINA_K =
  'Si tomás anticoagulantes (warfarina, acenocumarol), las hojas verdes tienen vitamina K: no las dejes, pero comelas en cantidades parecidas cada semana y consultá a tu médico.';
const VITAMIN_K =
  'If you take blood thinners (warfarin, acenocoumarol), leafy greens contain vitamin K: do not cut them out, but keep the amount similar every week and ask your doctor.';
const TEXTURA =
  'Si hay dificultad para tragar, la textura y si los líquidos deben espesarse los indica el fonoaudiólogo. Comer sentado, despacio y en bocados chicos.';
const TEXTURE =
  'If swallowing is difficult, the right texture and whether liquids must be thickened are decided by a speech therapist. Eat sitting up, slowly and in small bites.';

export const brainRecipes: SeedRecipe[] = [
  // ─── Cerebro sano (MIND) ───────────────────────────────────────────────
  {
    title: 'Salmón al horno con espinaca y batata',
    description:
      'Pescado graso (omega-3), hojas verdes y batata asada: un plato completo con los grupos que más destaca la dieta MIND para cuidar el cerebro.',
    servings: 2,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'proteico', 'sin_tacc'],
    estimatedCostTotal: 9000,
    nutrition: {
      calories: 520,
      proteinG: 34,
      fatG: 24,
      carbsG: 40,
      fiberG: 7,
      sugarG: 9,
      sodiumMg: 260,
    },
    instructions: [
      'Precalentar el horno a 200 °C. Cortar la batata en cubos, mezclarla con la mitad del aceite y hornearla 15 minutos.',
      'Agregar el salmón a la fuente, rociarlo con el resto del aceite, el jugo de limón, el ajo picado y pimienta.',
      'Hornear 12 a 15 minutos más, hasta que el salmón se separe en láminas.',
      'Mientras, saltear la espinaca 2 minutos en una sartén, solo hasta que se ablande.',
      'Servir el salmón con la batata y la espinaca, y terminar con perejil.',
    ],
    tips: [VITAMINA_K, AVISO],
    ingredients: [
      { ingredientName: 'Salmón', quantity: 300, unit: G, notes: '2 filetes' },
      { ingredientName: 'Batata', quantity: 1, unit: UN, notes: 'grande' },
      {
        ingredientName: 'Aceite',
        quantity: 20,
        unit: ML,
        notes: 'de oliva, dividido',
      },
      { ingredientName: 'Limón', quantity: 1, unit: UN, notes: 'el jugo' },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'diente' },
      { ingredientName: 'Espinaca', quantity: 200, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
      { ingredientName: 'Perejil', quantity: 5, unit: G },
    ],
    en: {
      title: 'Baked salmon with spinach and sweet potato',
      description:
        'Oily fish (omega-3), leafy greens and roasted sweet potato: a complete plate with the food groups the MIND diet highlights for brain health.',
      instructions: [
        'Preheat the oven to 200 °C (400 °F). Cube the sweet potato, toss it with half the oil and roast for 15 minutes.',
        'Add the salmon to the dish and drizzle with the rest of the oil, the lemon juice, chopped garlic and pepper.',
        'Bake 12 to 15 more minutes, until the salmon flakes.',
        'Meanwhile, sauté the spinach for 2 minutes in a pan, just until wilted.',
        'Serve the salmon with the sweet potato and spinach, and finish with parsley.',
      ],
      tips: [VITAMIN_K, NOTICE],
      ingredientNotes: [
        '2 fillets',
        'large',
        'olive oil, divided',
        'juiced',
        'clove',
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Ensalada de hojas verdes con frutillas y nueces',
    description:
      'Hojas verdes, frutos rojos y frutos secos en un mismo plato, tres de los grupos estrella de la dieta MIND, con un aderezo de aceite de oliva y limón.',
    servings: 2,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'vegetariano', 'vegano', 'sin_tacc'],
    estimatedCostTotal: 5000,
    nutrition: {
      calories: 290,
      proteinG: 6,
      fatG: 24,
      carbsG: 16,
      fiberG: 6,
      sugarG: 8,
      sodiumMg: 60,
    },
    instructions: [
      'Lavar y secar bien la rúcula y la espinaca.',
      'Cortar las frutillas en cuartos y picar grueso las nueces.',
      'Aderezo: batir el aceite con el jugo de limón, la miel y pimienta.',
      'Mezclar las hojas con las frutillas, las nueces y la palta en cubos, y aderezar justo antes de servir.',
    ],
    tips: [VITAMINA_K, AVISO],
    ingredients: [
      { ingredientName: 'Rúcula', quantity: 80, unit: G },
      {
        ingredientName: 'Espinaca',
        quantity: 80,
        unit: G,
        notes: 'baby o tierna',
      },
      { ingredientName: 'Frutillas', quantity: 150, unit: G },
      { ingredientName: 'Nueces', quantity: 40, unit: G },
      { ingredientName: 'Palta', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 20, unit: ML, notes: 'de oliva' },
      {
        ingredientName: 'Limón',
        quantity: 1,
        unit: UN,
        notes: 'medio, el jugo',
      },
      { ingredientName: 'Miel', quantity: 5, unit: G, notes: 'opcional' },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
    ],
    en: {
      title: 'Leafy green salad with strawberries and walnuts',
      description:
        'Leafy greens, berries and nuts on one plate, three of the star food groups of the MIND diet, with an olive oil and lemon dressing.',
      instructions: [
        'Wash and dry the arugula and spinach well.',
        'Quarter the strawberries and roughly chop the walnuts.',
        'Dressing: whisk the oil with the lemon juice, honey and pepper.',
        'Toss the greens with the strawberries, walnuts and cubed avocado, and dress just before serving.',
      ],
      tips: [VITAMIN_K, NOTICE],
      ingredientNotes: [
        null,
        'baby or tender',
        null,
        null,
        null,
        'olive oil',
        'half, juiced',
        'optional',
        null,
      ],
    },
  },
  {
    title: 'Avena con arándanos y nueces',
    description:
      'Desayuno de grano integral con frutos rojos y frutos secos, sin azúcar agregada: fácil de comer y con mucha fibra.',
    servings: 1,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'vegetariano', 'economico'],
    estimatedCostTotal: 1500,
    nutrition: {
      calories: 380,
      proteinG: 12,
      fatG: 15,
      carbsG: 50,
      fiberG: 8,
      sugarG: 14,
      sodiumMg: 70,
    },
    instructions: [
      'Calentar la leche en una ollita y agregar la avena.',
      'Cocinar 5 minutos a fuego bajo revolviendo, hasta que espese.',
      'Servir con los arándanos, las nueces picadas y la canela por encima.',
    ],
    tips: [
      'Con avena instantánea y la leche más caliente queda más blanda, si cuesta masticar.',
      AVISO,
    ],
    ingredients: [
      { ingredientName: 'Avena', quantity: 50, unit: G },
      {
        ingredientName: 'Leche',
        quantity: 250,
        unit: ML,
        notes: 'o bebida vegetal',
      },
      {
        ingredientName: 'Arándanos',
        quantity: 60,
        unit: G,
        notes: 'frescos o congelados',
      },
      { ingredientName: 'Nueces', quantity: 15, unit: G },
      { ingredientName: 'Canela', quantity: 1, unit: G },
    ],
    en: {
      title: 'Oatmeal with blueberries and walnuts',
      description:
        'A whole-grain breakfast with berries and nuts and no added sugar: easy to eat and high in fiber.',
      instructions: [
        'Heat the milk in a small pot and add the oats.',
        'Cook for 5 minutes on low heat, stirring, until thick.',
        'Top with the blueberries, chopped walnuts and cinnamon.',
      ],
      tips: [
        'With instant oats and hotter milk it turns out softer, if chewing is hard.',
        NOTICE,
      ],
      ingredientNotes: [
        null,
        'or plant-based milk',
        'fresh or frozen',
        null,
        null,
      ],
    },
  },
  {
    title: 'Lentejas guisadas con verduras',
    description:
      'Guiso de legumbres y verduras sin carne roja ni embutidos, con poca sal y mucho sabor por las especias.',
    servings: 4,
    prepTimeMinutes: 50,
    difficulty: RecipeDifficulty.EASY,
    dietTags: [
      'cerebro_sano',
      'vegetariano',
      'vegano',
      'economico',
      'sin_tacc',
    ],
    estimatedCostTotal: 4500,
    nutrition: {
      calories: 340,
      proteinG: 18,
      fatG: 7,
      carbsG: 52,
      fiberG: 14,
      sugarG: 7,
      sodiumMg: 300,
    },
    instructions: [
      'Rehogar la cebolla, el ajo, la zanahoria y el morrón picados en el aceite durante 8 minutos.',
      'Agregar el comino, la cúrcuma y el laurel, y cocinar 1 minuto.',
      'Sumar las lentejas lavadas, el tomate picado y el caldo. Cocinar a fuego bajo 30 minutos, hasta que estén tiernas.',
      'Agregar la acelga picada en los últimos 5 minutos.',
      'Probar y ajustar con pimienta y, si hace falta, muy poca sal.',
    ],
    tips: [
      'Usá caldo casero o caldo bajo en sodio: los cubitos comunes tienen mucha sal.',
      VITAMINA_K,
      AVISO,
    ],
    ingredients: [
      { ingredientName: 'Lentejas', quantity: 300, unit: G },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'dientes' },
      { ingredientName: 'Zanahoria', quantity: 2, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 20, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Comino', quantity: 2, unit: G },
      { ingredientName: 'Cúrcuma', quantity: 2, unit: G },
      { ingredientName: 'Laurel', quantity: 1, unit: UN, notes: 'hoja' },
      { ingredientName: 'Tomate', quantity: 2, unit: UN },
      {
        ingredientName: 'Caldo',
        quantity: 1,
        unit: IngredientUnit.LITERS,
        notes: 'casero o bajo en sodio',
      },
      { ingredientName: 'Acelga', quantity: 150, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
    ],
    en: {
      title: 'Lentil and vegetable stew',
      description:
        'A bean and vegetable stew with no red meat or cured sausage, low in salt and full of flavor from spices.',
      instructions: [
        'Cook the chopped onion, garlic, carrot and bell pepper in the oil for 8 minutes.',
        'Add the cumin, turmeric and bay leaf and cook for 1 minute.',
        'Add the rinsed lentils, chopped tomato and stock. Simmer on low heat for 30 minutes, until tender.',
        'Add the chopped chard during the last 5 minutes.',
        'Taste and adjust with pepper and, if needed, very little salt.',
      ],
      tips: [
        'Use homemade or low-sodium stock: regular bouillon cubes are very salty.',
        VITAMIN_K,
        NOTICE,
      ],
      ingredientNotes: [
        null,
        null,
        'cloves',
        null,
        null,
        'olive oil',
        null,
        null,
        'leaf',
        null,
        'homemade or low-sodium',
        null,
        null,
      ],
    },
  },
  {
    title: 'Pollo al limón con brócoli y arroz integral',
    description:
      'Pollo (la carne recomendada en la dieta MIND en lugar de la roja), brócoli y arroz integral, con limón y ajo en vez de sal.',
    servings: 2,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'proteico', 'sin_tacc'],
    estimatedCostTotal: 6500,
    nutrition: {
      calories: 510,
      proteinG: 40,
      fatG: 14,
      carbsG: 54,
      fiberG: 7,
      sugarG: 3,
      sodiumMg: 180,
    },
    instructions: [
      'Cocinar el arroz integral en agua según el paquete (unos 35 minutos).',
      'Cortar el pollo en tiras y marinarlo 10 minutos con el jugo de limón, el ajo picado, el orégano y pimienta.',
      'Dorar el pollo en una sartén con el aceite, 6 a 8 minutos.',
      'Cocinar el brócoli al vapor 5 minutos, que quede verde.',
      'Servir el arroz con el pollo y el brócoli, y la ralladura de limón por encima.',
    ],
    tips: [VITAMINA_K, AVISO],
    ingredients: [
      { ingredientName: 'Arroz integral', quantity: 150, unit: G },
      { ingredientName: 'Pollo (pechuga)', quantity: 300, unit: G },
      {
        ingredientName: 'Limón',
        quantity: 1,
        unit: UN,
        notes: 'jugo y ralladura',
      },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'dientes' },
      { ingredientName: 'Orégano', quantity: 2, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
      { ingredientName: 'Aceite', quantity: 15, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Brócoli', quantity: 300, unit: G },
    ],
    en: {
      title: 'Lemon chicken with broccoli and brown rice',
      description:
        'Chicken (the meat the MIND diet favors over red meat), broccoli and brown rice, with lemon and garlic instead of salt.',
      instructions: [
        'Cook the brown rice in water according to the package (about 35 minutes).',
        'Slice the chicken into strips and marinate it for 10 minutes with the lemon juice, chopped garlic, oregano and pepper.',
        'Brown the chicken in a pan with the oil, 6 to 8 minutes.',
        'Steam the broccoli for 5 minutes, keeping it green.',
        'Serve the rice with the chicken and broccoli, and the lemon zest on top.',
      ],
      tips: [VITAMIN_K, NOTICE],
      ingredientNotes: [
        null,
        null,
        'juice and zest',
        'cloves',
        null,
        null,
        'olive oil',
        null,
      ],
    },
  },
  {
    title: 'Tostadas de pan integral con sardinas y tomate',
    description:
      'Pescado graso de lata (barato y con omega-3) sobre pan integral con tomate: un almuerzo rápido para sumar pescado a la semana.',
    servings: 2,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'proteico', 'economico'],
    estimatedCostTotal: 3500,
    nutrition: {
      calories: 380,
      proteinG: 24,
      fatG: 17,
      carbsG: 32,
      fiberG: 6,
      sugarG: 4,
      sodiumMg: 520,
    },
    instructions: [
      'Tostar el pan.',
      'Frotar cada tostada con medio diente de ajo y cubrir con tomate en rodajas finas.',
      'Escurrir las sardinas, acomodarlas encima y aplastarlas un poco con un tenedor.',
      'Terminar con unas gotas de aceite, limón, pimienta y perejil.',
    ],
    tips: [
      'Elegí sardinas al natural o en aceite de oliva y escurrilas: así tienen menos sal.',
      AVISO,
    ],
    ingredients: [
      {
        ingredientName: 'Pan',
        quantity: 4,
        unit: UN,
        notes: 'rodajas de pan integral',
      },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'diente' },
      { ingredientName: 'Tomate', quantity: 2, unit: UN },
      { ingredientName: 'Sardinas', quantity: 125, unit: G, notes: '1 lata' },
      { ingredientName: 'Aceite', quantity: 5, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Limón', quantity: 1, unit: UN, notes: 'unas gotas' },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
      { ingredientName: 'Perejil', quantity: 5, unit: G },
    ],
    en: {
      title: 'Whole-grain toast with sardines and tomato',
      description:
        'Canned oily fish (cheap and rich in omega-3) on whole-grain bread with tomato: a quick lunch to add fish to your week.',
      instructions: [
        'Toast the bread.',
        'Rub each slice with half a garlic clove and cover with thin tomato slices.',
        'Drain the sardines, lay them on top and lightly mash them with a fork.',
        'Finish with a few drops of oil, lemon, pepper and parsley.',
      ],
      tips: [
        'Choose sardines in water or olive oil and drain them: they will have less salt.',
        NOTICE,
      ],
      ingredientNotes: [
        'slices of whole-grain bread',
        'clove',
        null,
        '1 can',
        'olive oil',
        'a few drops',
        null,
        null,
      ],
    },
  },
  {
    title: 'Sopa de verduras y porotos',
    description:
      'Sopa espesa de legumbres y verduras de estación, con hojas verdes al final. Rinde para varios días y se puede congelar.',
    servings: 6,
    prepTimeMinutes: 60,
    difficulty: RecipeDifficulty.EASY,
    dietTags: [
      'cerebro_sano',
      'vegetariano',
      'vegano',
      'economico',
      'sin_tacc',
    ],
    estimatedCostTotal: 5500,
    nutrition: {
      calories: 260,
      proteinG: 12,
      fatG: 5,
      carbsG: 40,
      fiberG: 11,
      sugarG: 7,
      sodiumMg: 280,
    },
    instructions: [
      'Rehogar la cebolla, el ajo, el apio y la zanahoria picados en el aceite durante 8 minutos.',
      'Agregar el zapallito y la papa en cubos, el tomate picado y el caldo. Cocinar 20 minutos.',
      'Sumar los porotos cocidos y el kale picado, y cocinar 10 minutos más.',
      'Condimentar con pimienta, orégano y, si hace falta, muy poca sal.',
    ],
    tips: [
      'Si los porotos son de lata, enjuagalos bien para sacarles sal.',
      VITAMINA_K,
      AVISO,
    ],
    ingredients: [
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'dientes' },
      { ingredientName: 'Apio', quantity: 2, unit: UN, notes: 'ramas' },
      { ingredientName: 'Zanahoria', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 20, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Zapallito', quantity: 2, unit: UN },
      { ingredientName: 'Papa', quantity: 1, unit: UN },
      { ingredientName: 'Tomate', quantity: 2, unit: UN },
      {
        ingredientName: 'Caldo',
        quantity: 1.5,
        unit: IngredientUnit.LITERS,
        notes: 'casero o bajo en sodio',
      },
      {
        ingredientName: 'Porotos negros',
        quantity: 400,
        unit: G,
        notes: 'cocidos',
      },
      { ingredientName: 'Kale', quantity: 100, unit: G, notes: 'o espinaca' },
      { ingredientName: 'Orégano', quantity: 2, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
    ],
    en: {
      title: 'Vegetable and bean soup',
      description:
        'A thick soup of beans and seasonal vegetables with leafy greens at the end. It lasts several days and freezes well.',
      instructions: [
        'Cook the chopped onion, garlic, celery and carrot in the oil for 8 minutes.',
        'Add the cubed zucchini and potato, the chopped tomato and the stock. Cook for 20 minutes.',
        'Add the cooked beans and chopped kale and cook 10 more minutes.',
        'Season with pepper, oregano and, if needed, very little salt.',
      ],
      tips: [
        'If the beans are canned, rinse them well to remove salt.',
        VITAMIN_K,
        NOTICE,
      ],
      ingredientNotes: [
        null,
        'cloves',
        'stalks',
        null,
        'olive oil',
        null,
        null,
        null,
        'homemade or low-sodium',
        'cooked',
        'or spinach',
        null,
        null,
      ],
    },
  },
  {
    title: 'Merluza a la provenzal con ensalada de hojas',
    description:
      'Pescado blanco al horno con ajo y perejil, acompañado de hojas verdes: liviano, barato y fácil de masticar.',
    servings: 2,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'proteico', 'sin_tacc'],
    estimatedCostTotal: 6000,
    nutrition: {
      calories: 330,
      proteinG: 34,
      fatG: 16,
      carbsG: 9,
      fiberG: 3,
      sugarG: 3,
      sodiumMg: 220,
    },
    instructions: [
      'Precalentar el horno a 200 °C y aceitar una fuente.',
      'Acomodar los filetes de merluza y cubrirlos con el ajo y el perejil picados mezclados con la mitad del aceite.',
      'Hornear 12 a 15 minutos, hasta que el pescado esté blanco y se separe con un tenedor.',
      'Servir con la lechuga y la rúcula aderezadas con el resto del aceite y limón.',
    ],
    tips: [VITAMINA_K, AVISO],
    ingredients: [
      {
        ingredientName: 'Merluza',
        quantity: 350,
        unit: G,
        notes: 'filetes sin espinas',
      },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'dientes' },
      { ingredientName: 'Perejil', quantity: 15, unit: G },
      {
        ingredientName: 'Aceite',
        quantity: 25,
        unit: ML,
        notes: 'de oliva, dividido',
      },
      { ingredientName: 'Lechuga', quantity: 100, unit: G },
      { ingredientName: 'Rúcula', quantity: 50, unit: G },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
    ],
    en: {
      title: 'Garlic and parsley baked hake with green salad',
      description:
        'Oven-baked white fish with garlic and parsley, served with leafy greens: light, affordable and easy to chew.',
      instructions: [
        'Preheat the oven to 200 °C (400 °F) and oil a baking dish.',
        'Lay the hake fillets in it and cover with the chopped garlic and parsley mixed with half the oil.',
        'Bake 12 to 15 minutes, until the fish is white and flakes with a fork.',
        'Serve with the lettuce and arugula dressed with the rest of the oil and lemon.',
      ],
      tips: [VITAMIN_K, NOTICE],
      ingredientNotes: [
        'boneless fillets',
        'cloves',
        null,
        'olive oil, divided',
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Garbanzos salteados con espinaca y huevo',
    description:
      'Legumbres, hojas verdes y huevo en una sartén: una cena rápida, económica y con proteína sin carne roja.',
    servings: 2,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'vegetariano', 'economico', 'sin_tacc'],
    estimatedCostTotal: 3000,
    nutrition: {
      calories: 400,
      proteinG: 22,
      fatG: 18,
      carbsG: 38,
      fiberG: 11,
      sugarG: 6,
      sodiumMg: 250,
    },
    instructions: [
      'Saltear la cebolla y el ajo picados en el aceite hasta que estén transparentes.',
      'Agregar los garbanzos cocidos, el comino y la cúrcuma, y saltear 3 minutos.',
      'Sumar la espinaca y revolver hasta que se ablande.',
      'Hacer dos huecos, cascar los huevos, tapar y cocinar 4 minutos, hasta que la clara esté cocida.',
    ],
    tips: [VITAMINA_K, AVISO],
    ingredients: [
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'diente' },
      { ingredientName: 'Aceite', quantity: 15, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Garbanzos', quantity: 250, unit: G, notes: 'cocidos' },
      { ingredientName: 'Comino', quantity: 1, unit: G },
      { ingredientName: 'Cúrcuma', quantity: 1, unit: G },
      { ingredientName: 'Espinaca', quantity: 200, unit: G },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
    ],
    en: {
      title: 'Sautéed chickpeas with spinach and egg',
      description:
        'Legumes, leafy greens and egg in one pan: a quick, cheap dinner with protein and no red meat.',
      instructions: [
        'Sauté the chopped onion and garlic in the oil until translucent.',
        'Add the cooked chickpeas, cumin and turmeric and sauté for 3 minutes.',
        'Add the spinach and stir until wilted.',
        'Make two wells, crack in the eggs, cover and cook for 4 minutes, until the whites are set.',
      ],
      tips: [VITAMIN_K, NOTICE],
      ingredientNotes: [
        null,
        'clove',
        'olive oil',
        'cooked',
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Yogur con frutos rojos, chía y almendras',
    description:
      'Merienda o postre con frutos rojos y frutos secos en lugar de facturas o galletitas.',
    servings: 1,
    prepTimeMinutes: 5,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'vegetariano', 'sin_tacc'],
    estimatedCostTotal: 2500,
    nutrition: {
      calories: 300,
      proteinG: 15,
      fatG: 15,
      carbsG: 26,
      fiberG: 7,
      sugarG: 17,
      sodiumMg: 80,
    },
    instructions: [
      'Poner el yogur en un bowl.',
      'Agregar las frutillas y los arándanos.',
      'Terminar con las almendras picadas y las semillas de chía.',
    ],
    tips: ['Usá yogur natural sin azúcar y endulzá solo con la fruta.', AVISO],
    ingredients: [
      {
        ingredientName: 'Yogur griego',
        quantity: 170,
        unit: G,
        notes: 'natural, sin azúcar',
      },
      { ingredientName: 'Frutillas', quantity: 60, unit: G },
      { ingredientName: 'Arándanos', quantity: 40, unit: G },
      { ingredientName: 'Almendras', quantity: 15, unit: G },
      { ingredientName: 'Semillas de chía', quantity: 8, unit: G },
    ],
    en: {
      title: 'Yogurt with berries, chia and almonds',
      description:
        'An afternoon snack or dessert with berries and nuts instead of pastries or cookies.',
      instructions: [
        'Spoon the yogurt into a bowl.',
        'Add the strawberries and blueberries.',
        'Top with the chopped almonds and chia seeds.',
      ],
      tips: [
        'Use plain unsweetened yogurt and sweeten only with the fruit.',
        NOTICE,
      ],
      ingredientNotes: ['plain, unsweetened', null, null, null, null],
    },
  },
  {
    title: 'Quinoa con verduras asadas y garbanzos',
    description:
      'Bowl de grano integral, verduras asadas al horno y legumbres, con un aderezo de yogur y limón.',
    servings: 2,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'vegetariano', 'sin_tacc'],
    estimatedCostTotal: 6000,
    nutrition: {
      calories: 480,
      proteinG: 18,
      fatG: 16,
      carbsG: 66,
      fiberG: 12,
      sugarG: 10,
      sodiumMg: 200,
    },
    instructions: [
      'Lavar la quinoa y cocinarla en el doble de agua 15 minutos. Dejar reposar tapada.',
      'Cortar la berenjena, el morrón, el zapallito y la cebolla en trozos, mezclarlos con el aceite y el orégano y hornearlos a 200 °C durante 25 minutos.',
      'Agregar los garbanzos a la fuente en los últimos 10 minutos.',
      'Aderezo: mezclar el yogur con el jugo de limón y el ajo rallado.',
      'Servir la quinoa con las verduras y los garbanzos, y el aderezo por encima.',
    ],
    tips: [AVISO],
    ingredients: [
      { ingredientName: 'Quinoa', quantity: 150, unit: G },
      { ingredientName: 'Berenjena', quantity: 1, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN },
      { ingredientName: 'Zapallito', quantity: 1, unit: UN },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 25, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Orégano', quantity: 2, unit: G },
      { ingredientName: 'Garbanzos', quantity: 200, unit: G, notes: 'cocidos' },
      { ingredientName: 'Yogur', quantity: 100, unit: G, notes: 'natural' },
      {
        ingredientName: 'Limón',
        quantity: 1,
        unit: UN,
        notes: 'medio, el jugo',
      },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'diente' },
    ],
    en: {
      title: 'Quinoa with roasted vegetables and chickpeas',
      description:
        'A bowl of whole grains, oven-roasted vegetables and legumes, with a yogurt and lemon dressing.',
      instructions: [
        'Rinse the quinoa and cook it in twice its volume of water for 15 minutes. Let it rest covered.',
        'Cut the eggplant, bell pepper, zucchini and onion into chunks, toss with the oil and oregano and roast at 200 °C (400 °F) for 25 minutes.',
        'Add the chickpeas to the tray for the last 10 minutes.',
        'Dressing: mix the yogurt with the lemon juice and grated garlic.',
        'Serve the quinoa with the vegetables and chickpeas, and the dressing on top.',
      ],
      tips: [NOTICE],
      ingredientNotes: [
        null,
        null,
        null,
        null,
        null,
        'olive oil',
        null,
        'cooked',
        'plain',
        'half, juiced',
        'clove',
      ],
    },
  },
  {
    title: 'Caballa al horno con puré de calabaza',
    description:
      'Otro pescado graso económico, al horno con limón, y un puré suave de calabaza con aceite de oliva en vez de manteca.',
    servings: 2,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'proteico', 'sin_tacc'],
    estimatedCostTotal: 6500,
    nutrition: {
      calories: 450,
      proteinG: 30,
      fatG: 26,
      carbsG: 24,
      fiberG: 5,
      sugarG: 9,
      sodiumMg: 200,
    },
    instructions: [
      'Pelar la calabaza, cortarla en cubos y hervirla 15 minutos.',
      'Hacer un puré con el aceite, la nuez moscada y pimienta.',
      'Mientras, hornear la caballa a 200 °C con rodajas de limón y el ajo picado, 12 a 15 minutos.',
      'Servir el pescado sobre el puré con perejil picado.',
    ],
    tips: [
      'Revisá bien que el pescado no tenga espinas antes de servir.',
      AVISO,
    ],
    ingredients: [
      { ingredientName: 'Caballa', quantity: 300, unit: G, notes: 'filetes' },
      { ingredientName: 'Calabaza', quantity: 600, unit: G },
      { ingredientName: 'Aceite', quantity: 20, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Nuez moscada', quantity: 1, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'diente' },
      { ingredientName: 'Perejil', quantity: 5, unit: G },
    ],
    en: {
      title: 'Baked mackerel with butternut squash mash',
      description:
        'Another affordable oily fish, baked with lemon, and a smooth butternut squash mash made with olive oil instead of butter.',
      instructions: [
        'Peel and cube the squash and boil it for 15 minutes.',
        'Mash it with the oil, nutmeg and pepper.',
        'Meanwhile, bake the mackerel at 200 °C (400 °F) with lemon slices and chopped garlic for 12 to 15 minutes.',
        'Serve the fish over the mash with chopped parsley.',
      ],
      tips: [
        'Check carefully that the fish has no bones before serving.',
        NOTICE,
      ],
      ingredientNotes: [
        'fillets',
        null,
        'olive oil',
        null,
        null,
        null,
        'clove',
        null,
      ],
    },
  },
  {
    title: 'Tortilla de espinaca al horno',
    description:
      'Tortilla de huevos y espinaca hecha al horno en lugar de frita, con poco queso: se corta en porciones y se come fría o caliente.',
    servings: 4,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['cerebro_sano', 'vegetariano', 'proteico', 'sin_tacc'],
    estimatedCostTotal: 3500,
    nutrition: {
      calories: 210,
      proteinG: 15,
      fatG: 14,
      carbsG: 7,
      fiberG: 2,
      sugarG: 3,
      sodiumMg: 260,
    },
    instructions: [
      'Precalentar el horno a 180 °C y aceitar una fuente chica.',
      'Saltear la cebolla en el aceite y agregar la espinaca hasta que se ablande. Dejar entibiar.',
      'Batir los huevos con la ricota, la nuez moscada y pimienta.',
      'Mezclar con la espinaca, volcar en la fuente y hornear 20 a 25 minutos, hasta que esté firme.',
    ],
    tips: [VITAMINA_K, AVISO],
    ingredients: [
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 15, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Espinaca', quantity: 300, unit: G },
      { ingredientName: 'Huevo', quantity: 6, unit: UN },
      { ingredientName: 'Ricota', quantity: 100, unit: G },
      { ingredientName: 'Nuez moscada', quantity: 1, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
    ],
    en: {
      title: 'Baked spinach frittata',
      description:
        'An egg and spinach omelette baked instead of fried, with little cheese: cut it into portions and eat it hot or cold.',
      instructions: [
        'Preheat the oven to 180 °C (350 °F) and oil a small baking dish.',
        'Sauté the onion in the oil and add the spinach until wilted. Let it cool slightly.',
        'Beat the eggs with the ricotta, nutmeg and pepper.',
        'Mix with the spinach, pour into the dish and bake 20 to 25 minutes, until set.',
      ],
      tips: [VITAMIN_K, NOTICE],
      ingredientNotes: [null, 'olive oil', null, null, null, null, null],
    },
  },
  {
    title: 'Manzanas asadas con nueces y canela',
    description:
      'Postre de fruta al horno con nueces y canela, sin azúcar agregada: una opción dulce para reemplazar facturas y tortas.',
    servings: 4,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.EASY,
    dietTags: [
      'cerebro_sano',
      'vegetariano',
      'vegano',
      'sin_tacc',
      'economico',
    ],
    estimatedCostTotal: 3000,
    nutrition: {
      calories: 190,
      proteinG: 2,
      fatG: 8,
      carbsG: 30,
      fiberG: 6,
      sugarG: 22,
      sodiumMg: 5,
    },
    instructions: [
      'Precalentar el horno a 180 °C.',
      'Quitarles el centro a las manzanas sin atravesarlas del todo.',
      'Rellenar con las nueces picadas mezcladas con la canela.',
      'Poner un poco de agua en la fuente y hornear 30 minutos, hasta que estén tiernas.',
    ],
    tips: [
      'Sin piel y bien cocidas quedan blandas, si cuesta masticar.',
      AVISO,
    ],
    ingredients: [
      { ingredientName: 'Manzana', quantity: 4, unit: UN },
      { ingredientName: 'Nueces', quantity: 40, unit: G },
      { ingredientName: 'Canela', quantity: 2, unit: G },
      { ingredientName: 'Agua', quantity: 100, unit: ML },
    ],
    en: {
      title: 'Baked apples with walnuts and cinnamon',
      description:
        'Oven-baked fruit with walnuts and cinnamon and no added sugar: a sweet option to replace pastries and cakes.',
      instructions: [
        'Preheat the oven to 180 °C (350 °F).',
        'Core the apples without cutting all the way through.',
        'Fill them with the chopped walnuts mixed with the cinnamon.',
        'Add a little water to the dish and bake for 30 minutes, until tender.',
      ],
      tips: [
        'Peeled and well cooked they turn out soft, if chewing is hard.',
        NOTICE,
      ],
      ingredientNotes: [null, null, null, null],
    },
  },

  // ─── Texturas suaves (poca sal, blandas y húmedas) ─────────────────────
  {
    title: 'Crema de calabaza y lentejas',
    description:
      'Crema lisa y espesa de calabaza con lentejas rojas: aporta proteína y fibra sin necesidad de masticar.',
    servings: 4,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: [
      'textura_suave',
      'cerebro_sano',
      'vegetariano',
      'vegano',
      'sin_tacc',
      'economico',
    ],
    estimatedCostTotal: 3500,
    nutrition: {
      calories: 230,
      proteinG: 11,
      fatG: 5,
      carbsG: 36,
      fiberG: 8,
      sugarG: 7,
      sodiumMg: 180,
    },
    instructions: [
      'Rehogar la cebolla picada en el aceite.',
      'Agregar la calabaza en cubos, las lentejas lavadas y el caldo. Cocinar 25 minutos, hasta que todo esté muy tierno.',
      'Licuar o procesar hasta que quede completamente lisa, sin grumos ni hebras.',
      'Si queda muy espesa, agregar caldo; si queda líquida, cocinar unos minutos más. Condimentar con cúrcuma y pimienta.',
    ],
    tips: [TEXTURA, AVISO],
    ingredients: [
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 15, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Calabaza', quantity: 600, unit: G },
      {
        ingredientName: 'Lentejas',
        quantity: 100,
        unit: G,
        notes: 'mejor si son rojas',
      },
      {
        ingredientName: 'Caldo',
        quantity: 800,
        unit: ML,
        notes: 'casero o bajo en sodio',
      },
      { ingredientName: 'Cúrcuma', quantity: 1, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
    ],
    en: {
      title: 'Butternut squash and lentil soup',
      description:
        'A smooth, thick butternut squash soup with red lentils: protein and fiber with no chewing needed.',
      instructions: [
        'Cook the chopped onion in the oil until soft.',
        'Add the cubed squash, rinsed lentils and stock. Cook for 25 minutes, until everything is very tender.',
        'Blend until completely smooth, with no lumps or strands.',
        'If too thick, add stock; if too thin, cook a few more minutes. Season with turmeric and pepper.',
      ],
      tips: [TEXTURE, NOTICE],
      ingredientNotes: [
        null,
        'olive oil',
        null,
        'red lentils are best',
        'homemade or low-sodium',
        null,
        null,
      ],
    },
  },
  {
    title: 'Merluza desmenuzada con puré de papa y zanahoria',
    description:
      'Pescado blanco cocido y desmenuzado, sin espinas, sobre un puré húmedo: fácil de masticar y de tragar.',
    servings: 2,
    prepTimeMinutes: 30,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['textura_suave', 'cerebro_sano', 'proteico', 'sin_tacc'],
    estimatedCostTotal: 5000,
    nutrition: {
      calories: 360,
      proteinG: 30,
      fatG: 10,
      carbsG: 36,
      fiberG: 5,
      sugarG: 6,
      sodiumMg: 200,
    },
    instructions: [
      'Hervir la papa y la zanahoria peladas hasta que estén muy tiernas, y hacer un puré bien liso con la leche caliente y el aceite.',
      'Cocinar la merluza al vapor o en agua apenas hirviendo 8 minutos.',
      'Desmenuzarla con un tenedor y revisar con los dedos que no quede ninguna espina.',
      'Mezclar el pescado con un poco del puré o servirlo encima, humedecido con una cucharada de caldo o leche.',
    ],
    tips: [TEXTURA, 'Revisá dos veces que no queden espinas.', AVISO],
    ingredients: [
      { ingredientName: 'Papa', quantity: 2, unit: UN },
      { ingredientName: 'Zanahoria', quantity: 1, unit: UN },
      { ingredientName: 'Leche', quantity: 100, unit: ML },
      { ingredientName: 'Aceite', quantity: 15, unit: ML, notes: 'de oliva' },
      {
        ingredientName: 'Merluza',
        quantity: 300,
        unit: G,
        notes: 'filetes sin espinas',
      },
    ],
    en: {
      title: 'Flaked hake with potato and carrot mash',
      description:
        'Cooked, flaked, boneless white fish over a moist mash: easy to chew and swallow.',
      instructions: [
        'Boil the peeled potato and carrot until very tender and mash them smooth with the hot milk and the oil.',
        'Steam the hake or poach it in barely simmering water for 8 minutes.',
        'Flake it with a fork and check with your fingers that no bones remain.',
        'Mix the fish into some of the mash or serve it on top, moistened with a spoonful of stock or milk.',
      ],
      tips: [TEXTURE, 'Check twice that no bones remain.', NOTICE],
      ingredientNotes: [null, null, null, 'olive oil', 'boneless fillets'],
    },
  },
  {
    title: 'Crema de zapallitos y espinaca',
    description:
      'Crema de verduras verde y suave, con ricota para darle cremosidad y proteína sin agregar crema.',
    servings: 4,
    prepTimeMinutes: 30,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['textura_suave', 'cerebro_sano', 'vegetariano', 'sin_tacc'],
    estimatedCostTotal: 3500,
    nutrition: {
      calories: 150,
      proteinG: 8,
      fatG: 8,
      carbsG: 12,
      fiberG: 4,
      sugarG: 6,
      sodiumMg: 170,
    },
    instructions: [
      'Rehogar la cebolla en el aceite.',
      'Agregar los zapallitos y la papa en cubos y el caldo. Cocinar 15 minutos.',
      'Sumar la espinaca y cocinar 2 minutos.',
      'Licuar con la ricota hasta que quede totalmente lisa. Condimentar con nuez moscada y pimienta.',
    ],
    tips: [TEXTURA, VITAMINA_K, AVISO],
    ingredients: [
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 15, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Zapallito', quantity: 3, unit: UN },
      { ingredientName: 'Papa', quantity: 1, unit: UN },
      {
        ingredientName: 'Caldo',
        quantity: 700,
        unit: ML,
        notes: 'casero o bajo en sodio',
      },
      { ingredientName: 'Espinaca', quantity: 150, unit: G },
      { ingredientName: 'Ricota', quantity: 100, unit: G },
      { ingredientName: 'Nuez moscada', quantity: 1, unit: G },
      { ingredientName: 'Pimienta negra', quantity: 1, unit: G },
    ],
    en: {
      title: 'Zucchini and spinach soup',
      description:
        'A smooth green vegetable soup with ricotta for creaminess and protein without adding cream.',
      instructions: [
        'Cook the onion in the oil until soft.',
        'Add the cubed zucchini and potato and the stock. Cook for 15 minutes.',
        'Add the spinach and cook for 2 minutes.',
        'Blend with the ricotta until completely smooth. Season with nutmeg and pepper.',
      ],
      tips: [TEXTURE, VITAMIN_K, NOTICE],
      ingredientNotes: [
        null,
        'olive oil',
        null,
        null,
        'homemade or low-sodium',
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    title: 'Pollo desmenuzado en salsa suave con puré de batata',
    description:
      'Pollo cocido muy tierno, desmenuzado y con salsa para que esté húmedo, sobre puré de batata.',
    servings: 2,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['textura_suave', 'cerebro_sano', 'proteico', 'sin_tacc'],
    estimatedCostTotal: 5000,
    nutrition: {
      calories: 420,
      proteinG: 36,
      fatG: 10,
      carbsG: 44,
      fiberG: 6,
      sugarG: 12,
      sodiumMg: 220,
    },
    instructions: [
      'Cocinar el pollo en el caldo a fuego bajo 20 minutos, hasta que esté muy tierno. Reservar el caldo.',
      'Hervir la batata pelada y hacer un puré liso con el aceite.',
      'Desmenuzar el pollo en hebras finas.',
      'Salsa: rehogar la zanahoria rallada fina, agregar 200 ml del caldo y el pollo, y cocinar 5 minutos para que se humedezca.',
      'Servir el pollo con su salsa sobre el puré.',
    ],
    tips: [TEXTURA, AVISO],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 300, unit: G },
      {
        ingredientName: 'Caldo',
        quantity: 600,
        unit: ML,
        notes: 'casero o bajo en sodio',
      },
      { ingredientName: 'Batata', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 15, unit: ML, notes: 'de oliva' },
      {
        ingredientName: 'Zanahoria',
        quantity: 1,
        unit: UN,
        notes: 'rallada fina',
      },
    ],
    en: {
      title: 'Shredded chicken in mild sauce with sweet potato mash',
      description:
        'Very tender cooked chicken, shredded and in sauce so it stays moist, over sweet potato mash.',
      instructions: [
        'Simmer the chicken in the stock on low heat for 20 minutes, until very tender. Keep the stock.',
        'Boil the peeled sweet potato and mash it smooth with the oil.',
        'Shred the chicken into fine strands.',
        'Sauce: cook the finely grated carrot, add 200 ml of the stock and the chicken, and cook 5 minutes so it gets moist.',
        'Serve the chicken with its sauce over the mash.',
      ],
      tips: [TEXTURE, NOTICE],
      ingredientNotes: [
        null,
        'homemade or low-sodium',
        null,
        'olive oil',
        'finely grated',
      ],
    },
  },
  {
    title: 'Compota de pera y manzana',
    description:
      'Fruta cocida y pisada, sin azúcar agregada: un postre suave y fácil de tragar.',
    servings: 4,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: [
      'textura_suave',
      'cerebro_sano',
      'vegetariano',
      'vegano',
      'sin_tacc',
      'economico',
    ],
    estimatedCostTotal: 2500,
    nutrition: {
      calories: 110,
      proteinG: 0.5,
      fatG: 0.3,
      carbsG: 28,
      fiberG: 5,
      sugarG: 20,
      sodiumMg: 2,
    },
    instructions: [
      'Pelar las peras y las manzanas, quitarles el centro y cortarlas en cubos.',
      'Cocinarlas tapadas con el agua y la canela 15 minutos, hasta que estén muy blandas.',
      'Pisar o procesar hasta lograr la textura indicada (lisa si hay dificultad para tragar).',
      'Servir tibia o fría.',
    ],
    tips: [TEXTURA, AVISO],
    ingredients: [
      { ingredientName: 'Pera', quantity: 2, unit: UN },
      { ingredientName: 'Manzana', quantity: 2, unit: UN },
      { ingredientName: 'Agua', quantity: 100, unit: ML },
      { ingredientName: 'Canela', quantity: 1, unit: G },
    ],
    en: {
      title: 'Pear and apple compote',
      description:
        'Cooked, mashed fruit with no added sugar: a soft dessert that is easy to swallow.',
      instructions: [
        'Peel and core the pears and apples and cut them into cubes.',
        'Cook them covered with the water and cinnamon for 15 minutes, until very soft.',
        'Mash or blend to the recommended texture (smooth if swallowing is difficult).',
        'Serve warm or cold.',
      ],
      tips: [TEXTURE, NOTICE],
      ingredientNotes: [null, null, null, null],
    },
  },
  {
    title: 'Huevos revueltos cremosos con palta',
    description:
      'Huevos cocidos a fuego bajo para que queden húmedos, con palta pisada: un desayuno blando y nutritivo.',
    servings: 1,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: [
      'textura_suave',
      'cerebro_sano',
      'vegetariano',
      'proteico',
      'sin_tacc',
    ],
    estimatedCostTotal: 2000,
    nutrition: {
      calories: 330,
      proteinG: 15,
      fatG: 27,
      carbsG: 8,
      fiberG: 5,
      sugarG: 1,
      sodiumMg: 160,
    },
    instructions: [
      'Batir los huevos con la leche.',
      'Cocinarlos en una sartén con el aceite a fuego mínimo, revolviendo todo el tiempo, hasta que estén cremosos y sin partes secas.',
      'Pisar la palta con unas gotas de limón.',
      'Servir los huevos con la palta al lado.',
    ],
    tips: [TEXTURA, AVISO],
    ingredients: [
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Leche', quantity: 30, unit: ML },
      { ingredientName: 'Aceite', quantity: 5, unit: ML, notes: 'de oliva' },
      { ingredientName: 'Palta', quantity: 1, unit: UN, notes: 'media' },
      { ingredientName: 'Limón', quantity: 1, unit: UN, notes: 'unas gotas' },
    ],
    en: {
      title: 'Creamy scrambled eggs with avocado',
      description:
        'Eggs cooked on low heat so they stay moist, with mashed avocado: a soft and nourishing breakfast.',
      instructions: [
        'Beat the eggs with the milk.',
        'Cook them in a pan with the oil on the lowest heat, stirring constantly, until creamy with no dry bits.',
        'Mash the avocado with a few drops of lemon.',
        'Serve the eggs with the avocado on the side.',
      ],
      tips: [TEXTURE, NOTICE],
      ingredientNotes: [null, null, 'olive oil', 'half', 'a few drops'],
    },
  },
];
