import 'reflect-metadata';
import * as path from 'path';
import { DataSource, ILike } from 'typeorm';
import * as dotenv from 'dotenv';
import { Ingredient } from '../../modules/ingredients/entities/ingredient.entity';
import { Recipe } from '../../modules/recipes/entities/recipe.entity';
import { IngredientUnit, RecipeDifficulty } from '../../common/enums';

dotenv.config();

interface SeedRecipeIngredient {
  ingredientName: string;
  quantity: number;
  unit: IngredientUnit;
  notes?: string;
}

interface SeedRecipe {
  title: string;
  imageUrl?: string;
  description: string;
  servings: number;
  prepTimeMinutes: number;
  difficulty: RecipeDifficulty;
  dietTags: string[];
  estimatedCostTotal: number;
  nutrition: {
    calories: number;
    proteinG: number;
    fatG: number;
    carbsG: number;
    fiberG: number;
    sugarG: number;
    sodiumMg: number;
  };
  instructions: string[];
  ingredients: SeedRecipeIngredient[];
}

const G = IngredientUnit.GRAMS;
const KG = IngredientUnit.KILOGRAMS;
const L = IngredientUnit.LITERS;
const UN = IngredientUnit.UNIT;

const seedRecipes: SeedRecipe[] = [
  {
    title: 'Milanesas de pollo con puré de papas',
    description:
      'El clásico de todas las casas: milanesas doradas y crocantes acompañadas de un puré cremoso.',
    servings: 4,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico'],
    estimatedCostTotal: 8000,
    nutrition: { calories: 620, proteinG: 40, fatG: 25, carbsG: 55, fiberG: 5, sugarG: 4, sodiumMg: 480 },
    instructions: [
      'Cortar la pechuga de pollo en filetes finos y salpimentar.',
      'Pasar cada filete por huevo batido y luego por pan rallado, presionando bien.',
      'Freír las milanesas en aceite caliente hasta dorar de ambos lados. Escurrir sobre papel absorbente.',
      'Pelar y hervir las papas en agua con sal hasta que estén tiernas.',
      'Hacer puré con las papas calientes, un chorrito de aceite y sal a gusto.',
      'Servir las milanesas junto al puré.',
    ],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 0.6, unit: KG },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Pan', quantity: 1, unit: UN, notes: 'rallado' },
      { ingredientName: 'Papa', quantity: 1, unit: KG },
      { ingredientName: 'Aceite', quantity: 0.2, unit: L },
      { ingredientName: 'Sal', quantity: 10, unit: G },
    ],
  },
  {
    title: 'Tortilla de papas y huevo',
    description: 'Tortilla española casera, jugosa por dentro y dorada por fuera.',
    servings: 4,
    prepTimeMinutes: 30,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['vegetariano', 'economico'],
    estimatedCostTotal: 3500,
    nutrition: { calories: 320, proteinG: 14, fatG: 18, carbsG: 28, fiberG: 3, sugarG: 3, sodiumMg: 380 },
    instructions: [
      'Pelar y cortar las papas en rodajas finas. Cortar la cebolla en juliana.',
      'Freír las papas y la cebolla en aceite a fuego suave hasta que estén tiernas, sin dorar.',
      'Escurrir el exceso de aceite y mezclar con los huevos batidos y sal.',
      'Volcar todo en una sartén caliente y cocinar a fuego medio-bajo.',
      'Dar vuelta la tortilla con ayuda de un plato y cocinar del otro lado hasta que cuaje.',
    ],
    ingredients: [
      { ingredientName: 'Papa', quantity: 0.5, unit: KG },
      { ingredientName: 'Huevo', quantity: 6, unit: UN },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.1, unit: L },
      { ingredientName: 'Sal', quantity: 5, unit: G },
    ],
  },
  {
    title: 'Arroz con pollo',
    description: 'Arroz sabroso cocido junto al pollo, morrón y cebolla en una sola olla.',
    servings: 4,
    prepTimeMinutes: 45,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico'],
    estimatedCostTotal: 6000,
    nutrition: { calories: 480, proteinG: 32, fatG: 12, carbsG: 58, fiberG: 3, sugarG: 4, sodiumMg: 420 },
    instructions: [
      'Cortar el pollo en cubos y dorarlo en una olla con aceite. Reservar.',
      'En la misma olla, rehogar la cebolla, el morrón y el ajo picados.',
      'Agregar el arroz y mezclar un minuto para que tome sabor.',
      'Incorporar el pollo dorado y cubrir con agua caliente. Salar.',
      'Cocinar tapado a fuego bajo hasta que el arroz esté a punto, revolviendo de vez en cuando.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.3, unit: KG },
      { ingredientName: 'Pollo (pechuga)', quantity: 0.5, unit: KG },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.05, unit: L },
      { ingredientName: 'Sal', quantity: 8, unit: G },
    ],
  },
  {
    title: 'Ensalada de lentejas',
    description: 'Fresca, económica y rendidora — ideal como plato principal liviano.',
    servings: 4,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'vegano', 'economico'],
    estimatedCostTotal: 2500,
    nutrition: { calories: 280, proteinG: 15, fatG: 8, carbsG: 38, fiberG: 12, sugarG: 5, sodiumMg: 320 },
    instructions: [
      'Cocinar las lentejas en agua con sal hasta que estén tiernas. Escurrir y dejar enfriar.',
      'Cortar la cebolla y el tomate en cubos pequeños.',
      'Mezclar las lentejas con la cebolla, el tomate, aceite, sal y jugo de limón.',
      'Dejar reposar unos minutos en la heladera antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Lentejas', quantity: 0.3, unit: KG },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Tomate', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 5, unit: G },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
    ],
  },
  {
    title: 'Tarta de verduras',
    description: 'Tarta casera de morrón, cebolla y queso, ideal para el almuerzo o la cena.',
    servings: 6,
    prepTimeMinutes: 50,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['vegetariano'],
    estimatedCostTotal: 4500,
    nutrition: { calories: 340, proteinG: 14, fatG: 20, carbsG: 26, fiberG: 3, sugarG: 4, sodiumMg: 400 },
    instructions: [
      'Mezclar la harina con aceite, sal y un poco de agua hasta formar una masa lisa. Dejar descansar.',
      'Estirar la masa y cubrir una tartera enmantecada.',
      'Rehogar la cebolla y el morrón cortados en aceite hasta que estén tiernos.',
      'Batir los huevos con la leche, mezclar con las verduras rehogadas y el queso en cubos.',
      'Volcar el relleno sobre la masa y hornear a fuego medio hasta que cuaje y dore, unos 30 minutos.',
    ],
    ingredients: [
      { ingredientName: 'Harina', quantity: 0.25, unit: KG },
      { ingredientName: 'Huevo', quantity: 3, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Queso', quantity: 150, unit: G },
      { ingredientName: 'Leche', quantity: 0.1, unit: L },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L },
      { ingredientName: 'Sal', quantity: 5, unit: G },
    ],
  },
  {
    title: 'Fideos con salsa de tomate y ajo',
    description: 'Un plato rápido, económico y de siempre: fideos con una salsa simple de tomate y ajo.',
    servings: 4,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'vegano', 'economico'],
    estimatedCostTotal: 3000,
    nutrition: { calories: 410, proteinG: 12, fatG: 10, carbsG: 68, fiberG: 5, sugarG: 8, sodiumMg: 350 },
    instructions: [
      'Hervir los fideos en agua con sal según el tiempo indicado.',
      'Mientras tanto, rehogar el ajo y la cebolla picados en aceite a fuego suave.',
      'Agregar el tomate picado y cocinar hasta formar una salsa, salando a gusto.',
      'Escurrir los fideos y mezclar con la salsa antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Fideos', quantity: 0.4, unit: KG },
      { ingredientName: 'Tomate', quantity: 4, unit: UN },
      { ingredientName: 'Ajo', quantity: 3, unit: UN },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.04, unit: L },
      { ingredientName: 'Sal', quantity: 6, unit: G },
    ],
  },
  {
    title: 'Ensalada César simple',
    description: 'Versión casera y sencilla de la clásica ensalada César con pollo.',
    servings: 2,
    prepTimeMinutes: 20,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['fitness', 'proteico'],
    estimatedCostTotal: 4000,
    nutrition: { calories: 350, proteinG: 30, fatG: 18, carbsG: 18, fiberG: 3, sugarG: 3, sodiumMg: 460 },
    instructions: [
      'Cocinar la pechuga de pollo a la plancha con sal y cortarla en tiras.',
      'Cortar el pan en cubos y tostarlo en una sartén con un poco de aceite hasta dorar (croutons).',
      'Lavar y cortar la lechuga en trozos grandes.',
      'Mezclar la lechuga con el pollo, los croutons y el queso en láminas.',
      'Aliñar con aceite, sal y jugo de limón antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Lechuga', quantity: 1, unit: UN },
      { ingredientName: 'Pollo (pechuga)', quantity: 0.3, unit: KG },
      { ingredientName: 'Queso', quantity: 50, unit: G },
      { ingredientName: 'Pan', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 3, unit: G },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
    ],
  },
  {
    title: 'Guiso de lentejas con carne',
    description: 'Guiso abundante y reconfortante, perfecto para los días fríos.',
    servings: 6,
    prepTimeMinutes: 60,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['economico', 'proteico'],
    estimatedCostTotal: 5000,
    nutrition: { calories: 390, proteinG: 26, fatG: 15, carbsG: 34, fiberG: 10, sugarG: 4, sodiumMg: 410 },
    instructions: [
      'Rehogar la cebolla, el ajo y el morrón picados en una olla con aceite.',
      'Agregar la carne picada y cocinar hasta que pierda el color rosado.',
      'Incorporar la zanahoria en cubos y las lentejas, cubrir con agua y salar.',
      'Cocinar tapado a fuego medio-bajo hasta que las lentejas estén tiernas, revolviendo de vez en cuando.',
      'Ajustar la sal y dejar reposar unos minutos antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Lentejas', quantity: 0.3, unit: KG },
      { ingredientName: 'Carne picada', quantity: 0.4, unit: KG },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Zanahoria', quantity: 2, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 8, unit: G },
    ],
  },
  {
    title: 'Pescado al horno con papas y zanahoria',
    description: 'Pescado horneado con guarnición de papas y zanahorias, liviano y sabroso.',
    servings: 4,
    prepTimeMinutes: 45,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['fitness', 'proteico'],
    estimatedCostTotal: 7000,
    nutrition: { calories: 380, proteinG: 32, fatG: 12, carbsG: 32, fiberG: 5, sugarG: 5, sodiumMg: 360 },
    instructions: [
      'Precalentar el horno y colocar el pescado en una fuente aceitada.',
      'Cortar las papas y zanahorias en rodajas y disponerlas alrededor del pescado.',
      'Agregar la cebolla y el ajo picados, un chorro de aceite, sal y jugo de limón por encima.',
      'Hornear hasta que el pescado esté cocido y las papas tiernas, unos 30-35 minutos.',
    ],
    ingredients: [
      { ingredientName: 'Pescado (filete)', quantity: 0.6, unit: KG },
      { ingredientName: 'Papa', quantity: 0.5, unit: KG },
      { ingredientName: 'Zanahoria', quantity: 0.4, unit: KG },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.04, unit: L },
      { ingredientName: 'Sal', quantity: 8, unit: G },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
    ],
  },
  {
    title: 'Ensalada mixta de verduras',
    description: 'Ensalada fresca y simple para acompañar cualquier plato o comer sola.',
    servings: 4,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'vegano', 'fitness', 'economico'],
    estimatedCostTotal: 1800,
    nutrition: { calories: 120, proteinG: 2, fatG: 8, carbsG: 12, fiberG: 4, sugarG: 6, sodiumMg: 180 },
    instructions: [
      'Lavar y cortar la lechuga en trozos. Cortar el tomate y la cebolla en rodajas finas.',
      'Rallar o cortar en bastones finos la zanahoria.',
      'Mezclar todas las verduras en una fuente.',
      'Aliñar con aceite, sal y jugo de limón antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Lechuga', quantity: 1, unit: UN },
      { ingredientName: 'Tomate', quantity: 3, unit: UN },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Zanahoria', quantity: 0.3, unit: KG },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 4, unit: G },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
    ],
  },
  {
    title: 'Sopa de zanahoria',
    description: 'Sopa cremosa y reconfortante, ideal como entrada o plato liviano.',
    servings: 4,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'vegano', 'economico'],
    estimatedCostTotal: 1500,
    nutrition: { calories: 110, proteinG: 2, fatG: 5, carbsG: 15, fiberG: 4, sugarG: 7, sodiumMg: 300 },
    instructions: [
      'Rehogar la cebolla y el ajo picados en una olla con aceite.',
      'Agregar la zanahoria cortada en rodajas y cubrir con agua.',
      'Cocinar hasta que la zanahoria esté muy tierna. Salar a gusto.',
      'Procesar todo hasta lograr una crema homogénea y servir caliente.',
    ],
    ingredients: [
      { ingredientName: 'Zanahoria', quantity: 0.5, unit: KG },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Agua', quantity: 1, unit: L },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L },
      { ingredientName: 'Sal', quantity: 6, unit: G },
    ],
  },
  {
    title: 'Panqueques caseros',
    description: 'Panqueques simples para el desayuno, la merienda o rellenos salados/dulces.',
    servings: 4,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano'],
    estimatedCostTotal: 2200,
    nutrition: { calories: 220, proteinG: 8, fatG: 9, carbsG: 27, fiberG: 1, sugarG: 3, sodiumMg: 150 },
    instructions: [
      'Batir los huevos con la leche hasta integrar.',
      'Incorporar la harina y la sal de a poco, mezclando para evitar grumos.',
      'Calentar una sartén con un poco de aceite y volcar un cucharón de la mezcla, esparciendo bien.',
      'Cocinar hasta que se despegue de los bordes, dar vuelta y cocinar unos segundos más del otro lado.',
      'Repetir con el resto de la mezcla.',
    ],
    ingredients: [
      { ingredientName: 'Harina', quantity: 0.2, unit: KG },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Leche', quantity: 0.4, unit: L },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L },
      { ingredientName: 'Sal', quantity: 2, unit: G },
    ],
  },
  {
    title: 'Sandwich de pollo y vegetales',
    description: 'Sandwich completo con pollo grillado, lechuga, tomate y queso.',
    servings: 2,
    prepTimeMinutes: 20,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['fitness', 'proteico'],
    estimatedCostTotal: 3800,
    nutrition: { calories: 420, proteinG: 34, fatG: 16, carbsG: 34, fiberG: 3, sugarG: 4, sodiumMg: 520 },
    instructions: [
      'Cocinar la pechuga de pollo a la plancha con sal hasta que esté bien cocida.',
      'Cortar el pan al medio y tostarlo levemente si se desea.',
      'Armar el sandwich con lechuga, tomate en rodajas, el pollo y el queso.',
      'Rociar con un hilo de aceite antes de cerrar el sandwich.',
    ],
    ingredients: [
      { ingredientName: 'Pan', quantity: 2, unit: UN },
      { ingredientName: 'Pollo (pechuga)', quantity: 0.25, unit: KG },
      { ingredientName: 'Lechuga', quantity: 1, unit: UN },
      { ingredientName: 'Tomate', quantity: 1, unit: UN },
      { ingredientName: 'Queso', quantity: 40, unit: G },
      { ingredientName: 'Aceite', quantity: 0.01, unit: L },
      { ingredientName: 'Sal', quantity: 3, unit: G },
    ],
  },
  {
    title: 'Ensalada de frutas con yogur',
    description: 'Postre fresco y liviano con manzana, banana y yogur.',
    servings: 2,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'fitness'],
    estimatedCostTotal: 1600,
    nutrition: { calories: 190, proteinG: 6, fatG: 3, carbsG: 38, fiberG: 4, sugarG: 28, sodiumMg: 60 },
    instructions: [
      'Cortar la manzana y la banana en cubos pequeños.',
      'Mezclar la fruta con unas gotas de jugo de limón para evitar que se oxide.',
      'Servir en copas o bowls y cubrir con el yogur.',
    ],
    ingredients: [
      { ingredientName: 'Manzana', quantity: 1, unit: UN },
      { ingredientName: 'Banana', quantity: 2, unit: UN },
      { ingredientName: 'Yogur', quantity: 2, unit: UN },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
    ],
  },
  {
    title: 'Omelette de queso',
    description: 'Omelette simple y rápido, perfecto para un desayuno o cena liviana.',
    servings: 1,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'fitness', 'keto', 'proteico'],
    estimatedCostTotal: 1400,
    nutrition: { calories: 320, proteinG: 22, fatG: 25, carbsG: 3, fiberG: 0, sugarG: 1, sodiumMg: 380 },
    instructions: [
      'Batir los huevos con una pizca de sal.',
      'Calentar aceite en una sartén chica y volcar los huevos batidos.',
      'Cuando empiece a cuajar, agregar el queso en cubos o láminas sobre la mitad.',
      'Doblar el omelette al medio y cocinar unos segundos más antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Huevo', quantity: 3, unit: UN },
      { ingredientName: 'Queso', quantity: 40, unit: G },
      { ingredientName: 'Aceite', quantity: 0.01, unit: L },
      { ingredientName: 'Sal', quantity: 2, unit: G },
    ],
  },
  {
    title: 'Arroz con verduras salteadas',
    description: 'Arroz salteado con morrón, zanahoria y cebolla, colorido y rendidor.',
    servings: 4,
    prepTimeMinutes: 30,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'vegano', 'economico'],
    estimatedCostTotal: 2400,
    nutrition: { calories: 340, proteinG: 7, fatG: 9, carbsG: 58, fiberG: 4, sugarG: 5, sodiumMg: 320 },
    instructions: [
      'Cocinar el arroz en agua con sal hasta que esté a punto. Escurrir y reservar.',
      'Cortar el morrón, la zanahoria y la cebolla en cubos pequeños.',
      'Saltear las verduras con el ajo picado en aceite hasta que estén tiernas.',
      'Agregar el arroz cocido y saltear todo junto unos minutos, ajustando la sal.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.3, unit: KG },
      { ingredientName: 'Zanahoria', quantity: 0.3, unit: KG },
      { ingredientName: 'Morrón', quantity: 1, unit: UN },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.04, unit: L },
      { ingredientName: 'Sal', quantity: 6, unit: G },
    ],
  },
  {
    title: 'Energy balls crudas de dátil y cacao',
    description:
      'Bocaditos energéticos sin cocción, dulces por los dátiles y con el toque amargo del cacao.',
    servings: 8,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'comida_cruda', 'economico'],
    estimatedCostTotal: 2800,
    nutrition: { calories: 140, proteinG: 3, fatG: 8, carbsG: 16, fiberG: 3, sugarG: 11, sodiumMg: 20 },
    instructions: [
      'Retirar los carozos a los dátiles si los tuvieran.',
      'Procesar los dátiles junto con las almendras hasta lograr una pasta pegajosa y homogénea.',
      'Agregar el cacao amargo y una pizca de sal, mezclar bien.',
      'Formar bolitas con las manos y pasarlas por coco rallado.',
      'Llevar a la heladera al menos 30 minutos antes de servir para que tomen firmeza.',
    ],
    ingredients: [
      { ingredientName: 'Dátiles', quantity: 200, unit: G },
      { ingredientName: 'Almendras', quantity: 100, unit: G },
      { ingredientName: 'Cacao amargo', quantity: 20, unit: G },
      { ingredientName: 'Coco rallado', quantity: 30, unit: G },
      { ingredientName: 'Sal', quantity: 1, unit: G },
    ],
  },
  {
    title: 'Leche de almendras casera',
    description: 'Bebida vegetal simple, sin cocción, para tomar sola o usar en otras recetas.',
    servings: 4,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'comida_cruda'],
    estimatedCostTotal: 2200,
    nutrition: { calories: 90, proteinG: 3, fatG: 7, carbsG: 3, fiberG: 1, sugarG: 1, sodiumMg: 40 },
    instructions: [
      'Remojar las almendras en agua durante al menos 8 horas (o toda la noche) y luego escurrir.',
      'Licuar las almendras remojadas con el agua fresca durante un minuto, hasta que quede blanquecina.',
      'Colar con un lienzo o bolsa para leches vegetales, apretando bien para extraer todo el líquido.',
      'Agregar una pizca de sal, mezclar y guardar en la heladera hasta 3 días.',
    ],
    ingredients: [
      { ingredientName: 'Almendras', quantity: 150, unit: G },
      { ingredientName: 'Agua', quantity: 1, unit: L },
      { ingredientName: 'Sal', quantity: 1, unit: G },
    ],
  },
  {
    title: 'Ensalada crudivegana de zanahoria, manzana y limón',
    description: 'Ensalada fresca, rallada y sin cocción, ácida y crocante.',
    servings: 4,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'comida_cruda', 'fitness'],
    estimatedCostTotal: 1600,
    nutrition: { calories: 100, proteinG: 1, fatG: 5, carbsG: 14, fiberG: 3, sugarG: 9, sodiumMg: 120 },
    instructions: [
      'Rallar la zanahoria y la manzana en tiras finas (con o sin cáscara la manzana, a gusto).',
      'Mezclar de inmediato con el jugo de limón para que la manzana no se oxide.',
      'Aliñar con aceite y una pizca de sal.',
      'Servir bien fría, apenas armada.',
    ],
    ingredients: [
      { ingredientName: 'Zanahoria', quantity: 0.3, unit: KG },
      { ingredientName: 'Manzana', quantity: 2, unit: UN },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L },
      { ingredientName: 'Sal', quantity: 3, unit: G },
    ],
  },
  {
    title: 'Helado crudo de banana y cacao',
    description: '"Nice cream" cremoso hecho solo con banana congelada, sin heladera ni cocción.',
    servings: 3,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'comida_cruda', 'fitness'],
    estimatedCostTotal: 1400,
    nutrition: { calories: 150, proteinG: 2, fatG: 3, carbsG: 32, fiberG: 4, sugarG: 20, sodiumMg: 15 },
    instructions: [
      'Cortar las bananas maduras en rodajas y congelarlas al menos 4 horas (idealmente toda la noche).',
      'Procesar las rodajas congeladas hasta lograr una textura cremosa tipo helado, deteniéndose para raspar los bordes si hace falta.',
      'Agregar el cacao amargo y procesar unos segundos más para integrar.',
      'Servir enseguida con coco rallado por encima.',
    ],
    ingredients: [
      { ingredientName: 'Banana', quantity: 4, unit: UN },
      { ingredientName: 'Cacao amargo', quantity: 10, unit: G },
      { ingredientName: 'Coco rallado', quantity: 10, unit: G },
    ],
  },
  {
    title: 'Granola cruda de avena y semillas',
    description: 'Mezcla energética sin horno, lista en minutos, ideal para el desayuno con yogur o leche vegetal.',
    servings: 6,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'comida_cruda'],
    estimatedCostTotal: 2600,
    nutrition: { calories: 210, proteinG: 6, fatG: 10, carbsG: 26, fiberG: 5, sugarG: 8, sodiumMg: 10 },
    instructions: [
      'Picar los dátiles y las almendras en trozos pequeños.',
      'Mezclar en un bol la avena, la chía, el coco rallado, los dátiles y las almendras picadas.',
      'Guardar en un frasco hermético a temperatura ambiente.',
      'Consumir con yogur, leche o leche vegetal y fruta fresca.',
    ],
    ingredients: [
      { ingredientName: 'Avena', quantity: 200, unit: G },
      { ingredientName: 'Almendras', quantity: 50, unit: G },
      { ingredientName: 'Chía', quantity: 20, unit: G },
      { ingredientName: 'Coco rallado', quantity: 30, unit: G },
      { ingredientName: 'Dátiles', quantity: 50, unit: G },
    ],
  },
  {
    title: 'Bowl crudo de manzana, chía y limón',
    description: 'Postre o desayuno liviano a base de gel de chía, manzana fresca y limón, sin cocción.',
    servings: 2,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'comida_cruda', 'economico'],
    estimatedCostTotal: 900,
    nutrition: { calories: 130, proteinG: 3, fatG: 5, carbsG: 20, fiberG: 7, sugarG: 12, sodiumMg: 5 },
    instructions: [
      'Cortar la manzana en cubos pequeños o rallarla.',
      'Mezclar la manzana con la chía, el agua y el jugo de limón en un bowl.',
      'Dejar reposar en la heladera unos 15 minutos, hasta que la chía se hidrate y forme un gel.',
      'Servir bien frío, revolviendo antes de comer.',
    ],
    ingredients: [
      { ingredientName: 'Manzana', quantity: 2, unit: UN },
      { ingredientName: 'Chía', quantity: 20, unit: G },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
      { ingredientName: 'Agua', quantity: 0.2, unit: L },
    ],
  },
  {
    title: 'Pollo a la mostaza',
    description:
      'Pechuga dorada y bañada en una salsa rápida de mostaza, ajo y limón: lista en 10 minutos.',
    servings: 1,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['proteico', 'fitness', 'keto'],
    estimatedCostTotal: 2500,
    nutrition: { calories: 280, proteinG: 35, fatG: 14, carbsG: 3, fiberG: 1, sugarG: 1, sodiumMg: 450 },
    instructions: [
      'Salpimentá la pechuga.',
      'Doralá en una sartén con el aceite de oliva a fuego medio.',
      'Agregá el ajo y cociná 30 segundos, sin que se queme.',
      'Incorporá la mostaza y el jugo de limón.',
      'Cociná 2-3 minutos más.',
      'Serví con ensalada o verduras.',
    ],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 0.2, unit: KG },
      { ingredientName: 'Mostaza', quantity: 15, unit: G },
      { ingredientName: 'Aceite', quantity: 0.01, unit: L },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'picado' },
      { ingredientName: 'Limón', quantity: 0.5, unit: UN, notes: 'el jugo' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
    ],
  },
  {
    title: 'Pollo al curry',
    description:
      'La pechuga de pollo no tiene por qué ser aburrida: cubos jugosos en una salsa cremosa de curry y leche de coco, listos en 20 minutos.',
    servings: 3,
    prepTimeMinutes: 20,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['proteico', 'fitness'],
    estimatedCostTotal: 3800,
    nutrition: { calories: 320, proteinG: 34, fatG: 16, carbsG: 6, fiberG: 2, sugarG: 3, sodiumMg: 380 },
    instructions: [
      'Salpimentar el pollo y dorarlo en una sartén con el aceite de oliva. Retirar y reservar.',
      'En la misma sartén, cocinar la cebolla durante 3-4 minutos hasta que esté transparente.',
      'Agregar el ajo y el curry, y cocinar 30 segundos para potenciar su aroma.',
      'Incorporar la leche de coco y mezclar bien.',
      'Volver a agregar el pollo y cocinar 5-7 minutos más, hasta que la salsa espese y el pollo esté bien cocido.',
      'Servir con verduras salteadas, arroz o puré de coliflor, y perejil o cilantro picado por encima.',
    ],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 0.35, unit: KG, notes: 'en cubos' },
      { ingredientName: 'Aceite', quantity: 0.01, unit: L },
      { ingredientName: 'Cebolla', quantity: 0.5, unit: UN, notes: 'picada' },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'picado' },
      { ingredientName: 'Curry en polvo', quantity: 5, unit: G },
      { ingredientName: 'Leche de coco', quantity: 0.1, unit: L, notes: 'sin azúcar' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Perejil', quantity: 2, unit: G, notes: 'o cilantro, opcional' },
    ],
  },
  {
    title: 'Pizza de pollo',
    description:
      'Una base de pizza hecha con pechuga de pollo procesada en lugar de harina, cubierta con salsa de tomate y mozzarella.',
    servings: 2,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico', 'fitness', 'sin_tacc'],
    estimatedCostTotal: 3200,
    nutrition: { calories: 380, proteinG: 42, fatG: 20, carbsG: 6, fiberG: 1, sugarG: 3, sodiumMg: 520 },
    instructions: [
      'Mezclar el pollo procesado con el huevo, el queso rallado y los condimentos.',
      'Formar una base fina sobre una placa con papel manteca.',
      'Hornear a 200 °C durante 18-20 minutos, hasta que esté firme y apenas dorada.',
      'Retirar del horno, agregar la salsa de tomate, la mozzarella y el orégano.',
      'Llevar nuevamente al horno 5 minutos, hasta que el queso se derrita.',
      'Terminar con albahaca fresca si gusta.',
    ],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 0.3, unit: KG, notes: 'procesada' },
      { ingredientName: 'Huevo', quantity: 1, unit: UN },
      { ingredientName: 'Queso', quantity: 30, unit: G, notes: 'rallado' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Ajo en polvo', quantity: 2, unit: G },
      { ingredientName: 'Orégano', quantity: 4, unit: G, notes: 'para la masa y para decorar' },
      { ingredientName: 'Salsa de tomate', quantity: 40, unit: G },
      { ingredientName: 'Mozzarella', quantity: 70, unit: G },
      { ingredientName: 'Albahaca', quantity: 3, unit: G, notes: 'opcional' },
    ],
  },
  {
    title: 'Pollo al limón y ajo',
    description:
      'Pechugas marinadas en limón, ajo y perejil, doradas en sartén: simples, jugosas y llenas de sabor.',
    servings: 2,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['proteico', 'fitness'],
    estimatedCostTotal: 3000,
    nutrition: { calories: 280, proteinG: 38, fatG: 12, carbsG: 3, fiberG: 1, sugarG: 1, sodiumMg: 320 },
    instructions: [
      'Mezclar el jugo de limón con el ajo, el aceite de oliva, el perejil, la sal y la pimienta.',
      'Marinar la pechuga durante 20 minutos.',
      'Cocinar en una sartén bien caliente durante 5-6 minutos por lado, hasta que esté dorada.',
      'Agregar el resto de la marinada el último minuto para potenciar el sabor.',
      'Servir con verduras asadas, una ensalada o puré de coliflor.',
    ],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 0.3, unit: KG },
      { ingredientName: 'Limón', quantity: 0.5, unit: UN, notes: 'el jugo' },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'picados' },
      { ingredientName: 'Aceite', quantity: 0.01, unit: L },
      { ingredientName: 'Perejil', quantity: 5, unit: G, notes: 'fresco picado' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
    ],
  },
  {
    title: 'Pollo crocante con yogur y semillas',
    description:
      'Bastones de pollo marinados en yogur y ajo, rebozados en semillas mixtas y horneados (o al air fryer) hasta quedar dorados y crocantes.',
    servings: 3,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico', 'fitness'],
    estimatedCostTotal: 3600,
    nutrition: { calories: 340, proteinG: 36, fatG: 18, carbsG: 8, fiberG: 4, sugarG: 2, sodiumMg: 300 },
    instructions: [
      'Cortar la pechuga en bastones o tiras.',
      'Mezclar el yogur con el ajo en polvo, la sal y la pimienta. Cubrir el pollo y dejar marinar 20 minutos.',
      'En un plato, mezclar las semillas con el orégano seco.',
      'Retirar el pollo del yogur y rebozarlo bien en las semillas, presionando para que se adhieran.',
      'Colocar en una placa con papel manteca o en la air fryer con un toque de aceite.',
      'Hornear a 200 °C o cocinar en la air fryer hasta que estén dorados y cocidos.',
      'Servir con dip de yogur o ensalada.',
    ],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 0.3, unit: KG, notes: 'cortada en bastones' },
      { ingredientName: 'Yogur griego', quantity: 120, unit: G, notes: 'natural' },
      { ingredientName: 'Ajo en polvo', quantity: 3, unit: G },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Semillas mixtas', quantity: 60, unit: G, notes: 'sésamo, lino, chía, girasol' },
      { ingredientName: 'Aceite', quantity: 0.01, unit: L },
      { ingredientName: 'Orégano', quantity: 2, unit: G, notes: 'o perejil seco, opcional' },
    ],
  },
  {
    title: 'Milanesas de berenjena al horno',
    description: 'Versión vegetariana de las milanesas, con rodajas de berenjena rebozadas y horneadas.',
    servings: 3,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['vegetariano', 'economico'],
    estimatedCostTotal: 2800,
    nutrition: { calories: 240, proteinG: 11, fatG: 12, carbsG: 22, fiberG: 5, sugarG: 5, sodiumMg: 380 },
    instructions: [
      'Cortar la berenjena en rodajas de medio centímetro y salarlas. Dejar reposar 15 minutos y secar con papel.',
      'Pasar cada rodaja por huevo batido y luego por pan rallado, presionando bien.',
      'Colocar en una placa con papel manteca y rociar con un hilo de aceite.',
      'Hornear a 200 °C durante 20-25 minutos, dando vuelta a mitad de cocción, hasta dorar.',
      'Servir con queso rallado por encima o ensalada.',
    ],
    ingredients: [
      { ingredientName: 'Berenjena', quantity: 2, unit: UN },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Pan rallado', quantity: 100, unit: G },
      { ingredientName: 'Queso', quantity: 40, unit: G, notes: 'rallado, opcional' },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L },
      { ingredientName: 'Sal', quantity: 6, unit: G },
    ],
  },
  {
    title: 'Guacamole casero',
    description: 'Clásico dip mexicano de palta bien fresco, ideal para untar o acompañar cualquier plato.',
    servings: 4,
    prepTimeMinutes: 10,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'comida_cruda', 'fitness'],
    estimatedCostTotal: 2600,
    nutrition: { calories: 160, proteinG: 2, fatG: 15, carbsG: 8, fiberG: 6, sugarG: 2, sodiumMg: 150 },
    instructions: [
      'Pisar la pulpa de las paltas con un tenedor hasta lograr una textura cremosa con algunos grumos.',
      'Picar la cebolla y el tomate en cubos muy pequeños.',
      'Mezclar la palta con la cebolla, el tomate y el jugo de limón.',
      'Salar a gusto y servir de inmediato para que no se oxide.',
    ],
    ingredients: [
      { ingredientName: 'Palta', quantity: 2, unit: UN },
      { ingredientName: 'Cebolla', quantity: 0.5, unit: UN, notes: 'picada' },
      { ingredientName: 'Tomate', quantity: 1, unit: UN, notes: 'picado' },
      { ingredientName: 'Limón', quantity: 1, unit: UN, notes: 'el jugo' },
      { ingredientName: 'Sal', quantity: 3, unit: G },
    ],
  },
  {
    title: 'Ensalada de garbanzos con verduras',
    description: 'Ensalada fría, proteica y rendidora con garbanzos, morrón, tomate y cebolla.',
    servings: 4,
    prepTimeMinutes: 20,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'economico', 'proteico'],
    estimatedCostTotal: 2600,
    nutrition: { calories: 260, proteinG: 11, fatG: 9, carbsG: 34, fiberG: 9, sugarG: 5, sodiumMg: 280 },
    instructions: [
      'Cocinar los garbanzos en agua con sal hasta que estén tiernos (o usar ya cocidos). Escurrir y dejar enfriar.',
      'Cortar el tomate, la cebolla y el morrón en cubos pequeños.',
      'Mezclar los garbanzos con las verduras picadas.',
      'Aliñar con aceite, sal y jugo de limón antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Garbanzos', quantity: 0.3, unit: KG },
      { ingredientName: 'Tomate', quantity: 2, unit: UN },
      { ingredientName: 'Cebolla', quantity: 0.5, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Limón', quantity: 1, unit: UN },
      { ingredientName: 'Sal', quantity: 5, unit: G },
    ],
  },
  {
    title: 'Tarta de atún y verduras',
    description: 'Tarta casera rellena de atún, cebolla, morrón y queso, perfecta para el almuerzo.',
    servings: 6,
    prepTimeMinutes: 50,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico'],
    estimatedCostTotal: 5200,
    nutrition: { calories: 320, proteinG: 20, fatG: 17, carbsG: 24, fiberG: 3, sugarG: 3, sodiumMg: 480 },
    instructions: [
      'Mezclar la harina con aceite, sal y un poco de agua hasta formar una masa lisa. Dejar descansar.',
      'Estirar la masa y cubrir una tartera enmantecada.',
      'Rehogar la cebolla y el morrón cortados en aceite hasta que estén tiernos.',
      'Batir los huevos, mezclar con las verduras rehogadas, el atún escurrido y el queso en cubos.',
      'Volcar el relleno sobre la masa y hornear a fuego medio hasta que cuaje y dore, unos 30 minutos.',
    ],
    ingredients: [
      { ingredientName: 'Harina', quantity: 0.25, unit: KG },
      { ingredientName: 'Huevo', quantity: 3, unit: UN },
      { ingredientName: 'Atún', quantity: 160, unit: G, notes: 'escurrido' },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN },
      { ingredientName: 'Queso', quantity: 100, unit: G },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L },
      { ingredientName: 'Sal', quantity: 5, unit: G },
    ],
  },
  {
    title: 'Batatas al horno con especias',
    description: 'Bastones de batata horneados hasta quedar tiernos por dentro y dorados por fuera.',
    servings: 4,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'economico', 'fitness'],
    estimatedCostTotal: 1800,
    nutrition: { calories: 160, proteinG: 2, fatG: 5, carbsG: 26, fiberG: 4, sugarG: 6, sodiumMg: 200 },
    instructions: [
      'Precalentar el horno. Cortar las batatas en bastones parejos, sin necesidad de pelarlas.',
      'Mezclar con aceite, sal y orégano en un bol, hasta cubrir bien.',
      'Disponer en una placa en una sola capa, sin amontonar.',
      'Hornear a 200 °C durante 25-30 minutos, dando vuelta a mitad de cocción, hasta dorar.',
    ],
    ingredients: [
      { ingredientName: 'Batata', quantity: 0.6, unit: KG },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 5, unit: G },
      { ingredientName: 'Orégano', quantity: 3, unit: G },
    ],
  },
  {
    title: 'Crema de calabaza',
    description: 'Sopa suave y dulzona, reconfortante y muy fácil de preparar.',
    servings: 4,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'economico'],
    estimatedCostTotal: 1700,
    nutrition: { calories: 100, proteinG: 2, fatG: 4, carbsG: 15, fiberG: 3, sugarG: 6, sodiumMg: 280 },
    instructions: [
      'Rehogar la cebolla y el ajo picados en una olla con aceite.',
      'Agregar la calabaza cortada en cubos y cubrir con agua.',
      'Cocinar hasta que la calabaza esté muy tierna. Salar a gusto.',
      'Procesar todo hasta lograr una crema homogénea y servir caliente.',
    ],
    ingredients: [
      { ingredientName: 'Calabaza', quantity: 0.6, unit: KG },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Ajo', quantity: 1, unit: UN },
      { ingredientName: 'Agua', quantity: 0.8, unit: L },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L },
      { ingredientName: 'Sal', quantity: 6, unit: G },
    ],
  },
  {
    title: 'Buñuelos de acelga',
    description: 'Bocaditos dorados de acelga rehogada, huevo y queso, ideales como entrada o picada.',
    servings: 4,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['vegetariano', 'economico'],
    estimatedCostTotal: 2400,
    nutrition: { calories: 220, proteinG: 10, fatG: 12, carbsG: 18, fiberG: 3, sugarG: 2, sodiumMg: 420 },
    instructions: [
      'Lavar y picar la acelga, y rehogarla en una sartén con un poco de aceite hasta que se ablande. Escurrir el exceso de agua.',
      'Mezclar la acelga con los huevos batidos, la harina y el queso en cubos.',
      'Salar la mezcla y formar bollitos con una cuchara.',
      'Freír en aceite caliente por tandas hasta dorar de ambos lados. Escurrir sobre papel absorbente.',
    ],
    ingredients: [
      { ingredientName: 'Acelga', quantity: 300, unit: G },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Harina', quantity: 0.1, unit: KG },
      { ingredientName: 'Queso', quantity: 60, unit: G },
      { ingredientName: 'Aceite', quantity: 0.1, unit: L },
      { ingredientName: 'Sal', quantity: 4, unit: G },
    ],
  },
  {
    title: 'Bife a la plancha con batatas al horno',
    description: 'Un plato completo y proteico: bife jugoso a la plancha acompañado de batatas horneadas.',
    servings: 2,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['proteico', 'fitness'],
    estimatedCostTotal: 5500,
    nutrition: { calories: 420, proteinG: 38, fatG: 18, carbsG: 26, fiberG: 3, sugarG: 5, sodiumMg: 320 },
    instructions: [
      'Cortar las batatas en bastones, condimentar con aceite y sal, y hornear a 200 °C durante 25-30 minutos.',
      'Salpimentar los bifes y dejarlos tomar temperatura ambiente unos minutos.',
      'Cocinar los bifes en una plancha o sartén bien caliente con un chorrito de aceite, 3-4 minutos por lado según el grosor.',
      'Agregar el ajo picado los últimos minutos de cocción.',
      'Servir el bife con las batatas y un toque de jugo de limón.',
    ],
    ingredients: [
      { ingredientName: 'Carne (bife)', quantity: 0.4, unit: KG },
      { ingredientName: 'Batata', quantity: 0.4, unit: KG },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'picado' },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 5, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Limón', quantity: 0.5, unit: UN, notes: 'opcional' },
    ],
  },
  {
    title: 'Bowl de yogur, granola y banana',
    description: 'Desayuno o merienda rápida y nutritiva, lista en 5 minutos sin cocción.',
    servings: 1,
    prepTimeMinutes: 5,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'fitness', 'comida_cruda'],
    estimatedCostTotal: 1200,
    nutrition: { calories: 300, proteinG: 14, fatG: 10, carbsG: 42, fiberG: 6, sugarG: 20, sodiumMg: 60 },
    instructions: [
      'Colocar el yogur griego en un bowl.',
      'Cortar la banana en rodajas y disponerla sobre el yogur.',
      'Espolvorear con avena y almendras picadas.',
      'Servir enseguida.',
    ],
    ingredients: [
      { ingredientName: 'Yogur griego', quantity: 150, unit: G },
      { ingredientName: 'Banana', quantity: 1, unit: UN },
      { ingredientName: 'Avena', quantity: 30, unit: G },
      { ingredientName: 'Almendras', quantity: 15, unit: G },
    ],
  },
  {
    title: 'Wrap de pollo, palta y vegetales',
    description: 'Tortilla de trigo rellena de pollo grillado, palta, lechuga y tomate, ideal para llevar.',
    servings: 2,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['proteico', 'fitness'],
    estimatedCostTotal: 4200,
    nutrition: { calories: 380, proteinG: 30, fatG: 16, carbsG: 30, fiberG: 6, sugarG: 3, sodiumMg: 460 },
    instructions: [
      'Cocinar la pechuga de pollo a la plancha con sal y cortarla en tiras.',
      'Pisar la palta con un poco de jugo de limón y sal.',
      'Calentar levemente las tortillas de trigo para que sean más flexibles.',
      'Untar cada tortilla con la palta pisada y agregar lechuga, tomate en rodajas y el pollo.',
      'Enrollar bien apretado y cortar al medio antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Tortilla de trigo', quantity: 2, unit: UN },
      { ingredientName: 'Pollo (pechuga)', quantity: 0.25, unit: KG },
      { ingredientName: 'Palta', quantity: 1, unit: UN },
      { ingredientName: 'Lechuga', quantity: 1, unit: UN },
      { ingredientName: 'Tomate', quantity: 1, unit: UN },
      { ingredientName: 'Limón', quantity: 0.5, unit: UN },
      { ingredientName: 'Sal', quantity: 3, unit: G },
    ],
  },
  {
    title: 'Bowl de atún, huevo y almendras',
    description:
      'Bowl rápido rico en yodo, selenio y zinc — nutrientes clave para el buen funcionamiento de la tiroides en el hipotiroidismo.',
    servings: 2,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['hipotiroidismo', 'proteico', 'fitness'],
    estimatedCostTotal: 4000,
    nutrition: { calories: 300, proteinG: 28, fatG: 18, carbsG: 4, fiberG: 1, sugarG: 1, sodiumMg: 380 },
    instructions: [
      'Hervir los huevos durante 9-10 minutos, enfriar, pelar y cortar por la mitad.',
      'Escurrir bien el atún.',
      'Lavar y cortar la lechuga en trozos.',
      'Armar el bowl con la lechuga, el atún, los huevos y las almendras picadas por encima.',
      'Aliñar con aceite de oliva, jugo de limón y sal a gusto.',
    ],
    ingredients: [
      { ingredientName: 'Atún', quantity: 120, unit: G, notes: 'escurrido' },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Almendras', quantity: 20, unit: G, notes: 'picadas' },
      { ingredientName: 'Lechuga', quantity: 1, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L },
      { ingredientName: 'Limón', quantity: 0.5, unit: UN },
      { ingredientName: 'Sal', quantity: 3, unit: G },
    ],
  },
  {
    title: 'Tostadas de atún, huevo y queso',
    description:
      'Tostadas calientes con atún, huevo y queso gratinado: una combinación práctica de yodo y selenio para el hipotiroidismo.',
    servings: 2,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['hipotiroidismo', 'proteico'],
    estimatedCostTotal: 3500,
    nutrition: { calories: 420, proteinG: 30, fatG: 16, carbsG: 35, fiberG: 2, sugarG: 3, sodiumMg: 650 },
    instructions: [
      'Hervir el huevo durante 9-10 minutos, enfriar, pelar y picar.',
      'Mezclar el atún escurrido con el huevo picado y la mostaza.',
      'Tostar el pan y repartir la mezcla de atún y huevo encima.',
      'Cubrir con el queso en láminas y llevar a horno o sandwichera hasta que se derrita.',
    ],
    ingredients: [
      { ingredientName: 'Pan', quantity: 2, unit: UN },
      { ingredientName: 'Atún', quantity: 120, unit: G, notes: 'escurrido' },
      { ingredientName: 'Huevo', quantity: 1, unit: UN },
      { ingredientName: 'Queso', quantity: 50, unit: G },
      { ingredientName: 'Mostaza', quantity: 10, unit: G, notes: 'opcional' },
      { ingredientName: 'Sal', quantity: 2, unit: G },
    ],
  },
  {
    title: 'Ensalada de brócoli y coliflor con queso',
    description:
      'Ensalada tibia de vegetales crucíferos con queso, una buena opción de calcio para acompañar el hipertiroidismo.',
    servings: 4,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['hipertiroidismo', 'vegetariano', 'fitness'],
    estimatedCostTotal: 3000,
    nutrition: { calories: 190, proteinG: 10, fatG: 13, carbsG: 9, fiberG: 4, sugarG: 3, sodiumMg: 220 },
    instructions: [
      'Cortar el brócoli y la coliflor en ramitos parejos.',
      'Cocinar al vapor o hervir ambos hasta que estén tiernos pero firmes, unos 8-10 minutos.',
      'Escurrir bien y dejar entibiar.',
      'Mezclar con el queso cortado en cubos.',
      'Aliñar con aceite de oliva, jugo de limón y sal a gusto.',
    ],
    ingredients: [
      { ingredientName: 'Brócoli', quantity: 0.3, unit: KG },
      { ingredientName: 'Coliflor', quantity: 0.3, unit: KG },
      { ingredientName: 'Queso', quantity: 100, unit: G },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Limón', quantity: 0.5, unit: UN },
      { ingredientName: 'Sal', quantity: 4, unit: G },
    ],
  },
  {
    title: 'Bife con brócoli y batatas al horno',
    description:
      'Plato completo y calórico con vegetales crucíferos, pensado para acompañar el mayor gasto energético del hipertiroidismo.',
    servings: 2,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['hipertiroidismo', 'proteico'],
    estimatedCostTotal: 7000,
    nutrition: { calories: 650, proteinG: 55, fatG: 28, carbsG: 45, fiberG: 8, sugarG: 5, sodiumMg: 350 },
    instructions: [
      'Precalentar el horno. Cortar la batata en cubos, condimentar con aceite y sal y hornear 25-30 minutos.',
      'Cocinar el brócoli al vapor o hervido hasta que esté tierno, unos 8 minutos.',
      'Salpimentar el bife y cocinarlo a la plancha con el ajo hasta el punto deseado.',
      'Servir el bife junto a la batata al horno y el brócoli.',
    ],
    ingredients: [
      { ingredientName: 'Carne (bife)', quantity: 0.4, unit: KG },
      { ingredientName: 'Brócoli', quantity: 0.3, unit: KG },
      { ingredientName: 'Batata', quantity: 0.4, unit: KG },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 6, unit: G },
    ],
  },
  {
    title: 'Sándwich de pepino y pollo',
    description:
      'Sándwich fresco con pollo, pepino y vegetales crocantes, bañado en una vinagreta de naranja y sésamo.',
    servings: 4,
    prepTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['proteico', 'fitness'],
    estimatedCostTotal: 3500,
    nutrition: { calories: 415, proteinG: 28, fatG: 22, carbsG: 32, fiberG: 3, sugarG: 12, sodiumMg: 420 },
    instructions: [
      'Para la vinagreta: procesar o licuar el jugo de naranja, el aceite de sésamo, el ajo, la sal y la pimienta hasta integrar.',
      'Agregar los gajos de naranja picados a la vinagreta y reservar.',
      'Cocinar las pechugas de pollo aplanadas a la plancha hasta que estén doradas y bien cocidas.',
      'Sobre una rebanada de pan, colocar el pollo, unas rodajas de pepino, el tomate cherry y el pimiento en juliana a gusto.',
      'Agregar una cucharadita de la vinagreta, tapar con otra rebanada de pan y servir. Tip: se puede reemplazar el pollo por queso.',
    ],
    ingredients: [
      { ingredientName: 'Pan', quantity: 8, unit: UN, notes: 'rebanadas, pan integral' },
      { ingredientName: 'Pollo (pechuga)', quantity: 0.3, unit: KG, notes: 'aplanada' },
      { ingredientName: 'Pepino', quantity: 2, unit: UN, notes: 'en rodajas' },
      { ingredientName: 'Tomate', quantity: 1, unit: UN, notes: 'cherry, en cuartos' },
      { ingredientName: 'Morrón', quantity: 1, unit: UN, notes: 'amarillo, en juliana' },
      { ingredientName: 'Naranja', quantity: 2, unit: UN, notes: 'el jugo de una y los gajos de la otra' },
      { ingredientName: 'Aceite de sésamo', quantity: 0.06, unit: L },
      { ingredientName: 'Ajo', quantity: 0.5, unit: UN, notes: 'picado finamente' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta negra a gusto' },
    ],
  },
  {
    title: 'Arroz con setas meloso',
    description: 'Arroz cremoso y meloso cocido lentamente con setas variadas, cebolla y un toque de vino blanco.',
    servings: 4,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['vegetariano'],
    estimatedCostTotal: 4500,
    nutrition: { calories: 380, proteinG: 9, fatG: 10, carbsG: 62, fiberG: 4, sugarG: 3, sodiumMg: 480 },
    instructions: [
      'Limpiar y trocear las setas. Picar finamente la cebolla y laminar los ajos.',
      'En una cazuela ancha, pochar la cebolla en aceite de oliva. Añadir el ajo y, un minuto después, las setas. Saltear a fuego fuerte hasta que se doren.',
      'Incorporar el arroz y nacarar durante 2 minutos. Verter el vino blanco y dejar que se evapore.',
      'Añadir un par de cucharones de caldo caliente y remover. Cocinar a fuego medio-bajo.',
      'Ir añadiendo caldo a medida que el arroz lo absorba, removiendo ocasionalmente, durante 18-20 minutos.',
      'Cuando el arroz esté tierno y meloso, retirar del fuego, tapar con un paño y dejar reposar 5 minutos.',
      'Servir inmediatamente con perejil fresco espolvoreado.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.32, unit: KG, notes: 'de grano redondo' },
      { ingredientName: 'Setas', quantity: 0.5, unit: KG, notes: 'variadas' },
      { ingredientName: 'Caldo', quantity: 1.2, unit: L, notes: 'de verduras o pollo, caliente' },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN, notes: 'grande' },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Vino blanco', quantity: 0.1, unit: L, notes: 'seco' },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 4, unit: G, notes: 'y pimienta negra a gusto' },
      { ingredientName: 'Perejil', quantity: 5, unit: G, notes: 'fresco' },
    ],
  },
  {
    title: 'Paella de carne',
    description: 'Paella tradicional con pollo y costillas de cerdo, pimientos, judías verdes y un sofrito de tomate con azafrán.',
    servings: 4,
    prepTimeMinutes: 90,
    difficulty: RecipeDifficulty.HARD,
    dietTags: ['proteico'],
    estimatedCostTotal: 9000,
    nutrition: { calories: 650, proteinG: 42, fatG: 30, carbsG: 55, fiberG: 5, sugarG: 4, sodiumMg: 620 },
    instructions: [
      'Cortar los pimientos en tiras y las judías verdes en trozos. Picar finamente los ajos. Rallar los tomates.',
      'Calentar aceite de oliva en una paellera y dorar el pollo y las costillas salpimentadas por todos lados. Retirar y reservar.',
      'En el mismo aceite, sofreír los pimientos, las judías verdes y luego el ajo picado. Justo antes de que dore, agregar el tomate rallado y cocinar hasta que se concentre.',
      'Incorporar el pimentón dulce, remover rápido y volver a poner las carnes en la paellera. Mezclar bien.',
      'Verter el caldo caliente con el azafrán, rectificar de sal y dejar hervir todo junto unos 10 minutos.',
      'Añadir el arroz repartiéndolo parejo por toda la paellera. Desde aquí no volver a remover.',
      'Cocinar a fuego fuerte 8-10 minutos y luego a fuego medio-bajo otros 8-10 minutos, hasta que el arroz absorba casi todo el caldo.',
      'Opcional: subir el fuego al máximo un minuto para formar el socarrat, sin dejar que se queme.',
      'Cubrir con un paño y dejar reposar 5-10 minutos antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.4, unit: KG, notes: 'tipo bomba o carnaroli' },
      { ingredientName: 'Pollo (pechuga)', quantity: 0.5, unit: KG, notes: 'muslos y contramuslos, troceado' },
      { ingredientName: 'Costillas de cerdo', quantity: 0.3, unit: KG, notes: 'troceadas' },
      { ingredientName: 'Morrón', quantity: 2, unit: UN, notes: 'uno rojo, uno verde, en tiras' },
      { ingredientName: 'Tomate', quantity: 2, unit: UN, notes: 'rallados' },
      { ingredientName: 'Chauchas', quantity: 0.15, unit: KG, notes: 'planas, en trozos' },
      { ingredientName: 'Ajo', quantity: 4, unit: UN },
      { ingredientName: 'Azafrán', quantity: 1, unit: G, notes: 'unas hebras' },
      { ingredientName: 'Pimentón dulce', quantity: 3, unit: G },
      { ingredientName: 'Aceite', quantity: 0.05, unit: L },
      { ingredientName: 'Sal', quantity: 6, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Caldo', quantity: 1.2, unit: L },
    ],
  },
  {
    title: 'Pan con psyllium',
    description: 'Pan de molde sin gluten a base de trigo sarraceno, maicena y harina de arroz, con psyllium como ligante.',
    servings: 10,
    prepTimeMinutes: 120,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['sin_tacc', 'vegano', 'vegetariano'],
    estimatedCostTotal: 4000,
    nutrition: { calories: 180, proteinG: 4, fatG: 4, carbsG: 32, fiberG: 5, sugarG: 1, sodiumMg: 220 },
    instructions: [
      'Activar el psyllium mezclándolo con 250 ml de agua tibia y dejar 5 minutos hasta formar un gel.',
      'Activar la levadura disolviéndola con el azúcar en 150 ml de agua tibia y dejar burbujear 10 minutos.',
      'Mezclar las harinas y la sal en un bol grande.',
      'Añadir el gel de psyllium, la mezcla de levadura y el aceite.',
      'Amasar 5 minutos, aunque quede pegajosa (es normal).',
      'Colocar en un molde aceitado, tapar y dejar leudar 1 hora hasta casi duplicar el volumen.',
      'Hornear a 200 °C por 45-50 minutos. Opcional: pintar con agua y espolvorear semillas antes de hornear.',
      'Dejar enfriar completamente antes de cortar.',
    ],
    ingredients: [
      { ingredientName: 'Psyllium', quantity: 15, unit: G, notes: 'en polvo' },
      { ingredientName: 'Agua', quantity: 0.4, unit: L, notes: 'tibia' },
      { ingredientName: 'Harina de trigo sarraceno', quantity: 0.3, unit: KG },
      { ingredientName: 'Almidón de maíz', quantity: 0.1, unit: KG, notes: 'maicena' },
      { ingredientName: 'Harina de arroz', quantity: 0.1, unit: KG },
      { ingredientName: 'Levadura', quantity: 7, unit: G, notes: 'seca de panadero' },
      { ingredientName: 'Sal', quantity: 5, unit: G },
      { ingredientName: 'Azúcar', quantity: 5, unit: G },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L, notes: 'de oliva' },
      { ingredientName: 'Semillas mixtas', quantity: 10, unit: G, notes: 'para decorar, opcional' },
    ],
  },
  {
    title: 'Cuscús base: cómo se cocina',
    description: 'La forma clásica de hidratar cuscús para usar como guarnición o base de otros platos.',
    servings: 2,
    prepTimeMinutes: 7,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegano', 'vegetariano', 'economico'],
    estimatedCostTotal: 1200,
    nutrition: { calories: 220, proteinG: 6, fatG: 6, carbsG: 38, fiberG: 2, sugarG: 0, sodiumMg: 380 },
    instructions: [
      'Calentar el agua o caldo en una olla, añadir sal y el aceite de oliva. Llevar a ebullición.',
      'Colocar el cuscús seco en un bol grande.',
      'Verter el líquido hirviendo sobre el cuscús. Remover rápidamente una sola vez para distribuirlo bien.',
      'Tapar el bol inmediatamente y dejar reposar 5 a 7 minutos sin destapar.',
      'Destapar, agregar la manteca si se usa, y separar los granos con un tenedor hasta que quede suelto y esponjoso.',
      'Servir como guarnición o base para otros platos, frío o caliente.',
    ],
    ingredients: [
      { ingredientName: 'Cuscús', quantity: 0.18, unit: KG, notes: 'sémola de trigo precocida' },
      { ingredientName: 'Caldo', quantity: 0.24, unit: L, notes: 'o agua' },
      { ingredientName: 'Aceite', quantity: 0.015, unit: L, notes: 'de oliva' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Manteca', quantity: 5, unit: G, notes: 'opcional' },
    ],
  },
  {
    title: 'Picante de pollo',
    description: 'Clásico peruano de pollo deshilachado en una salsa cremosa de ají amarillo, pan remojado en leche y especias.',
    servings: 4,
    prepTimeMinutes: 60,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico'],
    estimatedCostTotal: 5500,
    nutrition: { calories: 480, proteinG: 38, fatG: 22, carbsG: 32, fiberG: 3, sugarG: 6, sodiumMg: 560 },
    instructions: [
      'Cocinar las pechugas de pollo en agua con un trozo de cebolla, un diente de ajo y sal hasta que estén tiernas, unos 25-30 minutos.',
      'Mientras se cocina el pollo, remojar el pan en la leche hasta que se empape bien.',
      'Retirar el pollo, reservar el caldo, y deshilachar o cortar el pollo en trozos pequeños.',
      'En una olla, calentar el aceite y cocinar la cebolla picada hasta que esté transparente, unos 8 minutos. Agregar el ajo un minuto más.',
      'Incorporar la pasta de ají amarillo, el ají panca y el comino. Cocinar 5 minutos más, revolviendo.',
      'Licuar el sofrito con el pan remojado y media taza del caldo reservado hasta obtener una crema homogénea.',
      'Volver la salsa a la olla, agregar el pollo y mezclar bien.',
      'Cocinar todo junto 10 minutos a fuego bajo hasta que espese. Ajustar con más caldo si hace falta, y salpimentar.',
      'Servir con papas hervidas, zanahoria, perejil picado y arroz blanco.',
    ],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 0.6, unit: KG, notes: '4 pechugas' },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN, notes: 'roja, grande, picada' },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Ají amarillo', quantity: 60, unit: G, notes: 'pasta' },
      { ingredientName: 'Ají panca', quantity: 5, unit: G, notes: 'pasta, opcional' },
      { ingredientName: 'Comino', quantity: 2, unit: G },
      { ingredientName: 'Pan', quantity: 4, unit: UN, notes: 'de molde blanco, sin corteza' },
      { ingredientName: 'Leche', quantity: 0.125, unit: L, notes: 'evaporada o común' },
      { ingredientName: 'Caldo', quantity: 0.125, unit: L, notes: 'de pollo' },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 4, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Papa', quantity: 0.5, unit: KG, notes: 'hervidas en rodajas, opcional' },
      { ingredientName: 'Zanahoria', quantity: 0.2, unit: KG, notes: 'cocida en rodajas, opcional' },
      { ingredientName: 'Perejil', quantity: 5, unit: G },
      { ingredientName: 'Arroz', quantity: 0.3, unit: KG, notes: 'blanco, para acompañar' },
    ],
  },
  {
    title: 'Arroz con atún',
    description: 'Ensalada de arroz frío con atún, huevo duro, choclo, arvejas y morrón, ideal para el verano.',
    servings: 2,
    prepTimeMinutes: 25,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['proteico', 'economico'],
    estimatedCostTotal: 2800,
    nutrition: { calories: 380, proteinG: 22, fatG: 14, carbsG: 40, fiberG: 3, sugarG: 3, sodiumMg: 480 },
    instructions: [
      'Cocinar el arroz en agua con sal hasta que esté tierno y suelto. Escurrir y dejar entibiar (u omitir si ya está cocido).',
      'Cocinar los huevos en agua hirviendo 10 minutos, enfriar, pelar y picar.',
      'En un bol grande, mezclar el arroz cocido con el atún bien escurrido y desmenuzado.',
      'Agregar el choclo, las arvejas, el morrón picado y los huevos duros. Mezclar con suavidad.',
      'Sumar la mayonesa si se desea una versión más cremosa, o aceite de oliva y un toque de limón. Salpimentar y enfriar antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.1, unit: KG, notes: 'cocido, tipo largo fino' },
      { ingredientName: 'Atún', quantity: 120, unit: G, notes: 'al natural o en aceite' },
      { ingredientName: 'Huevo', quantity: 2, unit: UN, notes: 'duros' },
      { ingredientName: 'Choclo', quantity: 75, unit: G },
      { ingredientName: 'Arvejas', quantity: 75, unit: G, notes: 'cocidas' },
      { ingredientName: 'Morrón', quantity: 0.5, unit: UN, notes: 'rojo o verde, picado' },
      { ingredientName: 'Mayonesa', quantity: 30, unit: G, notes: 'opcional' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Limón', quantity: 0.5, unit: UN },
      { ingredientName: 'Aceite', quantity: 0.01, unit: L, notes: 'de oliva, opcional' },
    ],
  },
  {
    title: 'Pabellón criollo',
    description: 'Plato venezolano con carne mechada, caraotas negras, arroz blanco y tajadas de plátano frito.',
    servings: 4,
    prepTimeMinutes: 180,
    difficulty: RecipeDifficulty.HARD,
    dietTags: ['proteico'],
    estimatedCostTotal: 7000,
    nutrition: { calories: 720, proteinG: 40, fatG: 28, carbsG: 75, fiberG: 10, sugarG: 8, sodiumMg: 520 },
    instructions: [
      'Hervir la carne con sal y laurel durante 1 a 2 horas, hasta que esté bien tierna. Desmechar.',
      'Preparar un sofrito con cebolla, ajo y morrón; cuando la cebolla esté transparente, agregar el tomate picado.',
      'Incorporar la carne desmechada al sofrito, condimentar con comino, sal y pimienta, y agregar un poco del caldo de cocción si hace falta jugosidad. Reservar.',
      'Cocinar los porotos negros (remojados desde la noche anterior) hasta que estén tiernos, alrededor de 45 minutos a 1 hora. Saltear con un sofrito aparte de cebolla, ajo y morrón, y el azúcar. Condimentar y cocinar unos minutos más.',
      'Hervir el arroz con sal y agua hasta que esté cocido y suelto. Dejar reposar 5 minutos tapado.',
      'Cortar los plátanos maduros en rodajas al bies y freírlos en aceite caliente hasta que estén dorados. Escurrir sobre papel absorbente.',
      'Servir el arroz, la carne mechada, los porotos negros y las tajadas en sectores separados del plato.',
    ],
    ingredients: [
      { ingredientName: 'Carne (bife)', quantity: 0.6, unit: KG, notes: 'para mechar: falda o matambre' },
      { ingredientName: 'Cebolla', quantity: 1.5, unit: UN },
      { ingredientName: 'Morrón', quantity: 1.5, unit: UN },
      { ingredientName: 'Ajo', quantity: 3, unit: UN },
      { ingredientName: 'Tomate', quantity: 2, unit: UN, notes: 'perita' },
      { ingredientName: 'Comino', quantity: 2, unit: G },
      { ingredientName: 'Sal', quantity: 6, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Aceite', quantity: 0.04, unit: L },
      { ingredientName: 'Porotos negros', quantity: 0.25, unit: KG, notes: 'caraotas, remojados desde la noche anterior' },
      { ingredientName: 'Azúcar', quantity: 5, unit: G },
      { ingredientName: 'Arroz', quantity: 0.2, unit: KG, notes: 'blanco' },
      { ingredientName: 'Banana', quantity: 2, unit: UN, notes: 'bien maduras (plátano), para freír' },
    ],
  },
  {
    title: 'Paella de pollo',
    description: 'Paella clásica de pollo con pimiento rojo, tomate y azafrán, con su socarrat en la base.',
    servings: 4,
    prepTimeMinutes: 60,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico'],
    estimatedCostTotal: 5500,
    nutrition: { calories: 520, proteinG: 32, fatG: 18, carbsG: 58, fiberG: 4, sugarG: 4, sodiumMg: 540 },
    instructions: [
      'Calentar aceite de oliva en una paellera y dorar los trozos de pollo por todos lados, a fuego medio-alto.',
      'Agregar el pimiento en tiras y las judías verdes si se usan. Sofreír 5 minutos y añadir el ajo picado los últimos 2 minutos.',
      'Rallar los tomates e incorporarlos. Cocinar hasta que se evapore el líquido y quede un sofrito espeso.',
      'Añadir el pimentón dulce y el azafrán, remover fuera del fuego para que no se quemen, y devolver al fuego.',
      'Verter el arroz y mezclar con el sofrito 1 a 2 minutos, hasta que los granos estén transparentes.',
      'Incorporar el caldo caliente, distribuir el arroz parejo y salpimentar. No remover más desde este punto.',
      'Cocinar a fuego medio-alto 10 minutos, luego a fuego medio-bajo 8 minutos más, hasta que el arroz esté tierno y el líquido se haya absorbido.',
      'Subir el fuego 1 a 2 minutos al final para formar el socarrat, sin dejar que se queme.',
      'Apagar, cubrir con un paño y dejar reposar 5 a 10 minutos antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.3, unit: KG, notes: 'bomba' },
      { ingredientName: 'Caldo', quantity: 0.7, unit: L, notes: 'de pollo, caliente' },
      { ingredientName: 'Pollo (pechuga)', quantity: 0.6, unit: KG, notes: 'muslos o contramuslos, troceados' },
      { ingredientName: 'Morrón', quantity: 1, unit: UN, notes: 'rojo' },
      { ingredientName: 'Chauchas', quantity: 0.1, unit: KG, notes: 'opcional' },
      { ingredientName: 'Tomate', quantity: 2, unit: UN, notes: 'maduros' },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Pimentón dulce', quantity: 2, unit: G },
      { ingredientName: 'Azafrán', quantity: 1, unit: G, notes: 'unas hebras' },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 4, unit: G, notes: 'y pimienta a gusto' },
    ],
  },
  {
    title: 'Arroz con bacalao',
    description: 'Arroz caldoso con bacalao desalado, pimiento, tomate y azafrán, al estilo de la cocina española.',
    servings: 4,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico'],
    estimatedCostTotal: 6000,
    nutrition: { calories: 420, proteinG: 26, fatG: 12, carbsG: 55, fiberG: 3, sugarG: 3, sodiumMg: 620 },
    instructions: [
      'Picar la cebolla, el pimiento y los ajos. Sofreír en aceite de oliva a fuego medio 8-10 minutos, hasta que estén bien tiernos.',
      'Añadir el tomate rallado, el pimentón dulce y el laurel. Cocinar 5 minutos más.',
      'Incorporar el arroz y rehogar 2 minutos para que se impregne del sofrito.',
      'Agregar el caldo caliente y no remover más. Cocinar a fuego medio.',
      'A mitad de cocción, unos 10 minutos, incorporar el bacalao y el azafrán infusionado en un poco de caldo. Ajustar la sal con cuidado.',
      'Cocinar hasta que el arroz esté en su punto y el caldo casi se haya absorbido, unos 18 minutos en total. Dejar reposar 5 minutos tapado.',
      'Servir con un chorrito de aceite de oliva y perejil picado por encima.',
    ],
    ingredients: [
      { ingredientName: 'Bacalao', quantity: 0.3, unit: KG, notes: 'desalado, en migas o trozos' },
      { ingredientName: 'Arroz', quantity: 0.3, unit: KG, notes: 'bomba' },
      { ingredientName: 'Cebolla', quantity: 1, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN, notes: 'rojo' },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Tomate', quantity: 2, unit: UN, notes: 'maduros' },
      { ingredientName: 'Pimentón dulce', quantity: 2, unit: G },
      { ingredientName: 'Azafrán', quantity: 1, unit: G, notes: 'opcional' },
      { ingredientName: 'Caldo', quantity: 1, unit: L, notes: 'de pescado o vegetal' },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L },
      { ingredientName: 'Sal', quantity: 4, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Perejil', quantity: 5, unit: G, notes: 'opcional' },
    ],
  },
  {
    title: 'Arroz pilaf',
    description: 'Guarnición clásica de arroz suelto y dorado, salteado con manteca, cebolla y ajo antes de cocinarse en caldo.',
    servings: 4,
    prepTimeMinutes: 35,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'economico'],
    estimatedCostTotal: 2200,
    nutrition: { calories: 320, proteinG: 6, fatG: 9, carbsG: 54, fiberG: 2, sugarG: 2, sodiumMg: 380 },
    instructions: [
      'En una sartén o cacerola, derretir la manteca con el aceite (así la manteca no se quema).',
      'Agregar la cebolla y el ajo picados, y cocinar a fuego medio hasta que estén transparentes.',
      'Incorporar el arroz y tostarlo unos minutos hasta que tome un color dorado.',
      'Añadir el caldo caliente, sal y pimienta.',
      'Tapar, bajar el fuego y cocinar 12 a 15 minutos sin destapar.',
      'Apagar el fuego y dejar reposar tapado 10 minutos más.',
      'Esponjar con un tenedor y servir con perejil picado por encima y frutos secos, o como guarnición de otros platos.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.25, unit: KG, notes: 'basmati o largo fino' },
      { ingredientName: 'Caldo', quantity: 0.5, unit: L, notes: 'de verduras o pollo' },
      { ingredientName: 'Manteca', quantity: 15, unit: G },
      { ingredientName: 'Aceite', quantity: 0.015, unit: L, notes: 'de oliva' },
      { ingredientName: 'Cebolla', quantity: 0.5, unit: UN, notes: 'picada' },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'picado' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Perejil', quantity: 5, unit: G, notes: 'picado, opcional' },
      { ingredientName: 'Almendras', quantity: 20, unit: G, notes: 'u otros frutos secos, opcional' },
      { ingredientName: 'Pasas de uva', quantity: 15, unit: G, notes: 'opcional' },
    ],
  },
  {
    title: 'Sushi balls',
    description: 'Bolitas de arroz de sushi avinagrado rellenas y decoradas con salmón, palta, camarones y pepino, al estilo temari.',
    servings: 4,
    prepTimeMinutes: 120,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico'],
    estimatedCostTotal: 7500,
    nutrition: { calories: 340, proteinG: 18, fatG: 8, carbsG: 48, fiberG: 2, sugarG: 9, sodiumMg: 480 },
    instructions: [
      'Lavar el arroz en un colador hasta que el agua salga limpia. Dejarlo escurrir 30 minutos.',
      'Cocinar el arroz con el agua: llevar a hervor, bajar a fuego mínimo y cocinar 13 minutos. Apagar, tapar y dejar reposar 10 minutos más.',
      'Disolver el vinagre de arroz con el azúcar y la sal. Rociar sobre el arroz y mezclarlo con cuchara, abanicándolo para que se enfríe.',
      'Sobre papel film, colocar una cucharada de arroz, poner en el centro un trocito de mango, envolver con el film y enrollar como un caramelo hasta formar la bolita.',
      'Para decorar y rellenar, alternar los ingredientes (salmón, camarones, palta, pepino, cebolla de verdeo) con el alga nori y el arroz, dando forma con el film para que compacten bien.',
      'Servir con salsa de soja y el queso crema aparte.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.2, unit: KG, notes: 'para sushi o doble carolina' },
      { ingredientName: 'Agua', quantity: 0.2, unit: L },
      { ingredientName: 'Vinagre de arroz', quantity: 0.06, unit: L, notes: 'o vinagre blanco o de alcohol' },
      { ingredientName: 'Azúcar', quantity: 25, unit: G },
      { ingredientName: 'Sal', quantity: 2, unit: G, notes: 'una pizca' },
      { ingredientName: 'Mango', quantity: 1, unit: UN },
      { ingredientName: 'Alga nori', quantity: 2, unit: G, notes: '1 o 2 hojas' },
      { ingredientName: 'Salmón', quantity: 150, unit: G, notes: 'rosado, fileteado en trozos pequeños' },
      { ingredientName: 'Palta', quantity: 1, unit: UN },
      { ingredientName: 'Cebolla de verdeo', quantity: 2, unit: UN, notes: 'la parte verde' },
      { ingredientName: 'Pepino', quantity: 0.5, unit: UN },
      { ingredientName: 'Camarones', quantity: 100, unit: G, notes: '2 o 3 camarones' },
      { ingredientName: 'Queso crema', quantity: 80, unit: G, notes: 'tipo Filadelfia' },
      { ingredientName: 'Salsa de soja', quantity: 0.05, unit: L, notes: 'para servir' },
    ],
  },
  {
    title: 'Chow fan de pollo',
    description: 'Arroz frito chino con pollo, huevo revuelto y vegetales salteados a fuego fuerte, con un toque de sésamo.',
    servings: 4,
    prepTimeMinutes: 30,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['proteico'],
    estimatedCostTotal: 5000,
    nutrition: { calories: 420, proteinG: 30, fatG: 14, carbsG: 42, fiberG: 2, sugarG: 3, sodiumMg: 620 },
    instructions: [
      'Calentar un wok con un poco de aceite neutro. Saltear los cubos de pollo con una pizca de sal hasta dorar. Retirar y reservar.',
      'En el mismo wok, saltear el ajo, la zanahoria y el morrón hasta que estén tiernos pero crocantes. Empujarlos hacia un costado.',
      'Romper los huevos en el centro del wok y revolver rápido hasta formar un revuelto.',
      'Incorporar el arroz frío, el pollo reservado, la salsa de soja y el aceite de sésamo. Cocinar 4-5 minutos revolviendo constantemente.',
      'Apagar el fuego, agregar la mitad de la cebolla de verdeo y mezclar.',
      'Servir caliente decorado con el resto de la cebolla de verdeo.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.45, unit: KG, notes: 'cocido grano largo, preferentemente del día anterior' },
      { ingredientName: 'Pollo (pechuga)', quantity: 0.4, unit: KG, notes: 'en cubos' },
      { ingredientName: 'Zanahoria', quantity: 0.1, unit: KG, notes: 'en tiras finas' },
      { ingredientName: 'Morrón', quantity: 0.5, unit: UN, notes: 'rojo, en cubos' },
      { ingredientName: 'Huevo', quantity: 3, unit: UN },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'picados' },
      { ingredientName: 'Salsa de soja', quantity: 0.045, unit: L },
      { ingredientName: 'Aceite de sésamo', quantity: 0.015, unit: L },
      { ingredientName: 'Cebolla de verdeo', quantity: 2, unit: UN, notes: 'picadas, para decorar' },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L, notes: 'neutro, para saltear' },
      { ingredientName: 'Sal', quantity: 2, unit: G, notes: 'pizca' },
    ],
  },
  {
    title: 'Bibimbap coreano',
    description: 'Bowl coreano de arroz con vegetales salteados por separado, tiras de ternera, huevo y gochujang, todo mezclado al servir.',
    servings: 4,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico'],
    estimatedCostTotal: 6500,
    nutrition: { calories: 560, proteinG: 32, fatG: 22, carbsG: 58, fiberG: 6, sugarG: 6, sodiumMg: 680 },
    instructions: [
      'Enjuagar el arroz varias veces y cocinarlo con agua (proporción 1:1.2) hasta que esté tierno. Reservar caliente.',
      'Saltear cada vegetal (zanahoria, zapallito, morrón y espinaca) por separado con una pizca de sal y unas gotas de aceite de sésamo, 2-3 minutos cada uno.',
      'Mezclar las tiras de ternera con salsa de soja, ajo picado y aceite de sésamo. Dejar reposar 10 minutos y cocinar 5-7 minutos en sartén caliente.',
      'Cocinar los huevos con la yema líquida, 1 a 5 minutos.',
      'En un bowl, colocar el arroz como base, disponer los vegetales, la carne y el huevo encima, y agregar una cucharada de gochujang en el centro.',
      'Justo antes de comer, mezclar todo integrando bien el gochujang. Decorar con semillas de sésamo.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.36, unit: KG, notes: 'blanco de grano corto (glutinoso)' },
      { ingredientName: 'Carne (bife)', quantity: 0.2, unit: KG, notes: 'de ternera, en tiras' },
      { ingredientName: 'Zanahoria', quantity: 0.15, unit: KG, notes: 'en juliana' },
      { ingredientName: 'Zapallito', quantity: 1, unit: UN, notes: 'calabacín, en tiras finas' },
      { ingredientName: 'Morrón', quantity: 1, unit: UN, notes: 'rojo, en tiras, opcional' },
      { ingredientName: 'Espinaca', quantity: 100, unit: G, notes: '1 paquete' },
      { ingredientName: 'Huevo', quantity: 4, unit: UN, notes: 'uno por persona' },
      { ingredientName: 'Aceite de sésamo', quantity: 0.03, unit: L },
      { ingredientName: 'Salsa de soja', quantity: 0.03, unit: L },
      { ingredientName: 'Gochujang', quantity: 30, unit: G, notes: 'pasta de chile rojo coreano' },
      { ingredientName: 'Ajo', quantity: 1, unit: UN, notes: 'picado' },
      { ingredientName: 'Sal', quantity: 3, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Semillas de sésamo', quantity: 5, unit: G, notes: 'para decorar, opcional' },
    ],
  },
  {
    title: 'Dosas de arroz y lentejas fermentadas',
    description: 'Crepes indios fermentados de arroz integral y lentejas, crocantes por fuera, sin gluten. Requiere 2-3 días de remojo y fermentación.',
    servings: 4,
    prepTimeMinutes: 30,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['vegano', 'vegetariano', 'sin_tacc', 'economico'],
    estimatedCostTotal: 2000,
    nutrition: { calories: 260, proteinG: 9, fatG: 3, carbsG: 48, fiberG: 5, sugarG: 1, sodiumMg: 300 },
    instructions: [
      'Día 1: lavar el arroz y cubrirlo con el doble de agua sin cloro. En otro bol, cubrir las lentejas generosamente con agua sin cloro. Agregar el fenogreco al arroz si se usa. Tapar y dejar reposar 12-24 horas.',
      'Día 2: escurrir el arroz y las lentejas sin enjuagar. Licuar el arroz con muy poca agua hasta lograr una textura cremosa tipo masa de crepes. Licuar las lentejas igual y unir ambas mezclas. Agregar sal, tapar y dejar fermentar otras 12-24 horas.',
      'Día 3: agregar un poco de agua si la mezcla fermentada está muy espesa, hasta lograr una textura fluida pero no líquida.',
      'Calentar bien una sartén antiadherente a fuego medio-alto. Verter un poco de mezcla en el centro y extenderla rápido en capa fina.',
      'Cocinar hasta que los bordes doren, dar vuelta con cuidado y servir con los acompañamientos que se prefieran.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.4, unit: KG, notes: 'integral tipo yamaní (o basmati/blanco), para remojar y licuar' },
      { ingredientName: 'Lentejas', quantity: 100, unit: G, notes: 'rojas peladas, para remojar y licuar' },
      { ingredientName: 'Fenogreco', quantity: 5, unit: G, notes: 'opcional' },
      { ingredientName: 'Agua', quantity: 0.6, unit: L, notes: 'sin cloro, mineral o filtrada' },
      { ingredientName: 'Sal', quantity: 4, unit: G },
    ],
  },
  {
    title: 'Arancini siciliano',
    description: 'Bolitas de risotto rebozadas y fritas, rellenas de mozzarella y ragú, crocantes por fuera y cremosas por dentro.',
    servings: 4,
    prepTimeMinutes: 40,
    difficulty: RecipeDifficulty.HARD,
    dietTags: ['vegetariano'],
    estimatedCostTotal: 6000,
    nutrition: { calories: 480, proteinG: 16, fatG: 20, carbsG: 58, fiberG: 2, sugarG: 2, sodiumMg: 620 },
    instructions: [
      'Calentar aceite en una cacerola y agregar el arroz, revolviendo hasta que se ponga transparente. Incorporar el vino blanco y cocinar hasta que se evapore el alcohol.',
      'Agregar el caldo de a poco, un cucharón a la vez, removiendo constantemente y dejando que el arroz lo absorba antes de sumar más. Cocinar unos 20 minutos hasta que esté cremoso.',
      'Agregar la manteca y el parmesano rallado, integrar y dejar enfriar hasta temperatura ambiente (o refrigerar unas horas).',
      'Con el risotto frío, agregar la albahaca picada si se usa. Humedecerse las manos, tomar una porción, formar una bola y rellenar con ragú y/o mozzarella en el centro.',
      'Cerrar bien la bola cuidando que el relleno quede en el centro. Pasar por harina, luego por huevo batido y finalmente por pan rallado.',
      'Freír en abundante aceite caliente hasta que estén doradas y crocantes. Escurrir sobre papel absorbente.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.5, unit: KG, notes: 'arbóreo o bomba, para risotto' },
      { ingredientName: 'Vino blanco', quantity: 0.1, unit: L },
      { ingredientName: 'Caldo', quantity: 1, unit: L, notes: 'de pollo o verduras' },
      { ingredientName: 'Manteca', quantity: 50, unit: G },
      { ingredientName: 'Queso', quantity: 100, unit: G, notes: 'parmesano rallado' },
      { ingredientName: 'Mozzarella', quantity: 150, unit: G, notes: 'en cubos' },
      { ingredientName: 'Carne picada', quantity: 200, unit: G, notes: 'en salsa de tomate (ragú), opcional' },
      { ingredientName: 'Albahaca', quantity: 5, unit: G, notes: 'picada, opcional' },
      { ingredientName: 'Huevo', quantity: 2, unit: UN },
      { ingredientName: 'Pan rallado', quantity: 100, unit: G, notes: 'para rebozar' },
      { ingredientName: 'Harina', quantity: 50, unit: G },
      { ingredientName: 'Aceite', quantity: 0.3, unit: L, notes: 'para freír' },
    ],
  },
  {
    title: 'Arroz rojo',
    description: 'Arroz mexicano salteado y cocido en salsa de tomate, cebolla y ajo, como guarnición de todos los días.',
    servings: 4,
    prepTimeMinutes: 30,
    difficulty: RecipeDifficulty.EASY,
    dietTags: ['vegetariano', 'economico'],
    estimatedCostTotal: 1800,
    nutrition: { calories: 260, proteinG: 5, fatG: 6, carbsG: 46, fiberG: 2, sugarG: 3, sodiumMg: 320 },
    instructions: [
      'Enjuagar el arroz bajo el chorro de agua hasta que salga clara.',
      'En una sartén con un poco de aceite, saltear el arroz a fuego medio hasta que esté ligeramente dorado, revolviendo constantemente.',
      'Licuar los tomates con la cebolla y el ajo, agregando un poco de agua si hace falta. Colar la mezcla.',
      'Verter la salsa colada sobre el arroz dorado y cocinar 3-5 minutos, removiendo, hasta que se absorba parcialmente.',
      'Añadir el caldo caliente y sal. Mezclar bien.',
      'Tapar y cocinar a fuego bajo 15-20 minutos sin destapar, hasta que se absorba el líquido.',
      'Retirar del fuego y dejar reposar tapado 5 minutos antes de servir.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.25, unit: KG, notes: 'blanco' },
      { ingredientName: 'Tomate', quantity: 2, unit: UN, notes: 'maduros, medianos' },
      { ingredientName: 'Cebolla', quantity: 0.25, unit: UN },
      { ingredientName: 'Ajo', quantity: 1, unit: UN },
      { ingredientName: 'Caldo', quantity: 0.5, unit: L, notes: 'de pollo o agua' },
      { ingredientName: 'Aceite', quantity: 0.02, unit: L, notes: 'para freír' },
      { ingredientName: 'Sal', quantity: 3, unit: G },
    ],
  },
  {
    title: 'Morisqueta de Michoacán',
    description: 'Arroz blanco michoacano servido con frijoles y una salsa de jitomate asado, con chorizo y queso fresco opcionales.',
    servings: 4,
    prepTimeMinutes: 45,
    difficulty: RecipeDifficulty.MEDIUM,
    dietTags: ['proteico', 'economico'],
    estimatedCostTotal: 3500,
    nutrition: { calories: 420, proteinG: 16, fatG: 12, carbsG: 58, fiberG: 8, sugarG: 3, sodiumMg: 480 },
    instructions: [
      'Enjuagar el arroz hasta que el agua salga clara. Hervir agua, agregar el arroz con una pizca de sal, tapar y cocinar 10-12 minutos. Apagar y dejar reposar 15 minutos.',
      'Si los frijoles se cocinaron desde cero, reservarlos con un poco de su caldo. Si son de lata, calentarlos con un chorrito de agua o caldo.',
      'Asar los jitomates, la cebolla, el ajo y el chile hasta que estén dorados. Licuar todo con un poco de agua hasta obtener una salsa homogénea. Reservar.',
      'Si se usa chorizo, saltearlo unos minutos en la misma sartén, sin piel y en trozos pequeños.',
      'Servir el arroz en platos hondos, agregar los frijoles encima, el chorizo y bañar con la salsa.',
      'Decorar con cilantro fresco y trozos de queso.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.3, unit: KG, notes: 'blanco' },
      { ingredientName: 'Porotos negros', quantity: 0.3, unit: KG, notes: 'o frijoles pintos, cocidos, con su caldo' },
      { ingredientName: 'Tomate', quantity: 3, unit: UN, notes: 'jitomates, para asar' },
      { ingredientName: 'Cebolla', quantity: 0.5, unit: UN, notes: 'para asar' },
      { ingredientName: 'Ajo', quantity: 2, unit: UN, notes: 'para asar' },
      { ingredientName: 'Chile verde', quantity: 1, unit: UN, notes: 'para asar, al gusto' },
      { ingredientName: 'Cilantro', quantity: 10, unit: G, notes: 'fresco, para decorar' },
      { ingredientName: 'Queso crema', quantity: 60, unit: G, notes: 'fresco desmoronado o crema, opcional' },
      { ingredientName: 'Chorizo', quantity: 1, unit: UN, notes: 'sin piel, en trozos, opcional' },
      { ingredientName: 'Sal', quantity: 4, unit: G, notes: 'a gusto' },
    ],
  },
  {
    title: 'Paella mixta',
    description: 'Paella de mar y tierra con pollo, cerdo, calamares, langostinos y mejillones sobre arroz bomba con azafrán.',
    servings: 4,
    prepTimeMinutes: 105,
    difficulty: RecipeDifficulty.HARD,
    dietTags: ['proteico'],
    estimatedCostTotal: 11000,
    nutrition: { calories: 680, proteinG: 48, fatG: 26, carbsG: 60, fiberG: 4, sugarG: 3, sodiumMg: 780 },
    instructions: [
      'Cortar el pollo y el cerdo en trozos pequeños y uniformes. Limpiar los calamares y cortarlos en anillas junto con sus tentáculos. Lavar bien los mejillones.',
      'En una paellera amplia, calentar aceite de oliva a fuego medio-alto. Sellar el pollo hasta dorar (6-8 minutos), retirar y reservar. Hacer lo mismo con el cerdo.',
      'En la misma paellera, dorar ligeramente los calamares 2-3 minutos. Añadir los camarones y los mejillones, cocinar hasta que los mejillones se abran. Retirar los mariscos y reservar.',
      'Sofreír el ajo picado y el morrón cortado en tiras. Agregar el tomate rallado y cocinar a fuego medio-bajo 5-7 minutos hasta que espese.',
      'Incorporar el arroz y rehogar en el sofrito unos minutos hasta que esté nacarado. Devolver el pollo, el cerdo y los calamares a la paellera y mezclar suavemente.',
      'Tostar el azafrán en una sartén pequeña 20-30 segundos y disolverlo en un poco de caldo caliente.',
      'Añadir el caldo a la paellera (3 partes de caldo por cada parte de arroz). Llevar a hervor y cocinar a fuego alto 9-10 minutos, luego bajar el fuego y cocinar 7-8 minutos más sin remover.',
      'Blanquear las arvejas en agua con sal 2 minutos y escurrir. En los últimos 2-3 minutos de cocción del arroz, colocar los camarones y mejillones reservados encima.',
      'Cuando la paella esté lista, esparcir las arvejas por encima. Tapar y dejar reposar 5 minutos. Servir con rodajas de limón.',
    ],
    ingredients: [
      { ingredientName: 'Pollo (pechuga)', quantity: 0.5, unit: KG, notes: 'medio pollo troceado' },
      { ingredientName: 'Cerdo (magro)', quantity: 0.2, unit: KG, notes: 'en trozos pequeños' },
      { ingredientName: 'Calamares', quantity: 0.2, unit: KG, notes: '2 calamares limpios, en anillas' },
      { ingredientName: 'Camarones', quantity: 0.25, unit: KG, notes: '8 langostinos' },
      { ingredientName: 'Mejillones', quantity: 0.2, unit: KG, notes: '8 unidades, limpios' },
      { ingredientName: 'Tomate', quantity: 3, unit: UN, notes: 'o salsa de tomate' },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Morrón', quantity: 1, unit: UN, notes: 'verde' },
      { ingredientName: 'Arroz', quantity: 0.25, unit: KG, notes: 'bomba' },
      { ingredientName: 'Caldo', quantity: 0.75, unit: L, notes: 'o agua' },
      { ingredientName: 'Azafrán', quantity: 1, unit: G, notes: 'unas hebras' },
      { ingredientName: 'Arvejas', quantity: 100, unit: G, notes: 'frescas' },
      { ingredientName: 'Limón', quantity: 1, unit: UN, notes: 'en rodajas, para servir' },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L, notes: 'de oliva' },
      { ingredientName: 'Sal', quantity: 5, unit: G, notes: 'y pimienta a gusto' },
    ],
  },
  {
    title: 'Arroz del Senyoret',
    description: 'Arroz de mariscos valenciano ya limpio y pelado, con calamar, sepia y gambas, pensado para comer sin trabajo.',
    servings: 4,
    prepTimeMinutes: 90,
    difficulty: RecipeDifficulty.HARD,
    dietTags: ['proteico'],
    estimatedCostTotal: 9500,
    nutrition: { calories: 560, proteinG: 38, fatG: 18, carbsG: 58, fiberG: 3, sugarG: 3, sodiumMg: 720 },
    instructions: [
      'Calentar aceite de oliva en una paellera. Sofreír la cebolla y el ajo picados hasta que estén transparentes y dorados, 5-7 minutos.',
      'Incorporar el morrón cortado en trozos pequeños y cocinar unos minutos. Agregar el pimentón dulce y luego el tomate rallado. Cocinar a fuego lento hasta que el sofrito esté concentrado, 10-15 minutos.',
      'Añadir el arroz y cocinar 1-2 minutos, removiendo para que se impregne del sofrito. Incorporar el azafrán y salpimentar.',
      'Verter el caldo de pescado hirviendo cubriendo todo. Desde aquí no volver a remover el arroz, para que se forme el socarrat en el fondo. Cocinar a fuego medio-alto 18-20 minutos en total.',
      'A los 8-10 minutos de cocción, añadir los calamares y la sepia. Un par de minutos después, agregar los camarones pelados.',
      'Cuando el fumet se haya evaporado casi por completo, retirar del fuego, tapar con un paño y dejar reposar 5 minutos.',
      'Servir decorado con perejil fresco y rodajas de limón.',
    ],
    ingredients: [
      { ingredientName: 'Arroz', quantity: 0.4, unit: KG, notes: 'bomba' },
      { ingredientName: 'Caldo', quantity: 1, unit: L, notes: 'de pescado (fumet), caliente' },
      { ingredientName: 'Camarones', quantity: 0.2, unit: KG, notes: 'gambas peladas' },
      { ingredientName: 'Calamares', quantity: 0.2, unit: KG, notes: 'limpios y cortados en anillos' },
      { ingredientName: 'Sepia', quantity: 100, unit: G, notes: 'troceada' },
      { ingredientName: 'Tomate', quantity: 2, unit: UN, notes: 'maduros, rallados' },
      { ingredientName: 'Cebolla', quantity: 0.5, unit: UN, notes: 'opcional' },
      { ingredientName: 'Ajo', quantity: 2, unit: UN },
      { ingredientName: 'Morrón', quantity: 2, unit: UN, notes: 'uno verde, uno rojo' },
      { ingredientName: 'Pimentón dulce', quantity: 2, unit: G, notes: 'o ñora hidratada y picada' },
      { ingredientName: 'Azafrán', quantity: 1, unit: G, notes: 'unas hebras' },
      { ingredientName: 'Aceite', quantity: 0.03, unit: L, notes: 'de oliva virgen extra' },
      { ingredientName: 'Sal', quantity: 4, unit: G, notes: 'y pimienta a gusto' },
      { ingredientName: 'Perejil', quantity: 5, unit: G, notes: 'fresco, para decorar' },
      { ingredientName: 'Limón', quantity: 1, unit: UN, notes: 'opcional, para servir' },
    ],
  },
];

async function run() {
  const dataSource = new DataSource({
    type: 'postgres',
    host: process.env.DB_HOST,
    port: Number(process.env.DB_PORT ?? 5432),
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    ssl: process.env.DB_SSL === 'true' ? { rejectUnauthorized: false } : false,
    entities: [path.join(__dirname, '../../modules/**/*.entity.{ts,js}')],
  });

  await dataSource.initialize();
  const ingredientsRepository = dataSource.getRepository(Ingredient);
  const recipesRepository = dataSource.getRepository(Recipe);

  let created = 0;
  let skipped = 0;

  for (const seed of seedRecipes) {
    const existing = await recipesRepository.findOne({
      where: { title: seed.title },
    });
    if (existing) {
      // no se recrea, pero sí se sincronizan dietTags e imageUrl con lo que diga el seed
      // (incluso a null), para poder limpiar fotos incorrectas de instalaciones previas.
      existing.dietTags = seed.dietTags;
      existing.imageUrl = seed.imageUrl ?? null;
      await recipesRepository.save(existing);
      skipped++;
      continue;
    }

    const recipeIngredients = [];
    for (const ing of seed.ingredients) {
      const ingredient = await ingredientsRepository.findOne({
        where: { name: ILike(ing.ingredientName) },
      });
      if (!ingredient) {
        throw new Error(
          `Ingrediente "${ing.ingredientName}" no encontrado — corré primero el seed de ingredientes.`,
        );
      }
      recipeIngredients.push({
        ingredientId: ingredient.id,
        quantity: ing.quantity,
        unit: ing.unit,
        notes: ing.notes ?? null,
      });
    }

    const recipe = recipesRepository.create({
      title: seed.title,
      imageUrl: seed.imageUrl ?? null,
      description: seed.description,
      instructions: seed.instructions.map((instruction, index) => ({
        order: index + 1,
        instruction,
      })),
      servings: seed.servings,
      prepTimeMinutes: seed.prepTimeMinutes,
      difficulty: seed.difficulty,
      estimatedCostTotal: seed.estimatedCostTotal,
      dietTags: seed.dietTags,
      isAiGenerated: false,
      createdByUserId: null,
      nutrition: seed.nutrition,
      recipeIngredients,
    });
    await recipesRepository.save(recipe);
    created++;
  }

  console.log(`Seed de recetas: ${created} creadas, ${skipped} ya existían.`);
  await dataSource.destroy();
}

run().catch((error) => {
  console.error('Error corriendo el seed:', error);
  process.exit(1);
});
