const String _base = 'https://chef-ai-shinra.onrender.com/images/recipe-images';

/// Mapa de título de receta → URL remota en IDrive e2.
/// Las imágenes se sirven desde la nube; el APK no las incluye.
const Map<String, String> kRecipeImageUrls = {
  'Milanesas de pollo con puré de papas': '$_base/milanesas-pollo-pure-papas.jpg',
  'Tortilla de papas y huevo': '$_base/tortilla-papas-huevo.jpg',
  'Arroz con pollo': '$_base/arroz-con-pollo.jpg',
  'Ensalada de lentejas': '$_base/ensalada-lentejas.jpg',
  'Tarta de verduras': '$_base/tarta-verduras.jpg',
  'Fideos con salsa de tomate y ajo': '$_base/fideos-tomate-ajo.jpg',
  'Ensalada César simple': '$_base/ensalada-cesar.jpg',
  'Guiso de lentejas con carne': '$_base/guiso-lentejas-carne.jpg',
  'Pescado al horno con papas y zanahoria': '$_base/pescado-horno-papas-zanahoria.jpg',
  'Ensalada mixta de verduras': '$_base/ensalada-mixta-verduras.jpg',
  'Sopa de zanahoria': '$_base/sopa-zanahoria.jpg',
  'Panqueques caseros': '$_base/panqueques-caseros.jpg',
  'Sandwich de pollo y vegetales': '$_base/sandwich-pollo-vegetales.jpg',
  'Ensalada de frutas con yogur': '$_base/ensalada-frutas-yogur.jpg',
  'Omelette de queso': '$_base/omelette-queso.jpg',
  'Arroz con verduras salteadas': '$_base/arroz-verduras-salteadas.jpg',
  'Energy balls crudas de dátil y cacao': '$_base/energy-balls-datil-cacao.jpg',
  'Leche de almendras casera': '$_base/leche-almendras.jpg',
  'Ensalada crudivegana de zanahoria, manzana y limón': '$_base/ensalada-crudivegana-zanahoria-manzana-limon.jpg',
  'Helado crudo de banana y cacao': '$_base/helado-banana-cacao.jpg',
  'Granola cruda de avena y semillas': '$_base/granola-avena-semillas.jpg',
  'Bowl crudo de manzana, chía y limón': '$_base/bowl-manzana-chia-limon.jpg',
  'Pollo a la mostaza': '$_base/pollo-mostaza.jpg',
  'Pollo al curry': '$_base/pollo-curry.jpg',
  'Pizza de pollo': '$_base/pizza-pollo.jpg',
  'Pollo al limón y ajo': '$_base/pollo-limon-ajo.jpg',
  'Pollo crocante con yogur y semillas': '$_base/pollo-crocante-yogur-semillas.jpg',
  'Milanesas de berenjena al horno': '$_base/milanesas-berenjena.jpg',
  'Guacamole casero': '$_base/guacamole.jpg',
  'Ensalada de garbanzos con verduras': '$_base/ensalada-garbanzos.jpg',
  'Tarta de atún y verduras': '$_base/tarta-atun-verduras.jpg',
  'Batatas al horno con especias': '$_base/batatas-horno-especias.jpg',
  'Crema de calabaza': '$_base/crema-calabaza.jpg',
  'Buñuelos de acelga': '$_base/bunuelos-acelga.jpg',
  'Bife a la plancha con batatas al horno': '$_base/bife-plancha-batatas.jpg',
  'Bowl de yogur, granola y banana': '$_base/bowl-yogur-granola-banana.jpg',
  'Wrap de pollo, palta y vegetales': '$_base/wrap-pollo-palta.jpg',
  'Bowl de atún, huevo y almendras': '$_base/bowl-atun-huevo-almendras.jpg',
  'Tostadas de atún, huevo y queso': '$_base/tostadas-atun-huevo-queso.jpg',
  'Ensalada de brócoli y coliflor con queso': '$_base/ensalada-brocoli-coliflor-queso.jpg',
  'Bife con brócoli y batatas al horno': '$_base/bife-brocoli-batatas.jpg',
  'Sándwich de pepino y pollo': '$_base/sandwich-pepino-pollo.jpg',
  'Arroz con setas meloso': '$_base/arroz-setas-meloso.jpg',
  'Paella de carne': '$_base/paella-carne.jpg',
  'Pan con psyllium': '$_base/pan-psyllium.jpg',
  'Cuscús base: cómo se cocina': '$_base/cuscus-base.jpg',
  'Picante de pollo': '$_base/picante-pollo.jpg',
  'Arroz con atún': '$_base/arroz-atun.jpg',
  'Pabellón criollo': '$_base/pabellon-criollo.jpg',
  'Paella de pollo': '$_base/paella-pollo.jpg',
  'Arroz con bacalao': '$_base/arroz-bacalao.jpg',
  'Arroz pilaf': '$_base/arroz-pilaf.jpg',
  'Sushi balls': '$_base/sushi-balls.jpg',
  'Chow fan de pollo': '$_base/chow-fan-pollo.jpg',
  'Bibimbap coreano': '$_base/bibimbap-coreano.jpg',
  'Dosas de arroz y lentejas fermentadas': '$_base/dosas-arroz-lentejas.jpg',
  'Arancini siciliano': '$_base/arancini-siciliano.jpg',
  'Arroz rojo': '$_base/arroz-rojo.jpg',
  'Morisqueta de Michoacán': '$_base/morisqueta-michoacan.jpg',
  'Paella mixta': '$_base/paella-mixta.jpg',
  'Arroz del Senyoret': '$_base/arroz-senyoret.jpg',
  'Sorbete de limón': '$_base/sorbete-de-limon.jpg',
  'Matcha latte casero': '$_base/matcha-latte-casero.jpg',
  'Batido verde de espirulina': '$_base/batido-verde-de-espirulina.jpg',
  'Agua de tamarindo': '$_base/agua-de-tamarindo.jpg',
  'Chai latte casero': '$_base/chai-latte-casero.jpg',
  'Chocolate caliente casero': '$_base/chocolate-caliente-casero.jpg',
  'Leche de coco casera': '$_base/leche-de-coco-casera.jpg',
  'Mocaccino casero': '$_base/mocaccino-casero.jpg',
  'Jugo de zanahoria': '$_base/jugo-de-zanahoria.jpg',
  'Torreznos en freidora de aire': '$_base/torreznos-en-freidora-de-aire.jpg',
  'Entraña a la parrilla': '$_base/entrana-a-la-parrilla.jpg',
  'Cochinillo asado tradicional': '$_base/cochinillo-asado-tradicional.jpg',
  'Bulgogi coreano': '$_base/bulgogi-coreano.jpg',
  'Manitas de cerdo guisadas': '$_base/manitas-de-cerdo-guisadas.jpg',
  'Machaca casera': '$_base/machaca-casera.jpg',
  'Ajiaco colombiano': '$_base/ajiaco-colombiano.jpg',
  'Chuleta de cerdo jugosa': '$_base/chuleta-de-cerdo-jugosa.jpg',
  'Lomo saltado': '$_base/lomo-saltado.jpg',
  'Achuras a la parrilla': '$_base/achuras-a-la-parrilla.jpg',
  'Salsa de yogur y eneldo': '$_base/salsa-de-yogur-y-eneldo.jpg',
  'Morcilla encebollada': '$_base/morcilla-encebollada.jpg',
  'Chorizo a la sidra': '$_base/chorizo-a-la-sidra.jpg',
  'Carré de cerdo al horno': '$_base/carre-de-cerdo-al-horno.jpg',
  'Schnitzel de cerdo': '$_base/schnitzel-de-cerdo.jpg',
  'Lomo a la pimienta': '$_base/lomo-a-la-pimienta.jpg',
  'Tonkatsu': '$_base/tonkatsu.jpg',
  // Recetas Diarias - desayunos
  'Carne desmechada con huevos y queso gratinado': '$_base/carne-desmechada-huevos-queso-gratinado.jpg',
  'Huevos a la sartén con tomate, queso cremoso y albahaca': '$_base/huevos-sarten-tomate-queso-albahaca.jpg',
  'Huevos al horno con carne picada, espinaca y queso': '$_base/huevos-horno-carne-espinaca-queso.jpg',
  'Huevos al plato con chorizo, tomate y palta': '$_base/huevos-al-plato-chorizo-tomate-palta.jpg',
  'Huevos cremosos con carne picada especiada y palta': '$_base/huevos-cremosos-carne-picada-especiada-palta.jpg',
  'Huevos revueltos con carne desmechada y tomate': '$_base/huevos-revueltos-carne-desmechada-tomate.jpg',
  'Huevos revueltos con champiñones y cebolla de verdeo': '$_base/huevos-revueltos-champinones-verdeo.jpg',
  'Huevos revueltos con espinaca, tomate y queso cremoso': '$_base/huevos-revueltos-espinaca-tomate-queso.jpg',
  'Huevos revueltos con palta y queso cremoso': '$_base/huevos-revueltos-palta-queso.jpg',
  'Huevos revueltos con pollo, palta y queso': '$_base/huevos-revueltos-pollo-palta-queso.jpg',
  'Huevos revueltos con tomate, cebolla, palta y queso cremoso': '$_base/huevos-revueltos-tomate-cebolla-palta-queso.jpg',
  'Tortilla de zucchini y cebolla': '$_base/tortilla-zucchini-cebolla.jpg',
  'Tortillitas de queso y chía con huevo y palta': '$_base/tortillitas-queso-chia-huevo-palta.jpg',
  'Yogur griego con coco, semillas de lino y almendras': '$_base/yogur-griego-coco-lino-almendras.jpg',
  'Yogur griego con granola keto casera y frutos rojos': '$_base/yogur-griego-granola-keto-frutos-rojos.jpg',
  // Recetas Diarias - snacks
  'Bolitas saladas de pollo y queso': '$_base/bolitas-saladas-pollo-queso.jpg',
  'Frutillas con queso cremoso y almendras': '$_base/frutillas-queso-cremoso-almendras.jpg',
  'Maní tostado con coco y canela': '$_base/mani-tostado-coco-canela.jpg',
  'Mini tartas keto de espinaca y queso': '$_base/mini-tartas-keto-espinaca-queso.jpg',
  'Mousse de yogur griego con cacao puro y nueces': '$_base/mousse-yogur-griego-cacao-nueces.jpg',
  'Nueces y almendras tostadas con canela': '$_base/nueces-almendras-tostadas-canela.jpg',
  'Pepinos rellenos de pollo al limón': '$_base/pepinos-rellenos-pollo-limon.jpg',
  'Pinchos de mozzarella, tomates cherry y albahaca': '$_base/pinchos-mozzarella-cherry-albahaca.jpg',
  'Pudín de chía con yogur natural, coco y vainilla': '$_base/pudin-chia-yogur-coco-vainilla.jpg',
  'Rollitos de lechuga con pollo cremoso y palta': '$_base/rollitos-lechuga-pollo-cremoso-palta.jpg',
  'Rollitos de pepino con queso crema y nueces': '$_base/rollitos-pepino-queso-crema-nueces.jpg',
  'Tomates cherry rellenos de yogur natural y hierbas': '$_base/tomates-cherry-rellenos-yogur-hierbas.jpg',
  'Trufas de cacao amargo, coco y almendras': '$_base/trufas-cacao-coco-almendras.jpg',
  'Vasitos cremosos de limón y yogur': '$_base/vasitos-cremosos-limon-yogur.jpg',
  'Yogur griego con frutillas, chía y nueces': '$_base/yogur-griego-frutillas-chia-nueces.jpg',
  // Recetas Diarias - almuerzos
  'Bife de carne en salsa cremosa de champiñones con brócoli al limón': '$_base/bife-salsa-champinones-brocoli-limon.jpg',
  'Bife de cerdo con salsa de mostaza y hierbas, ensalada y rösti de zucchini': '$_base/bife-cerdo-mostaza-ensalada-rosti-zucchini.jpg',
  'Bondiola de cerdo al horno con ajo y romero, ensalada y soufflé de brócoli': '$_base/bondiola-ajo-romero-ensalada-souffle-brocoli.jpg',
  'Bondiola de cerdo al horno con ensalada de repollo y palta': '$_base/bondiola-horno-ensalada-repollo-palta.jpg',
  'Carne al horno con ensalada de palta y pepino y repollitos de Bruselas': '$_base/carne-horno-ensalada-palta-pepino-repollitos-bruselas.jpg',
  'Carne al horno desmenuzada con puré de zapallitos y ensalada verde': '$_base/carne-desmenuzada-pure-zapallitos-ensalada-verde.jpg',
  'Carne al horno desmenuzada con zapallitos salteados y ensalada de repollo colorado': '$_base/carne-desmenuzada-zapallitos-repollo-colorado.jpg',
  'Carne asada con guacamole, zapallito dorado y ensalada de repollo': '$_base/carne-asada-guacamole-zapallito-ensalada-repollo.jpg',
  'Chuleta de cerdo dorada con puré de coliflor al ajo y ensalada verde': '$_base/chuleta-cerdo-pure-coliflor-ensalada.jpg',
  'Lomo de cerdo al limón y cúrcuma con brócoli salteado y ensalada de pepino': '$_base/lomo-cerdo-limon-curcuma-brocoli-pepino.jpg',
  'Paleta de cerdo al horno con coliflor dorada y ensalada de espinaca': '$_base/paleta-cerdo-coliflor-dorada-espinaca.jpg',
  'Pollo al limón con chauchas salteadas y ensalada de pepino': '$_base/pollo-limon-chauchas-ensalada-pepino.jpg',
  'Pollo dorado en salsa cremosa de queso y limón con brócoli y ensalada de pepino': '$_base/pollo-salsa-queso-limon-brocoli-pepino.jpg',
  'Pollo en salsa cremosa de mostaza con berenjena dorada': '$_base/pollo-salsa-mostaza-berenjena-dorada.jpg',
  // Recetas Diarias - cenas
  'Berenjenas gratinadas con pollo y muzzarella': '$_base/berenjenas-gratinadas-pollo-muzzarella.jpg',
  'Carne vacuna salteada con champiñones y repollo': '$_base/carne-salteada-champinones-repollo.jpg',
  'Cazuela de carne desmenuzada con espinaca y muzzarella': '$_base/cazuela-carne-desmenuzada-espinaca-muzzarella.jpg',
  'Champiñones rellenos de carne picada y muzzarella': '$_base/champinones-rellenos-carne-muzzarella.jpg',
  'Crema de pollo, coliflor y espinaca': '$_base/crema-pollo-coliflor-espinaca.jpg',
  'Hamburguesa casera con queso y ensalada de repollo y palta': '$_base/hamburguesa-casera-queso-ensalada-repollo-palta.jpg',
  'Hamburguesas caseras de cerdo con ensalada cremosa de repollo': '$_base/hamburguesas-cerdo-ensalada-cremosa-repollo.jpg',
  'Hojas de repollo rellenas de carne picada y palta': '$_base/hojas-repollo-rellenas-carne-palta.jpg',
  'Lasaña de zucchini con carne picada y muzzarella': '$_base/lasana-zucchini-carne-muzzarella.jpg',
  'Pechuga de pollo en salsa de mostaza y hierbas con espárragos al horno': '$_base/pechuga-pollo-mostaza-hierbas-esparragos.jpg',
  'Pechuga rellena de mozzarella y espinaca con ensalada': '$_base/pechuga-rellena-mozzarella-espinaca-ensalada.jpg',
  'Pollo al horno con salsa de ajo, brócoli y champiñones': '$_base/pollo-horno-salsa-ajo-brocoli-champinones.jpg',
  'Pollo desmenuzado con palta, pepino y aderezo de limón': '$_base/pollo-desmenuzado-palta-pepino-limon.jpg',
  'Rollitos de omelette con palta y repollo': '$_base/rollitos-omelette-palta-repollo.jpg',
  'Sopa cremosa de champiñones con pollo desmenuzado': '$_base/sopa-cremosa-champinones-pollo.jpg',
  'Zapallitos redondos rellenos de carne picada y queso cremoso': '$_base/zapallitos-redondos-rellenos-carne-queso.jpg',
  'Zapallitos verdes rellenos de cerdo, espinaca y queso': '$_base/zapallitos-rellenos-cerdo-espinaca-queso.jpg',
  // Recetas Diarias - bebidas
  'Infusión de romero, limón y menta': '$_base/infusion-romero-limon-menta.jpg',
  'Licuado de coco, cacao amargo y canela': '$_base/licuado-coco-cacao-canela.jpg',
  'Licuado de coco, vainilla y frutillas sin azúcar': '$_base/licuado-coco-vainilla-frutillas.jpg',
  'Licuado de frutilla y coco': '$_base/licuado-frutilla-coco.jpg',
  'Licuado de frutilla, coco y canela': '$_base/licuado-frutilla-coco-canela.jpg',
  'Licuado de frutilla, palta y yogur natural': '$_base/licuado-frutilla-palta-yogur.jpg',
  'Licuado de frutilla, yogur natural y canela': '$_base/licuado-frutilla-yogur-canela.jpg',
  'Licuado de frutillas, yogur natural y chía': '$_base/licuado-frutillas-yogur-chia.jpg',
  'Licuado de frutos rojos con leche de coco y yogur griego': '$_base/licuado-frutos-rojos-coco-yogur-griego.jpg',
  'Licuado de maracuyá, menta y chía': '$_base/licuado-maracuya-menta-chia.jpg',
  'Licuado de palta, limón y canela': '$_base/licuado-palta-limon-canela.jpg',
  'Licuado de pepino, limón, menta y jengibre': '$_base/licuado-pepino-limon-menta-jengibre.jpg',
  'Licuado verde de palta, pepino, limón y jengibre': '$_base/licuado-verde-palta-pepino-limon-jengibre.jpg',
  'Limonada con menta y jengibre': '$_base/limonada-menta-jengibre.jpg',
  // Recetas Diarias - postres
  'Frutillas con crema de yogur y cacao': '$_base/frutillas-crema-yogur-cacao.jpg',
};

/// Devuelve la URL remota de la imagen para una receta del catálogo, o null si no tiene.
String? recipeImageUrl(String title) => kRecipeImageUrls[title];
