/// Mapa de recetas del catálogo base -> foto local curada a mano, para no depender
/// de imágenes de stock genéricas (que muchas veces no corresponden al plato real).
/// Las fotos viven en assets/recipe_images/ (declaradas en pubspec.yaml).
/// La clave es el título EXACTO de la receta tal como está en recipes.seed.ts.
const Map<String, String> kRecipeImageAssets = {
  'Milanesas de pollo con puré de papas': 'assets/recipe_images/milanesas-pollo-pure-papas.jpg',
  'Tortilla de papas y huevo': 'assets/recipe_images/tortilla-papas-huevo.jpg',
  'Arroz con pollo': 'assets/recipe_images/arroz-con-pollo.jpg',
  'Ensalada de lentejas': 'assets/recipe_images/ensalada-lentejas.jpg',
  'Tarta de verduras': 'assets/recipe_images/tarta-verduras.jpg',
  'Fideos con salsa de tomate y ajo': 'assets/recipe_images/fideos-tomate-ajo.jpg',
  'Ensalada César simple': 'assets/recipe_images/ensalada-cesar.jpg',
  'Guiso de lentejas con carne': 'assets/recipe_images/guiso-lentejas-carne.jpg',
  'Pescado al horno con papas y zanahoria': 'assets/recipe_images/pescado-horno-papas-zanahoria.jpg',
  'Ensalada mixta de verduras': 'assets/recipe_images/ensalada-mixta-verduras.jpg',
  'Sopa de zanahoria': 'assets/recipe_images/sopa-zanahoria.jpg',
  'Panqueques caseros': 'assets/recipe_images/panqueques-caseros.jpg',
  'Sandwich de pollo y vegetales': 'assets/recipe_images/sandwich-pollo-vegetales.jpg',
  'Ensalada de frutas con yogur': 'assets/recipe_images/ensalada-frutas-yogur.jpg',
  'Omelette de queso': 'assets/recipe_images/omelette-queso.jpg',
  'Arroz con verduras salteadas': 'assets/recipe_images/arroz-verduras-salteadas.jpg',
  'Energy balls crudas de dátil y cacao': 'assets/recipe_images/energy-balls-datil-cacao.jpg',
  'Leche de almendras casera': 'assets/recipe_images/leche-almendras.jpg',
  'Ensalada crudivegana de zanahoria, manzana y limón':
      'assets/recipe_images/ensalada-crudivegana-zanahoria-manzana-limon.jpg',
  'Helado crudo de banana y cacao': 'assets/recipe_images/helado-banana-cacao.jpg',
  'Granola cruda de avena y semillas': 'assets/recipe_images/granola-avena-semillas.jpg',
  'Bowl crudo de manzana, chía y limón': 'assets/recipe_images/bowl-manzana-chia-limon.jpg',
  'Pollo a la mostaza': 'assets/recipe_images/pollo-mostaza.jpg',
  'Pollo al curry': 'assets/recipe_images/pollo-curry.jpg',
  'Pizza de pollo': 'assets/recipe_images/pizza-pollo.jpg',
  'Pollo al limón y ajo': 'assets/recipe_images/pollo-limon-ajo.jpg',
  'Pollo crocante con yogur y semillas': 'assets/recipe_images/pollo-crocante-yogur-semillas.jpg',
  'Milanesas de berenjena al horno': 'assets/recipe_images/milanesas-berenjena.jpg',
  'Guacamole casero': 'assets/recipe_images/guacamole.jpg',
  'Ensalada de garbanzos con verduras': 'assets/recipe_images/ensalada-garbanzos.jpg',
  'Tarta de atún y verduras': 'assets/recipe_images/tarta-atun-verduras.jpg',
  'Batatas al horno con especias': 'assets/recipe_images/batatas-horno-especias.jpg',
  'Crema de calabaza': 'assets/recipe_images/crema-calabaza.jpg',
  'Buñuelos de acelga': 'assets/recipe_images/bunuelos-acelga.jpg',
  'Bife a la plancha con batatas al horno': 'assets/recipe_images/bife-plancha-batatas.jpg',
  'Bowl de yogur, granola y banana': 'assets/recipe_images/bowl-yogur-granola-banana.jpg',
  'Wrap de pollo, palta y vegetales': 'assets/recipe_images/wrap-pollo-palta.jpg',
  'Bowl de atún, huevo y almendras': 'assets/recipe_images/bowl-atun-huevo-almendras.jpg',
  'Tostadas de atún, huevo y queso': 'assets/recipe_images/tostadas-atun-huevo-queso.jpg',
  'Ensalada de brócoli y coliflor con queso':
      'assets/recipe_images/ensalada-brocoli-coliflor-queso.jpg',
  'Bife con brócoli y batatas al horno': 'assets/recipe_images/bife-brocoli-batatas.jpg',
  'Sándwich de pepino y pollo': 'assets/recipe_images/sandwich-pepino-pollo.jpg',
  'Arroz con setas meloso': 'assets/recipe_images/arroz-setas-meloso.jpg',
  'Paella de carne': 'assets/recipe_images/paella-carne.jpg',
  'Pan con psyllium': 'assets/recipe_images/pan-psyllium.jpg',
  'Cuscús base: cómo se cocina': 'assets/recipe_images/cuscus-base.jpg',
  'Picante de pollo': 'assets/recipe_images/picante-pollo.jpg',
  'Arroz con atún': 'assets/recipe_images/arroz-atun.jpg',
  'Pabellón criollo': 'assets/recipe_images/pabellon-criollo.jpg',
  'Paella de pollo': 'assets/recipe_images/paella-pollo.jpg',
  'Arroz con bacalao': 'assets/recipe_images/arroz-bacalao.jpg',
  'Arroz pilaf': 'assets/recipe_images/arroz-pilaf.jpg',
  'Sushi balls': 'assets/recipe_images/sushi-balls.jpg',
  'Chow fan de pollo': 'assets/recipe_images/chow-fan-pollo.jpg',
  'Bibimbap coreano': 'assets/recipe_images/bibimbap-coreano.jpg',
  'Dosas de arroz y lentejas fermentadas': 'assets/recipe_images/dosas-arroz-lentejas.jpg',
  'Arancini siciliano': 'assets/recipe_images/arancini-siciliano.jpg',
  'Arroz rojo': 'assets/recipe_images/arroz-rojo.jpg',
  'Morisqueta de Michoacán': 'assets/recipe_images/morisqueta-michoacan.jpg',
  'Paella mixta': 'assets/recipe_images/paella-mixta.jpg',
  'Arroz del Senyoret': 'assets/recipe_images/arroz-senyoret.jpg',
  'Wrap integral de avena y huevo': 'assets/recipe_images/wrap-avena-huevo.jpg',
  'Galletas de avena fáciles': 'assets/recipe_images/galletas-avena.jpg',
  'Budín de cacao y banana': 'assets/recipe_images/budin-cacao-banana.jpg',
  'Budín de zanahoria y naranja': 'assets/recipe_images/budin-zanahoria-naranja.jpg',
  'Budín de yogur y frutos rojos': 'assets/recipe_images/budin-yogur-frutos-rojos.jpg',
  'Budín de manzana y avena': 'assets/recipe_images/budin-manzana-avena.jpg',
  'Fideos Food Wars: mapo tofu, curry y albóndiga': 'assets/recipe_images/food-wars-mapo-tofu-curry.jpg',
  'Pudín de chía': 'assets/recipe_images/pudin-chia.jpg',
  'Fajitas de semillas': 'assets/recipe_images/fajitas-semillas.jpg',
  'Pancitos de queso': 'assets/recipe_images/pancitos-queso.jpg',
  'Pancake de coco': 'assets/recipe_images/pancake-coco.jpg',
  'Manzana tibia con canela y nueces': 'assets/recipe_images/manzana-tibia-canela-nueces.jpg',
  'Muffins de banana y almendras': 'assets/recipe_images/muffins-banana-almendras.jpg',
  'Pan proteico en 1 minuto': 'assets/recipe_images/pan-proteico-1-minuto.jpg',
  'Barrita de coco y chocolate': 'assets/recipe_images/barrita-coco-chocolate.jpg',
  'Coquitos': 'assets/recipe_images/coquitos.jpg',
  'Budín de naranja': 'assets/recipe_images/budin-naranja.jpg',
  'Volcán de chocolate proteico': 'assets/recipe_images/volcan-chocolate-proteico.jpg',
  'Crema de palta y huevo': 'assets/recipe_images/crema-palta-huevo.jpg',
  'Tortita de manzana': 'assets/recipe_images/tortita-manzana.jpg',
  'Muffin proteico': 'assets/recipe_images/muffin-proteico.jpg',
  'Nube proteica': 'assets/recipe_images/nube-proteica.jpg',
  'Fajita de almendras': 'assets/recipe_images/fajita-almendras.jpg',
  'Tortita de chocolate en taza': 'assets/recipe_images/tortita-chocolate-taza.jpg',
  'Budincito de yogur y limón': 'assets/recipe_images/budincito-yogur-limon.jpg',
  'Galletitas de coco': 'assets/recipe_images/galletitas-coco.jpg',
  'Panquequitos de yogur y almendras': 'assets/recipe_images/panquequitos-yogur-almendras.jpg',
  'Postre cremoso de café': 'assets/recipe_images/postre-cremoso-cafe.jpg',
  'Pan de yogur y almendras': 'assets/recipe_images/pan-yogur-almendras.jpg',
  'Dip de yogur griego con palta y limón': 'assets/recipe_images/dip-yogur-palta-limon.jpg',
  'Yogur griego crunch helado': 'assets/recipe_images/yogur-griego-crunch-helado.jpg',
  'Cheesecake de yogur griego': 'assets/recipe_images/cheesecake-yogur-griego.jpg',
  'Galletas con chispas de chocolate y maní': 'assets/recipe_images/galletas-chispas-chocolate-mani.jpg',
  'Galletitas de avena y limón': 'assets/recipe_images/galletitas-avena-limon.jpg',
  'Flan de avena': 'assets/recipe_images/flan-avena.jpg',
  'Pancitos sin gluten': 'assets/recipe_images/pancitos-sin-gluten.jpg',
  'Galletitas de coco y naranja sin harinas': 'assets/recipe_images/galletitas-coco-naranja.jpg',
  'Mezcla proteica casera': 'assets/recipe_images/mezcla-proteica-casera.jpg',
  'Tortilla de zapallitos y queso con ensalada fresca': 'assets/recipe_images/tortilla-zapallitos-queso-ensalada.jpg',
  'Wok de pollo y vegetales': 'assets/recipe_images/wok-pollo-vegetales.jpg',
  'Sopa crema antiinflamatoria de zapallo y pollo': 'assets/recipe_images/sopa-crema-zapallo-pollo.jpg',
  'Omelette de jamón, queso y palta': 'assets/recipe_images/omelette-jamon-queso-palta.jpg',
  'Manzana con chocolate y frutos secos': 'assets/recipe_images/manzana-chocolate-frutos-secos.jpg',
  'Bocaditos crocantes de chocolate': 'assets/recipe_images/bocaditos-crocantes-chocolate.jpg',
  'Bocaditos helados de yogur y frutilla': 'assets/recipe_images/bocaditos-helados-yogur-frutilla.jpg',
  'Chips de fruta con canela': 'assets/recipe_images/chips-fruta-canela.jpg',
  'Flan proteico en taza': 'assets/recipe_images/flan-proteico-taza.jpg',
  'Hamburguesita de huevo': 'assets/recipe_images/hamburguesita-huevo.jpg',
  'Espárragos gratinados con cherry y parmesano': 'assets/recipe_images/esparragos-gratinados-cherry-parmesano.jpg',
  'Carbonada': 'assets/recipe_images/carbonada.jpg',
  'Majadito': 'assets/recipe_images/majadito.jpg',
  'Silpancho': 'assets/recipe_images/silpancho.jpg',
  'Pollo Chijaukay con arroz chaufa': 'assets/recipe_images/pollo-chijaukay-chaufa.jpg',
  'Caigua rellena de carne': 'assets/recipe_images/caigua-rellena-carne.jpg',
  'Pollo tipakay': 'assets/recipe_images/pollo-tipakay.jpg',
  'Arroz paisa colombiano': 'assets/recipe_images/arroz-paisa-colombiano.jpg',
  'Gohan': 'assets/recipe_images/gohan.jpg',
  'Arroz con coco': 'assets/recipe_images/arroz-con-coco.jpg',
  'Ensalada de quinoa mediterránea': 'assets/recipe_images/ensalada-quinoa-mediterranea.jpg',
  'Judías verdes con patatas': 'assets/recipe_images/judias-verdes-patatas.jpg',
  'Ensaladilla rusa': 'assets/recipe_images/ensaladilla-rusa.jpg',
  'Crema ácida casera': 'assets/recipe_images/crema-acida-casera.jpg',
  'Habichuelas con chorizo': 'assets/recipe_images/habichuelas-chorizo.jpg',
  'Berenjenas en freidora de aire': 'assets/recipe_images/berenjenas-freidora-aire.jpg',
  'Hinojo gratinado': 'assets/recipe_images/hinojo-gratinado.jpg',
  'Ensalada de escarola con granada': 'assets/recipe_images/ensalada-escarola-granada.jpg',
  'Ensalada de nopales': 'assets/recipe_images/ensalada-nopales.jpg',
  'Ensalada de porotos blancos': 'assets/recipe_images/ensalada-porotos-blancos.jpg',
  'Ensalada de pepino': 'assets/recipe_images/ensalada-pepino.jpg',
  'Salsa César casera': 'assets/recipe_images/salsa-cesar-casera.jpg',
  'Ensalada alemana con salchichas': 'assets/recipe_images/ensalada-alemana-salchichas.jpg',
  'Ensalada griega': 'assets/recipe_images/ensalada-griega.jpg',
  'Pipirrana andaluza': 'assets/recipe_images/pipirrana-andaluza.jpg',
  'Ensalada caprese': 'assets/recipe_images/ensalada-caprese.jpg',
  'Chapsui de pollo': 'assets/recipe_images/chapsui-pollo.jpg',
  'Sajta de pollo boliviano': 'assets/recipe_images/sajta-pollo-boliviano.jpg',
  'Salpicón de pollo': 'assets/recipe_images/salpicon-pollo.jpg',
  'Tomates verdes fritos': 'assets/recipe_images/tomates-verdes-fritos.jpg',
  'Esquites mexicanos': 'assets/recipe_images/esquites-mexicanos.jpg',
  'Salpicón de res': 'assets/recipe_images/salpicon-res.jpg',
  'Pollo a la jardinera': 'assets/recipe_images/pollo-jardinera.jpg',
  'Poke bowl casero': 'assets/recipe_images/poke-bowl-casero.jpg',
  'Ensalada de burrata': 'assets/recipe_images/ensalada-burrata.jpg',
  'Ensalada de altramuces': 'assets/recipe_images/ensalada-altramuces.jpg',
  'Atascaburras murciano': 'assets/recipe_images/atascaburras-murciano.jpg',
  'Ensalada campera': 'assets/recipe_images/ensalada-campera.jpg',
  'Alcachofas con jamón': 'assets/recipe_images/alcachofas-jamon.jpg',
  'Ensalada malagueña': 'assets/recipe_images/ensalada-malaguena.jpg',
  'Ensalada de zanahoria': 'assets/recipe_images/ensalada-zanahoria.jpg',
  'Ensalada de manzana navideña': 'assets/recipe_images/ensalada-manzana-navidena.jpg',
  'Mayonesa de ave': 'assets/recipe_images/mayonesa-ave.jpg',
  'Ensalada de papa americana': 'assets/recipe_images/ensalada-papa-americana.jpg',
  'Ensalada de coditos': 'assets/recipe_images/ensalada-coditos.jpg',
  'Ensalada murciana': 'assets/recipe_images/ensalada-murciana.jpg',
  'Salpicón de marisco': 'assets/recipe_images/salpicon-marisco.jpg',
  'Aguachile de camarón': 'assets/recipe_images/aguachile-camaron.jpg',
  'Vinagreta de mostaza': 'assets/recipe_images/vinagreta-mostaza.jpg',
  'Pico de gallo': 'assets/recipe_images/pico-de-gallo.jpg',
  'Coleslaw': 'assets/recipe_images/coleslaw.jpg',
  'Ensalada de arroz': 'assets/recipe_images/ensalada-arroz.jpg',
  'Ensalada de frutas': 'assets/recipe_images/ensalada-frutas.jpg',
  'Ensalada de lentejas fría': 'assets/recipe_images/ensalada-lentejas-fria.jpg',
  'Ensalada de garbanzos y tomate': 'assets/recipe_images/ensalada-garbanzos-tomate.jpg',
  'Ensalada de pasta': 'assets/recipe_images/ensalada-pasta.jpg',
  'Ensalada César con pollo': 'assets/recipe_images/ensalada-cesar-pollo.jpg',
  'Causa peruana de atún': 'assets/recipe_images/causa-peruana-atun.jpg',
  'Pan de hamburguesa sin gluten': 'assets/recipe_images/pan-hamburguesa-sin-gluten.jpg',
  'Budín de chocolate sin gluten': 'assets/recipe_images/budin-chocolate-sin-gluten.jpg',
  'Budín de naranja glaseado sin gluten': 'assets/recipe_images/budin-naranja-glaseado-sin-gluten.jpg',
  'Ñoquis de zanahoria sin gluten': 'assets/recipe_images/noquis-zanahoria-sin-gluten.jpg',
  'Mini-tartas de manzana sin gluten': 'assets/recipe_images/mini-tartas-manzana-sin-gluten.jpg',
  'Pan de pebete sin gluten': 'assets/recipe_images/pan-pebete-sin-gluten.jpg',
  'Capelettinis de jamón y queso sin gluten': 'assets/recipe_images/capelettinis-jamon-queso-sin-gluten.jpg',
  'Cookies con chips de chocolate sin gluten': 'assets/recipe_images/cookies-chips-chocolate-sin-gluten.jpg',
  'Pastafrola sin gluten': 'assets/recipe_images/pastafrola-sin-gluten.jpg',
  'Bizcochuelo de chocolate sin gluten': 'assets/recipe_images/bizcochuelo-chocolate-sin-gluten.jpg',
  'Tarta de coco y dulce de leche sin gluten': 'assets/recipe_images/tarta-coco-dulce-leche-sin-gluten.jpg',
  'Grisines de queso y aceitunas sin gluten': 'assets/recipe_images/grisines-queso-aceitunas-sin-gluten.jpg',
  'Budín salado de queso y aceitunas sin gluten': 'assets/recipe_images/budin-salado-queso-aceitunas-sin-gluten.jpg',
  'Budín marmolado sin gluten': 'assets/recipe_images/budin-marmolado-sin-gluten.jpg',
  'Ravioles de jamón y queso sin gluten': 'assets/recipe_images/ravioles-jamon-queso-sin-gluten.jpg',
  'Crepes de mandarina sin gluten': 'assets/recipe_images/crepes-mandarina-sin-gluten.jpg',
  'Pan para sándwich de milanesa sin gluten': 'assets/recipe_images/pan-sandwich-milanesa-sin-gluten.jpg',
  'Coquitos con miel sin gluten': 'assets/recipe_images/coquitos-miel-sin-gluten.jpg',
  'Empanadas de pollo (masa sin gluten)': 'assets/recipe_images/empanadas-pollo-sin-gluten.jpg',
  'Budín de mandarina sin gluten': 'assets/recipe_images/budin-mandarina-sin-gluten.jpg',
  'Pan de sándwich sin gluten': 'assets/recipe_images/pan-sandwich-sin-gluten.jpg',
  'Medialunas sin gluten': 'assets/recipe_images/medialunas-sin-gluten.jpg',
  'Rolls de canela sin gluten': 'assets/recipe_images/rolls-canela-sin-gluten.jpg',
  'Donas de café y chocolate sin gluten': 'assets/recipe_images/donas-cafe-chocolate-sin-gluten.jpg',
  'Scones dulces sin gluten': 'assets/recipe_images/scones-dulces-sin-gluten.jpg',
  'Pancakes de coco y limón sin gluten': 'assets/recipe_images/pancakes-coco-limon-sin-gluten.jpg',
  'Pastas caseras sin gluten': 'assets/recipe_images/pastas-caseras-sin-gluten.jpg',
  'Pastelitos sin gluten': 'assets/recipe_images/pastelitos-sin-gluten.jpg',
  'Pan brioche sin gluten': 'assets/recipe_images/pan-brioche-sin-gluten.jpg',
  'Pizzetas sin gluten': 'assets/recipe_images/pizzetas-sin-gluten.jpg',
  'Pancakes de coco y pera sin gluten': 'assets/recipe_images/pancakes-coco-pera-sin-gluten.jpg',
  'Cookies de chocolate y limón sin gluten': 'assets/recipe_images/cookies-chocolate-limon-sin-gluten.jpg',
  'Torta de manzana sin gluten': 'assets/recipe_images/torta-manzana-sin-gluten.jpg',
  'Pizza casera sin gluten': 'assets/recipe_images/pizza-casera-sin-gluten.jpg',
  'Rapiditas sin gluten': 'assets/recipe_images/rapiditas-sin-gluten.jpg',
  'Pan en microondas en 10 minutos': 'assets/recipe_images/pan-microondas-10-minutos.jpg',
  'Crepes sin gluten': 'assets/recipe_images/crepes-sin-gluten.jpg',
  'Rosca de pascua sin gluten': 'assets/recipe_images/rosca-pascua-sin-gluten.jpg',
  'Panchos sin gluten': 'assets/recipe_images/panchos-sin-gluten.jpg',
  'Sorbete de limón': 'assets/recipe_images/sorbete-de-limon.jpg',
  'Matcha latte casero': 'assets/recipe_images/matcha-latte-casero.jpg',
  'Batido verde de espirulina': 'assets/recipe_images/batido-verde-de-espirulina.jpg',
  'Agua de tamarindo': 'assets/recipe_images/agua-de-tamarindo.jpg',
  'Chai latte casero': 'assets/recipe_images/chai-latte-casero.jpg',
  'Chocolate caliente casero': 'assets/recipe_images/chocolate-caliente-casero.jpg',
  'Leche de coco casera': 'assets/recipe_images/leche-de-coco-casera.jpg',
  'Mocaccino casero': 'assets/recipe_images/mocaccino-casero.jpg',
  'Jugo de zanahoria': 'assets/recipe_images/jugo-de-zanahoria.jpg',
  'Torreznos en freidora de aire': 'assets/recipe_images/torreznos-en-freidora-de-aire.jpg',
  'Entraña a la parrilla': 'assets/recipe_images/entrana-a-la-parrilla.jpg',
  'Cochinillo asado tradicional': 'assets/recipe_images/cochinillo-asado-tradicional.jpg',
  'Bulgogi coreano': 'assets/recipe_images/bulgogi-coreano.jpg',
  'Manitas de cerdo guisadas': 'assets/recipe_images/manitas-de-cerdo-guisadas.jpg',
  'Machaca casera': 'assets/recipe_images/machaca-casera.jpg',
  'Ajiaco colombiano': 'assets/recipe_images/ajiaco-colombiano.jpg',
  'Chuleta de cerdo jugosa': 'assets/recipe_images/chuleta-de-cerdo-jugosa.jpg',
  'Lomo saltado': 'assets/recipe_images/lomo-saltado.jpg',
  'Achuras a la parrilla': 'assets/recipe_images/achuras-a-la-parrilla.jpg',
  'Salsa de yogur y eneldo': 'assets/recipe_images/salsa-de-yogur-y-eneldo.jpg',
  'Morcilla encebollada': 'assets/recipe_images/morcilla-encebollada.jpg',
  'Chorizo a la sidra': 'assets/recipe_images/chorizo-a-la-sidra.jpg',
  'Carré de cerdo al horno': 'assets/recipe_images/carre-de-cerdo-al-horno.jpg',
  'Schnitzel de cerdo': 'assets/recipe_images/schnitzel-de-cerdo.jpg',
  'Lomo a la pimienta': 'assets/recipe_images/lomo-a-la-pimienta.jpg',
  'Tonkatsu': 'assets/recipe_images/tonkatsu.jpg',
  'Porchetta italiana': 'assets/recipe_images/porchetta-italiana.jpg',
  'Costillitas de cerdo a la riojana': 'assets/recipe_images/costillitas-de-cerdo-a-la-riojana.jpg',
  'Croquetas de cocido': 'assets/recipe_images/croquetas-de-cocido.jpg',
  'Espinazo de cerdo guisado en salsa roja': 'assets/recipe_images/espinazo-de-cerdo-guisado-en-salsa-roja.jpg',
  'Pollo tandoori': 'assets/recipe_images/pollo-tandoori.jpg',
  'Pularda rellena al horno': 'assets/recipe_images/pularda-rellena-al-horno.jpg',
  'Pollo en salsa de almendras': 'assets/recipe_images/pollo-en-salsa-de-almendras.jpg',
  'Pechuga de pollo en freidora de aire': 'assets/recipe_images/pechuga-de-pollo-en-freidora-de-aire.jpg',
  'Pavo al horno': 'assets/recipe_images/pavo-al-horno.jpg',
  'Arrollado de papa relleno de pollo y espinaca': 'assets/recipe_images/arrollado-de-papa-relleno-de-pollo-y-espinaca.jpg',
  'Pan de cristal': 'assets/recipe_images/pan-de-cristal.jpg',
  'Pan de ajo': 'assets/recipe_images/pan-de-ajo.jpg',
  'Pan de centeno casero': 'assets/recipe_images/pan-de-centeno-casero.jpg',
  'Pan de campo argentino': 'assets/recipe_images/pan-de-campo-argentino.jpg',
  'Piadina italiana': 'assets/recipe_images/piadina-italiana.jpg',
  'Tortilla a la parrilla': 'assets/recipe_images/tortilla-a-la-parrilla.jpg',
  'Chapati': 'assets/recipe_images/chapati.jpg',
  'Grisines caseros saborizados': 'assets/recipe_images/grisines-caseros-saborizados.jpg',
  'Pizza sin amasar': 'assets/recipe_images/pizza-sin-amasar.jpg',
  'Figacitas de manteca': 'assets/recipe_images/figacitas-de-manteca.jpg',
  'Budín inglés': 'assets/recipe_images/budin-ingles.jpg',
  'Pandoro': 'assets/recipe_images/pandoro.jpg',
  'Pancitos saborizados': 'assets/recipe_images/pancitos-saborizados.jpg',
  'Sopa de galets': 'assets/recipe_images/sopa-de-galets.jpg',
  'Salsa napolitana': 'assets/recipe_images/salsa-napolitana.jpg',
  'Linguini aglio e olio': 'assets/recipe_images/linguini-aglio-e-olio.jpg',
  'Tagliatelle caseros': 'assets/recipe_images/tagliatelle-caseros.jpg',
  'Pierogi ruskie': 'assets/recipe_images/pierogi-ruskie.jpg',
  'Garganelli': 'assets/recipe_images/garganelli.jpg',
  'Rotolo de espinaca y ricota': 'assets/recipe_images/rotolo-de-espinaca-y-ricota.jpg',
  'Cavatelli': 'assets/recipe_images/cavatelli.jpg',
  'Macarrones con chorizo': 'assets/recipe_images/macarrones-con-chorizo.jpg',
  'Fideos con tuco': 'assets/recipe_images/fideos-con-tuco.jpg',
  'Salsa pomodoro': 'assets/recipe_images/salsa-pomodoro.jpg',
  'Tuco argentino': 'assets/recipe_images/tuco-argentino.jpg',
  'Canelones de acelga': 'assets/recipe_images/canelones-de-acelga.jpg',
  'Tarta de calabaza': 'assets/recipe_images/tarta-de-calabaza.jpg',
  'Tartiflette': 'assets/recipe_images/tartiflette.jpg',
  'Tortillas de maíz': 'assets/recipe_images/tortillas-de-maiz.jpg',
  'Fosforitos de hojaldre': 'assets/recipe_images/fosforitos-de-hojaldre.jpg',
  'Empanadas de asado': 'assets/recipe_images/empanadas-de-asado.jpg',
  'Empanadas de carne cortada a cuchillo': 'assets/recipe_images/empanadas-de-carne-cortada-a-cuchillo.jpg',
  'Panzerotti': 'assets/recipe_images/panzerotti.jpg',
  'Sardinas en escabeche': 'assets/recipe_images/sardinas-en-escabeche.jpg',
  'Pulpo a feira': 'assets/recipe_images/pulpo-a-feira.jpg',
  'Merluza a la vasca': 'assets/recipe_images/merluza-a-la-vasca.jpg',
  'Mejillones en escabeche': 'assets/recipe_images/mejillones-en-escabeche.jpg',
  'Calamares encebollados': 'assets/recipe_images/calamares-encebollados.jpg',
  'Berenjenas rellenas de atún': 'assets/recipe_images/berenjenas-rellenas-de-atun.jpg',
  'Cóctel de marisco gourmet': 'assets/recipe_images/coctel-de-marisco-gourmet.jpg',
  'Salmón marinado': 'assets/recipe_images/salmon-marinado.jpg',
  'Crema de marisco': 'assets/recipe_images/crema-de-marisco.jpg',
  'Sashimi casero': 'assets/recipe_images/sashimi-casero.jpg',
  'Mariscada gallega': 'assets/recipe_images/mariscada-gallega.jpg',
  'Pez espada a la plancha': 'assets/recipe_images/pez-espada-a-la-plancha.jpg',
  'Centolla gratinada': 'assets/recipe_images/centolla-gratinada.jpg',
  'Vieiras gratinadas': 'assets/recipe_images/vieiras-gratinadas.jpg',
  'Club sandwich casero': 'assets/recipe_images/club-sandwich-casero.jpg',
  'Queso brie al horno': 'assets/recipe_images/queso-brie-al-horno.jpg',
  'Jalapeños rellenos': 'assets/recipe_images/jalapenos-rellenos.jpg',
  'Salsa sriracha casera': 'assets/recipe_images/salsa-sriracha-casera.jpg',
  'Mortadela a la milanesa': 'assets/recipe_images/mortadela-a-la-milanesa.jpg',
  'Serranito': 'assets/recipe_images/serranito.jpg',
  'Stracciatella de queso': 'assets/recipe_images/stracciatella-de-queso.jpg',
  'Salsa barbacoa casera': 'assets/recipe_images/salsa-barbacoa-casera.jpg',
  'Salsa de almendras': 'assets/recipe_images/salsa-de-almendras.jpg',
  'Muhammara': 'assets/recipe_images/muhammara.jpg',
  'Harissa': 'assets/recipe_images/harissa.jpg',
  'Crema de chirivía': 'assets/recipe_images/crema-de-chirivia.jpg',
  'Crème fraîche casera': 'assets/recipe_images/creme-fraiche-casera.jpg',
  'Sopa de marisco': 'assets/recipe_images/sopa-de-marisco.jpg',
  'Ketchup casero': 'assets/recipe_images/ketchup-casero.jpg',
  'Frangollo': 'assets/recipe_images/frangollo.jpg',
  'Tteokbokki': 'assets/recipe_images/tteokbokki.jpg',
  'Harira': 'assets/recipe_images/harira.jpg',
  'Sopa juliana': 'assets/recipe_images/sopa-juliana.jpg',
  'Cocido gallego': 'assets/recipe_images/cocido-gallego.jpg',
  'Conejo en salsa': 'assets/recipe_images/conejo-en-salsa.jpg',
  'Mollejas de ternera al ajillo': 'assets/recipe_images/mollejas-de-ternera-al-ajillo.jpg',
  'Lentejas guisadas en olla a presión': 'assets/recipe_images/lentejas-guisadas-en-olla-a-presion.jpg',
  'Tumbet mallorquín': 'assets/recipe_images/tumbet-mallorquin.jpg',
  'Verduras al vapor con aderezo de limón': 'assets/recipe_images/verduras-al-vapor-con-aderezo-de-limon.jpg',
  'Coliflor con bechamel': 'assets/recipe_images/coliflor-con-bechamel.jpg',
  'Parmigiana de berenjenas': 'assets/recipe_images/parmigiana-de-berenjenas.jpg',
  'Tofu salteado con soja y ajo': 'assets/recipe_images/tofu-salteado-con-soja-y-ajo.jpg',
  'Puré duquesa': 'assets/recipe_images/pure-duquesa.jpg',
  'Milanesas de soja': 'assets/recipe_images/milanesas-de-soja.jpg',
  'Torrejas de acelga': 'assets/recipe_images/torrejas-de-acelga.jpg',
  'Tamagoyaki': 'assets/recipe_images/tamagoyaki.jpg',
  'Chutney de manzana': 'assets/recipe_images/chutney-de-manzana.jpg',
  'Mermelada de manzana': 'assets/recipe_images/mermelada-de-manzana.jpg',
  'Ajíes en vinagre': 'assets/recipe_images/ajies-en-vinagre.jpg',
  'Chucrut casero': 'assets/recipe_images/chucrut-casero.jpg',
  'Caballa en escabeche': 'assets/recipe_images/caballa-en-escabeche.jpg',
  'Kimchi casero': 'assets/recipe_images/kimchi-casero.jpg',
  'Pickles caseros': 'assets/recipe_images/pickles-caseros.jpg',
  'Guisantes con jamón': 'assets/recipe_images/guisantes-con-jamon.jpg',
  'Higos en almíbar': 'assets/recipe_images/higos-en-almibar.jpg',
  'Torta de naranja con almíbar': 'assets/recipe_images/torta-de-naranja-con-almibar.jpg',
  'Pan de plátano': 'assets/recipe_images/pan-de-platano.jpg',
  'Panettone casero': 'assets/recipe_images/panettone-casero.jpg',
  'Pastel tres leches': 'assets/recipe_images/pastel-tres-leches.jpg',
  'Dacquoise': 'assets/recipe_images/dacquoise.jpg',
  'Torta 1234': 'assets/recipe_images/torta-1234.jpg',
  'Coca de llanda': 'assets/recipe_images/coca-de-llanda.jpg',
  'Bizcocho de plátano': 'assets/recipe_images/bizcocho-de-platano.jpg',
  'Torta de naranja sin huevo': 'assets/recipe_images/torta-de-naranja-sin-huevo.jpg',
  'Rosca de pascua rellena': 'assets/recipe_images/rosca-de-pascua-rellena.jpg',
  'Galletas con chispas de chocolate': 'assets/recipe_images/galletas-con-chispas-de-chocolate.jpg',
  'Galletas de avena y almendras': 'assets/recipe_images/galletas-de-avena-y-almendras.jpg',
  'Crumbl cookies caseras': 'assets/recipe_images/crumbl-cookies-caseras.jpg',
  'Whoopies de chocolate': 'assets/recipe_images/whoopies-de-chocolate.jpg',
  'Galletas lotus': 'assets/recipe_images/galletas-lotus.jpg',
  'Polvorones caseros': 'assets/recipe_images/polvorones-caseros.jpg',
  'Alfajores cordobeses': 'assets/recipe_images/alfajores-cordobeses.jpg',
  'Smores caseros': 'assets/recipe_images/smores-caseros.jpg',
  'Pay de queso': 'assets/recipe_images/pay-de-queso.jpg',
  'Mis moscovitas favoritas': 'assets/recipe_images/mis-moscovitas-favoritas.jpg',
  'Pepas caseras': 'assets/recipe_images/pepas-caseras.jpg',
  'Galletas de avena y banana': 'assets/recipe_images/galletas-de-avena-y-banana.jpg',
  'Galletitas de manteca clásicas': 'assets/recipe_images/galletitas-de-manteca-clasicas.jpg',
  'Tarta lotus sin horno': 'assets/recipe_images/tarta-lotus-sin-horno.jpg',
  'Roscón de reyes': 'assets/recipe_images/roscon-de-reyes.jpg',
  'Clafoutis de cerezas': 'assets/recipe_images/clafoutis-de-cerezas.jpg',
  'Tarta alaska': 'assets/recipe_images/tarta-alaska.jpg',
  'Tarta de la abuela': 'assets/recipe_images/tarta-de-la-abuela.jpg',
  'Cheesecake new york': 'assets/recipe_images/cheesecake-new-york.jpg',
  'Kuchen de nuez': 'assets/recipe_images/kuchen-de-nuez.jpg',
  'Sfogliatella italiana': 'assets/recipe_images/sfogliatella-italiana.jpg',
  'Torrijas en freidora de aire': 'assets/recipe_images/torrijas-en-freidora-de-aire.jpg',
  'Copas de cheesecake con frutos rojos': 'assets/recipe_images/copas-de-cheesecake-con-frutos-rojos.jpg',
  'Cajeta casera': 'assets/recipe_images/cajeta-casera.jpg',
  'Dulce de cayote': 'assets/recipe_images/dulce-de-cayote.jpg',
  'Helado frito': 'assets/recipe_images/helado-frito.jpg',
  'Helado de banana casero': 'assets/recipe_images/helado-de-banana-casero.jpg',
  'Affogato': 'assets/recipe_images/affogato.jpg',
  'Granizado de limón': 'assets/recipe_images/granizado-de-limon.jpg',
  'Banana split': 'assets/recipe_images/banana-split.jpg',
  'Tortitas americanas caseras': 'assets/recipe_images/tortitas-americanas-caseras.jpg',
  'Desayuno americano completo': 'assets/recipe_images/desayuno-americano-completo.jpg',
  'Potaje de garbanzos de la abuela': 'assets/recipe_images/potaje-de-garbanzos-de-la-abuela.jpg',
  'Brochetas de verduras a la parrilla': 'assets/recipe_images/brochetas-de-verduras-a-la-parrilla.jpg',
  'Berenjenas con miel': 'assets/recipe_images/berenjenas-con-miel.jpg',
  'Caponata siciliana': 'assets/recipe_images/caponata-siciliana.jpg',
  'Berenjenas rebozadas': 'assets/recipe_images/berenjenas-rebozadas.jpg',
  'Boronia colombiana': 'assets/recipe_images/boronia-colombiana.jpg',
  'Curry tailandés': 'assets/recipe_images/curry-tailandes.jpg',
  'Babaganoush': 'assets/recipe_images/babaganoush.jpg',
  'Escalivada': 'assets/recipe_images/escalivada.jpg',
  'Arroz con verduras salteado': 'assets/recipe_images/arroz-con-verduras-salteado.jpg',
  'Quiche de verduras': 'assets/recipe_images/quiche-de-verduras.jpg',
  'Sopa fría de coditos con jamón': 'assets/recipe_images/sopa-fria-de-coditos-con-jamon.jpg',
  'Garbanzos con langostinos': 'assets/recipe_images/garbanzos-con-langostinos.jpg',
  'Torrejas de arroz al horno': 'assets/recipe_images/torrejas-de-arroz-al-horno.jpg',
  'Wok de verduras': 'assets/recipe_images/wok-de-verduras.jpg',
  'Sopa crema de choclo': 'assets/recipe_images/sopa-crema-de-choclo.jpg',
  'Chilaquiles verdes': 'assets/recipe_images/chilaquiles-verdes.jpg',
  'Avocado toast': 'assets/recipe_images/avocado-toast.jpg',
  'Panuchos yucatecos': 'assets/recipe_images/panuchos-yucatecos.jpg',
  'Uramaki de salmón y palta': 'assets/recipe_images/uramaki-de-salmon-y-palta.jpg',
  'Tostada de ceviche': 'assets/recipe_images/tostada-de-ceviche.jpg',
  'Tacos de camarón': 'assets/recipe_images/tacos-de-camaron.jpg',
  'Torta de jamón': 'assets/recipe_images/torta-de-jamon.jpg',
  'Torta cubana': 'assets/recipe_images/torta-cubana.jpg',
  'Cóctel de camarones': 'assets/recipe_images/coctel-de-camarones.jpg',
  'Calabaza asada con especias': 'assets/recipe_images/calabaza-asada-con-especias.jpg',
  'Calabaza al horno con ajo y hierbas': 'assets/recipe_images/calabaza-al-horno-con-ajo-y-hierbas.jpg',
  'Ceviche de camarón mexicano': 'assets/recipe_images/ceviche-de-camaron-mexicano.jpg',
  'Sepia a la plancha': 'assets/recipe_images/sepia-a-la-plancha.jpg',
  'Paté de champiñones': 'assets/recipe_images/pate-de-champinones.jpg',
  'Vinagreta de sirope de agave': 'assets/recipe_images/vinagreta-de-sirope-de-agave.jpg',
  'Alfajores de maicena': 'assets/recipe_images/alfajores-de-maicena.jpg',
};

/// Devuelve la ruta del asset local para una receta del catálogo base, o null si
/// no hay una foto curada para ese título (recetas creadas por usuarios o IA).
String? localRecipeImageAsset(String title) => kRecipeImageAssets[title];
