/// Mapa de recetas del catálogo base -> foto local curada a mano, para no depender
/// de imágenes de stock genéricas (que muchas veces no corresponden al plato real).
/// Las fotos viven en assets/recipe_images/ (declaradas en pubspec.yaml).
/// La clave es el título EXACTO de la receta tal como está en recipes.seed.ts.
const Map<String, String> kRecipeImageAssets = {
  'Milanesas de pollo con puré de papas': 'assets/recipe_images/milanesas-pollo-pure-papas.jpg',
  'Tortilla de papas y huevo': 'assets/recipe_images/tortilla-papas-huevo.jpg',
  'Arroz con pollo': 'assets/recipe_images/arroz-con-pollo.jpg',
  'Ensalada de lentejas': 'assets/recipe_images/ensalada-lentejas.jpg',
  'Tarta de verduras': 'assets/recipe_images/tarta-verduras.jpg',
  'Fideos con salsa de tomate y ajo': 'assets/recipe_images/fideos-tomate-ajo.jpg',
  'Ensalada César simple': 'assets/recipe_images/ensalada-cesar.jpg',
  'Guiso de lentejas con carne': 'assets/recipe_images/guiso-lentejas-carne.jpg',
  'Pescado al horno con papas y zanahoria': 'assets/recipe_images/pescado-horno-papas-zanahoria.jpg',
  'Ensalada mixta de verduras': 'assets/recipe_images/ensalada-mixta-verduras.jpg',
  'Sopa de zanahoria': 'assets/recipe_images/sopa-zanahoria.jpg',
  'Panqueques caseros': 'assets/recipe_images/panqueques-caseros.jpg',
  'Sandwich de pollo y vegetales': 'assets/recipe_images/sandwich-pollo-vegetales.jpg',
  'Ensalada de frutas con yogur': 'assets/recipe_images/ensalada-frutas-yogur.jpg',
  'Omelette de queso': 'assets/recipe_images/omelette-queso.jpg',
  'Arroz con verduras salteadas': 'assets/recipe_images/arroz-verduras-salteadas.jpg',
  'Energy balls crudas de dátil y cacao': 'assets/recipe_images/energy-balls-datil-cacao.jpg',
  'Leche de almendras casera': 'assets/recipe_images/leche-almendras.jpg',
  'Ensalada crudivegana de zanahoria, manzana y limón':
      'assets/recipe_images/ensalada-crudivegana-zanahoria-manzana-limon.jpg',
  'Helado crudo de banana y cacao': 'assets/recipe_images/helado-banana-cacao.jpg',
  'Granola cruda de avena y semillas': 'assets/recipe_images/granola-avena-semillas.jpg',
  'Bowl crudo de manzana, chía y limón': 'assets/recipe_images/bowl-manzana-chia-limon.jpg',
  'Pollo a la mostaza': 'assets/recipe_images/pollo-mostaza.jpg',
  'Pollo al curry': 'assets/recipe_images/pollo-curry.jpg',
  'Pizza de pollo': 'assets/recipe_images/pizza-pollo.jpg',
  'Pollo al limón y ajo': 'assets/recipe_images/pollo-limon-ajo.jpg',
  'Pollo crocante con yogur y semillas': 'assets/recipe_images/pollo-crocante-yogur-semillas.jpg',
  'Milanesas de berenjena al horno': 'assets/recipe_images/milanesas-berenjena.jpg',
  'Guacamole casero': 'assets/recipe_images/guacamole.jpg',
  'Ensalada de garbanzos con verduras': 'assets/recipe_images/ensalada-garbanzos.jpg',
  'Tarta de atún y verduras': 'assets/recipe_images/tarta-atun-verduras.jpg',
  'Batatas al horno con especias': 'assets/recipe_images/batatas-horno-especias.jpg',
  'Crema de calabaza': 'assets/recipe_images/crema-calabaza.jpg',
  'Buñuelos de acelga': 'assets/recipe_images/bunuelos-acelga.jpg',
  'Bife a la plancha con batatas al horno': 'assets/recipe_images/bife-plancha-batatas.jpg',
  'Bowl de yogur, granola y banana': 'assets/recipe_images/bowl-yogur-granola-banana.jpg',
  'Wrap de pollo, palta y vegetales': 'assets/recipe_images/wrap-pollo-palta.jpg',
  'Bowl de atún, huevo y almendras': 'assets/recipe_images/bowl-atun-huevo-almendras.jpg',
  'Tostadas de atún, huevo y queso': 'assets/recipe_images/tostadas-atun-huevo-queso.jpg',
  'Ensalada de brócoli y coliflor con queso':
      'assets/recipe_images/ensalada-brocoli-coliflor-queso.jpg',
  'Bife con brócoli y batatas al horno': 'assets/recipe_images/bife-brocoli-batatas.jpg',
  'Sándwich de pepino y pollo': 'assets/recipe_images/sandwich-pepino-pollo.jpg',
  'Arroz con setas meloso': 'assets/recipe_images/arroz-setas-meloso.jpg',
  'Paella de carne': 'assets/recipe_images/paella-carne.jpg',
  'Pan con psyllium': 'assets/recipe_images/pan-psyllium.jpg',
  'Cuscús base: cómo se cocina': 'assets/recipe_images/cuscus-base.jpg',
  'Picante de pollo': 'assets/recipe_images/picante-pollo.jpg',
  'Arroz con atún': 'assets/recipe_images/arroz-atun.jpg',
  'Pabellón criollo': 'assets/recipe_images/pabellon-criollo.jpg',
  'Paella de pollo': 'assets/recipe_images/paella-pollo.jpg',
  'Arroz con bacalao': 'assets/recipe_images/arroz-bacalao.jpg',
  'Arroz pilaf': 'assets/recipe_images/arroz-pilaf.jpg',
  'Sushi balls': 'assets/recipe_images/sushi-balls.jpg',
  'Chow fan de pollo': 'assets/recipe_images/chow-fan-pollo.jpg',
  'Bibimbap coreano': 'assets/recipe_images/bibimbap-coreano.jpg',
  'Dosas de arroz y lentejas fermentadas': 'assets/recipe_images/dosas-arroz-lentejas.jpg',
  'Arancini siciliano': 'assets/recipe_images/arancini-siciliano.jpg',
  'Arroz rojo': 'assets/recipe_images/arroz-rojo.jpg',
  'Morisqueta de Michoacán': 'assets/recipe_images/morisqueta-michoacan.jpg',
  'Paella mixta': 'assets/recipe_images/paella-mixta.jpg',
  'Arroz del Senyoret': 'assets/recipe_images/arroz-senyoret.jpg',
  'Wrap integral de avena y huevo': 'assets/recipe_images/wrap-avena-huevo.jpg',
  'Galletas de avena fáciles': 'assets/recipe_images/galletas-avena.jpg',
  'Budín de cacao y banana': 'assets/recipe_images/budin-cacao-banana.jpg',
  'Budín de zanahoria y naranja': 'assets/recipe_images/budin-zanahoria-naranja.jpg',
  'Budín de yogur y frutos rojos': 'assets/recipe_images/budin-yogur-frutos-rojos.jpg',
  'Budín de manzana y avena': 'assets/recipe_images/budin-manzana-avena.jpg',
  'Fideos Food Wars: mapo tofu, curry y albóndiga': 'assets/recipe_images/food-wars-mapo-tofu-curry.jpg',
  'Pudín de chía': 'assets/recipe_images/pudin-chia.jpg',
  'Fajitas de semillas': 'assets/recipe_images/fajitas-semillas.jpg',
  'Pancitos de queso': 'assets/recipe_images/pancitos-queso.jpg',
  'Pancake de coco': 'assets/recipe_images/pancake-coco.jpg',
  'Manzana tibia con canela y nueces': 'assets/recipe_images/manzana-tibia-canela-nueces.jpg',
  'Muffins de banana y almendras': 'assets/recipe_images/muffins-banana-almendras.jpg',
  'Pan proteico en 1 minuto': 'assets/recipe_images/pan-proteico-1-minuto.jpg',
  'Barrita de coco y chocolate': 'assets/recipe_images/barrita-coco-chocolate.jpg',
  'Coquitos': 'assets/recipe_images/coquitos.jpg',
  'Budín de naranja': 'assets/recipe_images/budin-naranja.jpg',
  'Volcán de chocolate proteico': 'assets/recipe_images/volcan-chocolate-proteico.jpg',
  'Crema de palta y huevo': 'assets/recipe_images/crema-palta-huevo.jpg',
  'Tortita de manzana': 'assets/recipe_images/tortita-manzana.jpg',
  'Muffin proteico': 'assets/recipe_images/muffin-proteico.jpg',
  'Nube proteica': 'assets/recipe_images/nube-proteica.jpg',
  'Fajita de almendras': 'assets/recipe_images/fajita-almendras.jpg',
  'Tortita de chocolate en taza': 'assets/recipe_images/tortita-chocolate-taza.jpg',
  'Budincito de yogur y limón': 'assets/recipe_images/budincito-yogur-limon.jpg',
  'Galletitas de coco': 'assets/recipe_images/galletitas-coco.jpg',
  'Panquequitos de yogur y almendras': 'assets/recipe_images/panquequitos-yogur-almendras.jpg',
  'Postre cremoso de café': 'assets/recipe_images/postre-cremoso-cafe.jpg',
  'Pan de yogur y almendras': 'assets/recipe_images/pan-yogur-almendras.jpg',
  'Dip de yogur griego con palta y limón': 'assets/recipe_images/dip-yogur-palta-limon.jpg',
  'Yogur griego crunch helado': 'assets/recipe_images/yogur-griego-crunch-helado.jpg',
  'Cheesecake de yogur griego': 'assets/recipe_images/cheesecake-yogur-griego.jpg',
  'Galletas con chispas de chocolate y maní': 'assets/recipe_images/galletas-chispas-chocolate-mani.jpg',
  'Galletitas de avena y limón': 'assets/recipe_images/galletitas-avena-limon.jpg',
  'Flan de avena': 'assets/recipe_images/flan-avena.jpg',
  'Pancitos sin gluten': 'assets/recipe_images/pancitos-sin-gluten.jpg',
  'Galletitas de coco y naranja sin harinas': 'assets/recipe_images/galletitas-coco-naranja.jpg',
  'Mezcla proteica casera': 'assets/recipe_images/mezcla-proteica-casera.jpg',
  'Tortilla de zapallitos y queso con ensalada fresca': 'assets/recipe_images/tortilla-zapallitos-queso-ensalada.jpg',
  'Wok de pollo y vegetales': 'assets/recipe_images/wok-pollo-vegetales.jpg',
  'Sopa crema antiinflamatoria de zapallo y pollo': 'assets/recipe_images/sopa-crema-zapallo-pollo.jpg',
  'Omelette de jamón, queso y palta': 'assets/recipe_images/omelette-jamon-queso-palta.jpg',
  'Manzana con chocolate y frutos secos': 'assets/recipe_images/manzana-chocolate-frutos-secos.jpg',
  'Bocaditos crocantes de chocolate': 'assets/recipe_images/bocaditos-crocantes-chocolate.jpg',
  'Bocaditos helados de yogur y frutilla': 'assets/recipe_images/bocaditos-helados-yogur-frutilla.jpg',
  'Chips de fruta con canela': 'assets/recipe_images/chips-fruta-canela.jpg',
  'Flan proteico en taza': 'assets/recipe_images/flan-proteico-taza.jpg',
  'Hamburguesita de huevo': 'assets/recipe_images/hamburguesita-huevo.jpg',
  'Espárragos gratinados con cherry y parmesano': 'assets/recipe_images/esparragos-gratinados-cherry-parmesano.jpg',
  'Carbonada': 'assets/recipe_images/carbonada.jpg',
  'Majadito': 'assets/recipe_images/majadito.jpg',
  'Silpancho': 'assets/recipe_images/silpancho.jpg',
  'Pollo Chijaukay con arroz chaufa': 'assets/recipe_images/pollo-chijaukay-chaufa.jpg',
  'Caigua rellena de carne': 'assets/recipe_images/caigua-rellena-carne.jpg',
  'Pollo tipakay': 'assets/recipe_images/pollo-tipakay.jpg',
  'Arroz paisa colombiano': 'assets/recipe_images/arroz-paisa-colombiano.jpg',
  'Gohan': 'assets/recipe_images/gohan.jpg',
  'Arroz con coco': 'assets/recipe_images/arroz-con-coco.jpg',
  'Ensalada de quinoa mediterránea': 'assets/recipe_images/ensalada-quinoa-mediterranea.jpg',
  'Judías verdes con patatas': 'assets/recipe_images/judias-verdes-patatas.jpg',
  'Ensaladilla rusa': 'assets/recipe_images/ensaladilla-rusa.jpg',
  'Crema ácida casera': 'assets/recipe_images/crema-acida-casera.jpg',
  'Habichuelas con chorizo': 'assets/recipe_images/habichuelas-chorizo.jpg',
  'Berenjenas en freidora de aire': 'assets/recipe_images/berenjenas-freidora-aire.jpg',
  'Hinojo gratinado': 'assets/recipe_images/hinojo-gratinado.jpg',
  'Ensalada de escarola con granada': 'assets/recipe_images/ensalada-escarola-granada.jpg',
  'Ensalada de nopales': 'assets/recipe_images/ensalada-nopales.jpg',
  'Ensalada de porotos blancos': 'assets/recipe_images/ensalada-porotos-blancos.jpg',
  'Ensalada de pepino': 'assets/recipe_images/ensalada-pepino.jpg',
  'Salsa César casera': 'assets/recipe_images/salsa-cesar-casera.jpg',
  'Ensalada alemana con salchichas': 'assets/recipe_images/ensalada-alemana-salchichas.jpg',
  'Ensalada griega': 'assets/recipe_images/ensalada-griega.jpg',
  'Pipirrana andaluza': 'assets/recipe_images/pipirrana-andaluza.jpg',
  'Ensalada caprese': 'assets/recipe_images/ensalada-caprese.jpg',
  'Chapsui de pollo': 'assets/recipe_images/chapsui-pollo.jpg',
  'Sajta de pollo boliviano': 'assets/recipe_images/sajta-pollo-boliviano.jpg',
  'Salpicón de pollo': 'assets/recipe_images/salpicon-pollo.jpg',
  'Tomates verdes fritos': 'assets/recipe_images/tomates-verdes-fritos.jpg',
  'Esquites mexicanos': 'assets/recipe_images/esquites-mexicanos.jpg',
  'Salpicón de res': 'assets/recipe_images/salpicon-res.jpg',
  'Pollo a la jardinera': 'assets/recipe_images/pollo-jardinera.jpg',
  'Poke bowl casero': 'assets/recipe_images/poke-bowl-casero.jpg',
  'Ensalada de burrata': 'assets/recipe_images/ensalada-burrata.jpg',
  'Ensalada de altramuces': 'assets/recipe_images/ensalada-altramuces.jpg',
  'Atascaburras murciano': 'assets/recipe_images/atascaburras-murciano.jpg',
  'Ensalada campera': 'assets/recipe_images/ensalada-campera.jpg',
  'Alcachofas con jamón': 'assets/recipe_images/alcachofas-jamon.jpg',
  'Ensalada malagueña': 'assets/recipe_images/ensalada-malaguena.jpg',
  'Ensalada de zanahoria': 'assets/recipe_images/ensalada-zanahoria.jpg',
  'Ensalada de manzana navideña': 'assets/recipe_images/ensalada-manzana-navidena.jpg',
  'Mayonesa de ave': 'assets/recipe_images/mayonesa-ave.jpg',
  'Ensalada de papa americana': 'assets/recipe_images/ensalada-papa-americana.jpg',
  'Ensalada de coditos': 'assets/recipe_images/ensalada-coditos.jpg',
  'Ensalada murciana': 'assets/recipe_images/ensalada-murciana.jpg',
  'Salpicón de marisco': 'assets/recipe_images/salpicon-marisco.jpg',
  'Aguachile de camarón': 'assets/recipe_images/aguachile-camaron.jpg',
  'Vinagreta de mostaza': 'assets/recipe_images/vinagreta-mostaza.jpg',
  'Pico de gallo': 'assets/recipe_images/pico-de-gallo.jpg',
  'Coleslaw': 'assets/recipe_images/coleslaw.jpg',
  'Ensalada de arroz': 'assets/recipe_images/ensalada-arroz.jpg',
  'Ensalada de frutas': 'assets/recipe_images/ensalada-frutas.jpg',
  'Ensalada de lentejas fría': 'assets/recipe_images/ensalada-lentejas-fria.jpg',
  'Ensalada de garbanzos y tomate': 'assets/recipe_images/ensalada-garbanzos-tomate.jpg',
  'Ensalada de pasta': 'assets/recipe_images/ensalada-pasta.jpg',
  'Ensalada César con pollo': 'assets/recipe_images/ensalada-cesar-pollo.jpg',
  'Causa peruana de atún': 'assets/recipe_images/causa-peruana-atun.jpg',
  'Pan de hamburguesa sin gluten': 'assets/recipe_images/pan-hamburguesa-sin-gluten.jpg',
  'Budín de chocolate sin gluten': 'assets/recipe_images/budin-chocolate-sin-gluten.jpg',
  'Budín de naranja glaseado sin gluten': 'assets/recipe_images/budin-naranja-glaseado-sin-gluten.jpg',
  'Ñoquis de zanahoria sin gluten': 'assets/recipe_images/noquis-zanahoria-sin-gluten.jpg',
  'Mini-tartas de manzana sin gluten': 'assets/recipe_images/mini-tartas-manzana-sin-gluten.jpg',
  'Pan de pebete sin gluten': 'assets/recipe_images/pan-pebete-sin-gluten.jpg',
  'Capelettinis de jamón y queso sin gluten': 'assets/recipe_images/capelettinis-jamon-queso-sin-gluten.jpg',
  'Cookies con chips de chocolate sin gluten': 'assets/recipe_images/cookies-chips-chocolate-sin-gluten.jpg',
  'Pastafrola sin gluten': 'assets/recipe_images/pastafrola-sin-gluten.jpg',
  'Bizcochuelo de chocolate sin gluten': 'assets/recipe_images/bizcochuelo-chocolate-sin-gluten.jpg',
  'Tarta de coco y dulce de leche sin gluten': 'assets/recipe_images/tarta-coco-dulce-leche-sin-gluten.jpg',
  'Grisines de queso y aceitunas sin gluten': 'assets/recipe_images/grisines-queso-aceitunas-sin-gluten.jpg',
  'Budín salado de queso y aceitunas sin gluten': 'assets/recipe_images/budin-salado-queso-aceitunas-sin-gluten.jpg',
  'Budín marmolado sin gluten': 'assets/recipe_images/budin-marmolado-sin-gluten.jpg',
  'Ravioles de jamón y queso sin gluten': 'assets/recipe_images/ravioles-jamon-queso-sin-gluten.jpg',
  'Crepes de mandarina sin gluten': 'assets/recipe_images/crepes-mandarina-sin-gluten.jpg',
  'Pan para sándwich de milanesa sin gluten': 'assets/recipe_images/pan-sandwich-milanesa-sin-gluten.jpg',
  'Coquitos con miel sin gluten': 'assets/recipe_images/coquitos-miel-sin-gluten.jpg',
  'Empanadas de pollo (masa sin gluten)': 'assets/recipe_images/empanadas-pollo-sin-gluten.jpg',
  'Budín de mandarina sin gluten': 'assets/recipe_images/budin-mandarina-sin-gluten.jpg',
  'Pan de sándwich sin gluten': 'assets/recipe_images/pan-sandwich-sin-gluten.jpg',
  'Medialunas sin gluten': 'assets/recipe_images/medialunas-sin-gluten.jpg',
  'Rolls de canela sin gluten': 'assets/recipe_images/rolls-canela-sin-gluten.jpg',
  'Donas de café y chocolate sin gluten': 'assets/recipe_images/donas-cafe-chocolate-sin-gluten.jpg',
  'Scones dulces sin gluten': 'assets/recipe_images/scones-dulces-sin-gluten.jpg',
  'Pancakes de coco y limón sin gluten': 'assets/recipe_images/pancakes-coco-limon-sin-gluten.jpg',
  'Pastas caseras sin gluten': 'assets/recipe_images/pastas-caseras-sin-gluten.jpg',
  'Pastelitos sin gluten': 'assets/recipe_images/pastelitos-sin-gluten.jpg',
  'Pan brioche sin gluten': 'assets/recipe_images/pan-brioche-sin-gluten.jpg',
  'Pizzetas sin gluten': 'assets/recipe_images/pizzetas-sin-gluten.jpg',
  'Pancakes de coco y pera sin gluten': 'assets/recipe_images/pancakes-coco-pera-sin-gluten.jpg',
  'Cookies de chocolate y limón sin gluten': 'assets/recipe_images/cookies-chocolate-limon-sin-gluten.jpg',
  'Torta de manzana sin gluten': 'assets/recipe_images/torta-manzana-sin-gluten.jpg',
  'Pizza casera sin gluten': 'assets/recipe_images/pizza-casera-sin-gluten.jpg',
  'Rapiditas sin gluten': 'assets/recipe_images/rapiditas-sin-gluten.jpg',
  'Pan en microondas en 10 minutos': 'assets/recipe_images/pan-microondas-10-minutos.jpg',
  'Crepes sin gluten': 'assets/recipe_images/crepes-sin-gluten.jpg',
  'Rosca de pascua sin gluten': 'assets/recipe_images/rosca-pascua-sin-gluten.jpg',
  'Panchos sin gluten': 'assets/recipe_images/panchos-sin-gluten.jpg',
};

/// Devuelve la ruta del asset local para una receta del catálogo base, o null si
/// no hay una foto curada para ese título (recetas creadas por usuarios o IA).
String? localRecipeImageAsset(String title) => kRecipeImageAssets[title];
